### ISSUE TITLE
perl latexindent on masOS High Sierra does'nt work

### ISSUE THREAD

**Issue by rmfberlin** [cmhughes/latexindent.pl#101]
If I try `perl latexindent` in teminal I get 

> Cannot write to 'indent.log': Permission denied at /opt/local/lib/perl5/site_perl/5.12.4/Log/Dispatch/File.pm line 100.

Can't find a solution. File permissions for /Log/Dispatch/ are set to read and write.

Thanks a lot

**Comment by cmhughes** [comment]
What happens if you simply type 

latexindent myfile.tex

It looks to me that you might be asking perl to operate on the symlink....?

You might also try

latexindent.pl myfile.tex

**Comment by cmhughes** [comment]
The simplest test is
```
latexindent.pl -v
```
which should show you the version number and date of release of your installed version.

**Comment by rmfberlin** [comment]
`latextindent test.tex` works. Great!
'latexindent -v' results '3.4, 2018-01-13'
'latexindent.pl test.tex' Command not found.

Thanks a lot.

**Comment by cmhughes** [comment]
Cool, sounds like you're up and running, happy TeXing!
