### ISSUE TITLE
Log4Perl

### ISSUE THREAD

**Issue by MrYann** [cmhughes/latexindent.pl#102]
Hi :)

I write latex with VisualStudioCode and the Latex Workshop extension. They automatically call on latexindent to do code formatting, which is nice. However, latexindent requires Log4Perl, which forces me to install a whole group of dependencies. Could this logging be bypassed through an option ? (well, not just the logging, but also the loading of the module -- otherwise, there is no real point)

**Comment by cmhughes** [comment]
Which OS are you using? If Windows, there's a standalone executable, so no modules required :)

**Comment by MrYann** [comment]
It is MacOs.

**Comment by cmhughes** [comment]
I'm not sure if it's possible; I'll happily look into it, but I can't guarantee a quick turn around on it, so I'd say in the short term, you're better off installing the modules.  https://github.com/cmhughes/latexindent.pl/blob/master/helper-scripts/latexindent-module-installer.pl

**Comment by zoehneto** [comment]
An alternative would be to also provide a standalone executable for other platforms, which would be nice for everyone who doesn't want to mess with perl packages (especially since your module install script requires cpanminus which is not installed by default on some distributions). The only downside is, that you have to create the executable on the platform you want to build for so you have to have a Mac in order to build for MacOs.

**Comment by cmhughes** [comment]
Yes indeed, that would be nice. I don't have a Mac, and don't know how to
create an executable file for Mac without one. If anyone knows how, let me
know!

**Comment by cmhughes** [comment]
Following some discussion in https://github.com/cmhughes/latexindent.pl/issues/104 I'm happy to explore the idea of creating a standalone executable for the Mac. It's not clear if I'll be successful, and will rely upon some travis ci magic, which I don't yet know...

At this stage, I don't think it's wise for me to set a precedent of conditionally loading modules -- I don't know which modules the script will need in the future. While it might be possible to side step Log4Perl, there's no way to know if others would be.

**Comment by cmhughes** [comment]
related: https://github.com/travis-ci/travis.rb/issues/581#issuecomment-379637498

**Comment by cmhughes** [comment]
I'm going to close this for now. I haven't found a way to produce a standalone Mac executable file without owning a Mac. Perhaps I'll be able to revisit this at some point in the future.

**Comment by jinyangustc** [comment]
If you use MacTex, then `indentlatex` should already be installed. After installed missing Perl modules, you can use `indentlatex.pl` (by cloning this project) directly or `indentlatex` which comes with MacTex.

To use it with VSCode, you may find my comment in https://github.com/James-Yu/LaTeX-Workshop/issues/725 Interesting.

I don't know Perl and its tools so I don't know how to make the binary. A stand alone binary with all dependencies bundled in is more convenient though.

**Comment by benjavalero** [comment]
To install the missing Perl I have followed the instructions in:

https://gist.github.com/LucaCappelletti94/920186303d71c85e66e76ff989ea6b62#cpan--latexindent

installing Perl modules with "sudo" option.
