### ISSUE TITLE
3.4.x can't locate perl dependencies

### ISSUE THREAD

**Issue by pvjulien** [cmhughes/latexindent.pl#104]
I use Latexindent via [Atom-Beautify](https://atom.io/packages/atom-beautify). I upgraded my TexLive 2017 distribution, which presumably (I don't know for sure) upgraded the Latexindent package, and Latexindent then stopped working. Atom-Beautify told me it couldn't locate Log4Perl. I somehow installed that module, but then I got the following error:

> 
> Can't locate Log/Dispatch/File.pm in @INC (you may need to install the Log::Dispatch::File module) (@INC contains: /usr/local/texlive/2017/texmf-dist/scripts/latexindent /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2/darwin-thread-multi-2level /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /usr/local/texlive/2017/texmf-dist/scripts/latexindent/LatexIndent/LogFile.pm line 24.
> BEGIN failed--compilation aborted at /usr/local/texlive/2017/texmf-dist/scripts/latexindent/LatexIndent/LogFile.pm line 24.
> Compilation failed in require at /usr/local/texlive/2017/texmf-dist/scripts/latexindent/LatexIndent/Document.pm line 25.
> BEGIN failed--compilation aborted at /usr/local/texlive/2017/texmf-dist/scripts/latexindent/LatexIndent/Document.pm line 25.
> Compilation failed in require at /Library/TeX/texbin/latexindent line 27.
> BEGIN failed--compilation aborted at /Library/TeX/texbin/latexindent line 27.

I somehow wasn't able to fix it, so I thought I would try an earlier version of Latexindent. As it happens, if I replace all the Latexindent files with those of version 3.3, Atom-Beautify works again. Neither 3.4 nor 3.4.1 work. I am on macOS 10.13.3.

I honestly don't really know what's happening, but it seems there's a bug somewhere. Since reverting to a previous version of Latexindent works, I thought this may be the problem, but perhaps the issue is somewhere else (e.g. Atom-Beautify, perl, etc.).

**Comment by cmhughes** [comment]
Have you tried installing the perl module

Log::Dispatch::File

You might run, for example,

cpanm Log::Dispatch::File

Can you try this and let me know?

**Comment by pvjulien** [comment]
Yes I did, but to no avail. That's when I tried another version of Latexindent and found out that v. 3.3 was working as before.

Here's the message I get from the command `cpanm Log::Dispatch::File`:

> perl: warning: Setting locale failed.
> perl: warning: Please check that your locale settings:
>         LC_ALL = (unset),
>         LANG = "fr.UTF-8"
>     are supported and installed on your system.
> perl: warning: Falling back to the standard locale ("C").
> !
> ! Can't write to /Library/Perl/5.18 and /usr/local/bin: Installing modules to /Users/username/perl5
> ! To turn off this warning, you have to do one of the following:
> !   - run me as a root or with --sudo option (to install to /Library/Perl/5.18 and /usr/local/bin)
> !   - Configure local::lib in your existing shell to set PERL_MM_OPT etc.
> !   - Install local::lib by running the following commands
> !
> !         cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
> !
> --> Working on Log::Dispatch::File
> Fetching http://www.cpan.org/authors/id/D/DR/DROLSKY/Log-Dispatch-2.67.tar.gz ... OK
> tar: Failed to set default locale
> tar: Failed to set default locale
> Configuring Log-Dispatch-2.67 ... OK
> ==> Found dependencies: Params::ValidationCompiler, Specio::Declare, Specio::Library::Builtins, Specio::Library::String, Specio::Library::Numeric, Specio::Exporter, Test::Needs, Specio
> --> Working on Params::ValidationCompiler
> Fetching http://www.cpan.org/authors/id/D/DR/DROLSKY/Params-ValidationCompiler-0.26.tar.gz ... OK
> tar: Failed to set default locale
> tar: Failed to set default locale
> Configuring Params-ValidationCompiler-0.26 ... OK
> ==> Found dependencies: Specio
> --> Working on Specio
> Fetching http://www.cpan.org/authors/id/D/DR/DROLSKY/Specio-0.42.tar.gz ... OK
> tar: Failed to set default locale
> tar: Failed to set default locale
> Configuring Specio-0.42 ... OK
> ==> Found dependencies: Test::Needs
> --> Working on Test::Needs
> Fetching http://www.cpan.org/authors/id/H/HA/HAARG/Test-Needs-0.002005.tar.gz ... OK
> tar: Failed to set default locale
> tar: Failed to set default locale
> Configuring Test-Needs-0.002005 ... OK
> Building and testing Test-Needs-0.002005 ... FAIL
> ! Installing Test::Needs failed. See /Users/username/.cpanm/work/1518127085.12226/build.log for details. Retry with --force to force install it.
> ! Installing the dependencies failed: Module 'Test::Needs' is not installed
> ! Bailing out the installation for Specio-0.42.
> ! Installing the dependencies failed: Module 'Specio' is not installed
> ! Bailing out the installation for Params-ValidationCompiler-0.26.
> ! Installing the dependencies failed: Module 'Test::Needs' is not installed, Module 'Specio' is not installed, Module 'Specio::Exporter' is not installed, Module 'Specio::Library::Numeric' is not installed, Module 'Specio::Library::String' is not installed, Module 'Specio::Library::Builtins' is not installed, Module 'Specio::Declare' is not installed, Module 'Params::ValidationCompiler' is not installed
> ! Bailing out the installation for Log-Dispatch-2.67.

I replaced my real username with "username".

**Comment by cmhughes** [comment]
Have you tried running it as sudo?

**Comment by pvjulien** [comment]
Yes, sorry, I should have mentioned that. Here's the message I get:

> perl: warning: Setting locale failed.
> perl: warning: Please check that your locale settings:
>         LC_ALL = (unset),
>         LANG = "fr.UTF-8"
>     are supported and installed on your system.
> perl: warning: Falling back to the standard locale ("C").
> --> Working on Log::Dispatch::File
> Fetching http://www.cpan.org/authors/id/D/DR/DROLSKY/Log-Dispatch-2.67.tar.gz ... OK
> tar: Failed to set default locale
> tar: Failed to set default locale
> Configuring Log-Dispatch-2.67 ... OK
> ==> Found dependencies: Specio, Specio::Library::Builtins, Specio::Declare, Specio::Exporter, Params::ValidationCompiler, Test::Needs, Specio::Library::String, Specio::Library::Numeric
> --> Working on Specio
> Fetching http://www.cpan.org/authors/id/D/DR/DROLSKY/Specio-0.42.tar.gz ... OK
> tar: Failed to set default locale
> tar: Failed to set default locale
> Configuring Specio-0.42 ... OK
> ==> Found dependencies: Test::Needs
> --> Working on Test::Needs
> Fetching http://www.cpan.org/authors/id/H/HA/HAARG/Test-Needs-0.002005.tar.gz ... OK
> tar: Failed to set default locale
> tar: Failed to set default locale
> Configuring Test-Needs-0.002005 ... OK
> Building and testing Test-Needs-0.002005 ... FAIL
> ! Installing Test::Needs failed. See /Users/username/.cpanm/work/1518168009.2090/build.log for details. Retry with --force to force install it.
> ! Installing the dependencies failed: Module 'Test::Needs' is not installed
> ! Bailing out the installation for Specio-0.42.
> --> Working on Params::ValidationCompiler
> Fetching http://www.cpan.org/authors/id/D/DR/DROLSKY/Params-ValidationCompiler-0.26.tar.gz ... OK
> tar: Failed to set default locale
> tar: Failed to set default locale
> Configuring Params-ValidationCompiler-0.26 ... OK
> ==> Found dependencies: Specio
> ! Installing the dependencies failed: Module 'Specio' is not installed
> ! Bailing out the installation for Params-ValidationCompiler-0.26.
> ! Installing the dependencies failed: Module 'Specio::Library::Builtins' is not installed, Module 'Specio::Exporter' is not installed, Module 'Params::ValidationCompiler' is not installed, Module 'Specio::Declare' is not installed, Module 'Specio' is not installed, Module 'Specio::Library::Numeric' is not installed, Module 'Specio::Library::String' is not installed, Module 'Test::Needs' is not installed
> ! Bailing out the installation for Log-Dispatch-2.67.

Again I'm not sure what's not working, but from my limited understanding apparently it's also not the best idea to mess with the system perl installation.

**Comment by cmhughes** [comment]
My impression is that this is a MAC problem; I don't own a Mac and haven't ever tried installing anything, so bear that in mind in what follows.

I'd start by searching for 

mac perl warning setting locale failed

If you're comfortable exploring some of the solutions, then you might do so.

I will try to explore the possibility of not requiring the Log4perl module, but this still isn't the best solution as I may require other perl modules for the script in the future that can not be avoided. I will also try to explore the possibility of creating a stand alone Mac executable, but without a Mac, it will be tricky. I'm hopeful travis-ci might be able to help.

**Comment by pvjulien** [comment]
Well, that did the trick!

I followed this [suggestion](https://blogs.agilefaqs.com/2014/01/12/fixing-perl-warning-setting-locale-failed-on-mac-osx/) and then was able to `sudo cpanm Log::Dispatch::File`. The required packages were successfully installed, I installed Latexindent 3.4.1, and everything appears to be working as it should. It just didn't occur to me this 'locale' issue could block the whole installation. Thank you for the suggestion!

I understand your point of view about developing for Mac and, well, it's already great to have this package! And I may move on to Windows in the future. :) I thought of opening the issue here because it seemed the Latexindent update broke my installation, but then it may indeed be something Mac related. Anyhow, thanks for your help!

**Comment by cmhughes** [comment]
That's excellent, I'm glad you've worked through this :) I'm continuing to explore a stand alone executable for the Mac. Keep an eye on https://github.com/cmhughes/latexindent.pl/issues/102 for updates. For the moment, I'll close this issue, but feel free to post if ever you have any issues in the future.
