### ISSUE TITLE
Question: How to uninstall

### ISSUE THREAD

**Issue by ndabAP** [cmhughes/latexindent.pl#109]
How can I uninstall this package after using the helper installer?

**Comment by cmhughes** [comment]
Which 'helper installer' have you used? If it's the one here in the repo,
have you seen

http://latexindentpl.readthedocs.io/en/latest/appendices.html#updating-the-path-variable

**Comment by cmhughes** [comment]
Let me know if this isn't resolved, and I'll reopen it.
