### ISSUE TITLE
Formatting Requires perl (?)

### ISSUE THREAD

**Issue by u2berggeist** [cmhughes/latexindent.pl#110]
_From @u2berggeist on April 21, 2018 15:42_

### Description

I'm trying to have the formatter work and am running into issues. From #118 , I'm assuming the implementation is very similar if not identical to [latex-formatter](https://marketplace.visualstudio.com/items?itemName=nickfode.latex-formatter). I followed the instructions he has for the installation along with the general instructions from [this StackExchange answer](https://tex.stackexchange.com/a/334511/122509) and am getting `failed with exit code 1` message.

I do _not_ have perl installed on my computer and would like not to. I assumed the use of `latexindent.exe` would circumvent this, but I'm not sure tbh. Scrounging around the repo for latex-formatter (specifically [this folder](https://github.com/cmhughes/latexindent.pl/tree/master/helper-scripts)) makes it seem like it's meant to run without perl (ie. `latexindent.exe` should be a self contained program with no dependencies to perl).

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>

```
[11:25:09] Formatting failed with exit code 1
[11:25:09] stderr: latexindent: The script engine could not be found.
latexindent: Data: scriptEngine="perl.exe"
```
</details>

<details>
<summary>Developer Tools Console</summary>

</details>

### How to reproduce

Following instructions from [this StackExchange answer](https://tex.stackexchange.com/a/334511/122509):
1.  Install latexindent via MiKTeX
2. Download latexindent zip from [CTAN](https://www.ctan.org/pkg/latexindent) (pretty sure this is to get the `latexindent.exe`)
3. Replace contents of folder MiKTeX just created with CTAN zip file into the folder 
4. Add the folder containing `latexindent.exe` to the User Path
5. ~Profit~

### Expected behavior

Reformat the code.

### Actual behavior

Nothing, error.

_Copied from original issue: James-Yu/LaTeX-Workshop#564_

**Comment by u2berggeist** [comment]
_From @James-Yu on April 21, 2018 15:45_

It's unrelated to this extension. [src](https://github.com/cmhughes/latexindent.pl)

**Comment by zoehneto** [comment]
While formatting support in Latex Workshop os originally based on the latex-formatter extension, it has since been changed quite a bit. Specifically it seems from the error message that latexindent from MikTex is used (which requires perl) instead of latexindent.exe (which doesn't require perl to be installed). You can configure which is used by specifying `latex-workshop.latexindent.path`.

**Comment by cmhughes** [comment]
Hello!
I'm not really sure what this issue is about... is it about an
implementation on Latex Workshop? If so, what is Latex Workshop?

To test your installation of latexindent.exe, open a command prompt and
run, for example:

latexindent.exe myfile.tex

If this works, then you have it installed correctly. If not, post back with
the error messages.

You are correct that latexindent.exe does not require a perl installation.
Let me know
Chris

**Comment by zoehneto** [comment]
Latex Workshop is a visual studio code extension for latex editing. It supports formatting with latexindent which in this case doesn't work, most likely due to a missing setting.

**Comment by cmhughes** [comment]
A missing setting from latexindent? Or from Latex Workshop?

**Comment by zoehneto** [comment]
From Latex Workshop

**Comment by cmhughes** [comment]
Ok, so what can I do to help at this end? :)

**Comment by zoehneto** [comment]
Nothing really, @u2berggeist should try my solution which will probably solve this issue. If it doesn't it is probably still an issue with the Latex Workshop configuration.

**Comment by cmhughes** [comment]
Have you got latexindent.exe from this repo? Some versions of it are actually just links to the perl file, which isn't what you want...

**Comment by u2berggeist** [comment]
I actually got it from CTAN. I'll try with the executable from this repo.

As for the initial issue, I believe that @zoehneto is correct on the initial reference being for MiKTeX's package for `latexindent.pl` as I was experimenting with deleting the `latexindent.pl` (theoretically "forcing" the usage of the exe) and MiKTeX jumped into repair the installation, and subsequently fail due to perl dependence.

**Comment by u2berggeist** [comment]
Alright, I've traded out `latexindent.exe` and moved it to a completely different folder (ie. not in the MiKTeX installation path).

It's ignoring the "new" folder path and MiKTeX latexindent is the one getting used. This is probably due to `PATH` ordering. So the MiKTeX path get's referenced first, finds it's version of `latexindent`, and tries to run it. I think figuring out the MiKTeX side of things is the key to getting the environment variable working now.

**Comment by u2berggeist** [comment]
Alright I've figure out the issue. MiKTeX wasn't fully uninstalling it's version of `latexindent.pl` due to a stray terminal window I had open. Once I closed that, MiKTeX could successfully uninstall it's version of `latexindent.pl` , therefore leaving my version in a separate folder with `latexindent.exe` in it as the only reference to it.

Thanks for y'all's help!

To any future stragglers, I put my `latexindent` folder in `C:\Tools` as suggested by [this superuser post](https://superuser.com/a/815897/894282)

**Comment by cmhughes** [comment]
Great!
