### ISSUE TITLE
Missing error check

### ISSUE THREAD

**Issue by Krzmbrzl** [cmhughes/latexindent.pl#116]
I just encountered a little bug or an inconvenience (whatever you want to call it) with the tool.

When using it from the command line in one of the following ways, it will freeze (I guess it gets stuck in an endless loop somewhere):
1. Calling the tool with no options whatsoever: `latexindent`
2. Calling the tool without specifying a file: `latexindent --screenlog -o=test.tex -t`

In both cases I failed to provide the tool with the actual file I'd like to format. That admittedly is pretty dumb but it just happened to me and I thought that it'd be nice if the tool detected the user's failure and exits with an error message (something like: `You fool forgot to specify a file!`)

Don't know if this is important but I'm running the tool on a Linux Mint 18.3 machine

**Comment by cmhughes** [comment]
Many thanks for this!

As of V3.4, latexindent.pl supports STDIN As such, it's not stuck, but it
is expecting input from the user.

I think that this could perhaps be clearer; perhaps something like 'enter
your code'?

**Comment by Krzmbrzl** [comment]
So it is expecting the code that should be formatted to be typed in? Then yes I'd say a message like "Please type in the source code that should be formatted" would be really helpful.
If it is actually the filename that should be entered, the message should be altered accordingly to clearly indicate that.

**Comment by cmhughes** [comment]
I'll take a look at this.

The following looks helpful:

https://stackoverflow.com/questions/9661379/how-to-prompt-for-input-and-exit-if-the-user-entered-an-empty-string
