### ISSUE TITLE
Does not properly handle mismatched existing indentation

### ISSUE THREAD

**Issue by mboratko** [cmhughes/latexindent.pl#118]
This is, admittedly, bad form for the original input, however that's exactly the sort of thing this would be useful to clean up. (Currently it also may eat some data.)

**Input:**
```
\begin{align}
x&=x\end{align}
```
**Current Output:**
```
\begin{align}
```

_Note that this will discard everything after the `\begin{align}`!_

**Desired Output:**
```
\begin{align}
    x &= x
\end{align}
```

**Comment by mboratko** [comment]
I should note: I was using this with the version of `latexindent` which came in my TeX distribution, which happened to be v2.2. I downloaded the latest version from Git, and it no longer chops off the output (as above) but it also doesn't move `\end{align}` to it's own line.

**Comment by cmhughes** [comment]
Have you looked at the m switch?

**Comment by cmhughes** [comment]
Starting with

`myfile.tex`
-
```
\begin{align}
 x & =x\end{align}
```
and using 

`localSettings.yaml`
-
```
modifyLineBreaks:
    environments:
        EndStartsOnOwnLine: 1
```
and running
```
latexindent.pl -m -l myfile.tex
```
gives
```
\begin{align}
 x & =x
\end{align}
```
As desired...? Have a look at Section 6 of the documentation for further details.
