### ISSUE TITLE
Add a simple safety check

### ISSUE THREAD

**Issue by mboratko** [cmhughes/latexindent.pl#119]
If `latexindent` only changes whitespace a simple safety check of stripping out all whitespace from the file and counting the resulting bytes before / after would be useful.

**Comment by cmhughes** [comment]
Many thanks for this, it sounds like a very reasonable thing! Do you have
any references/starting points for me to look at?

**Comment by cmhughes** [comment]
`latexindent.pl` can also modify line breaks. Would this affect the bit count? Let me know.
