### ISSUE TITLE
STDIN help text breaks formatting on the editor

### ISSUE THREAD

**Issue by xu-cheng** [cmhughes/latexindent.pl#120]
A STDIN help text is added in https://github.com/cmhughes/latexindent.pl/commit/029bdc5b9d96eccf2f53d0db3b8ce4a47610c8fe. However, this breaks latex format on the vim for me.

The formatting tool in the most editors such as [vim-autoformat](https://github.com/Chiel92/vim-autoformat) work in the following way: 
* It pipes the current buffer to the formatting tool like latexindent using STDIN.
* It captures whatever output of the STDOUT and replace  the editor buffer with the captured content.

Therefore, after 029bdc5b9d96eccf2f53d0db3b8ce4a47610c8fe, there is an extra help text being added in the top of formatted file in the editor.

To solve this issue, please consider make the help text output using STDERR instead of STDOUT.

**Comment by cmhughes** [comment]
Thanks for this, and happy to consider it. It sounds like quite a quick change -- would you like to submit a pull request for review to the develop branch?

**Comment by xu-cheng** [comment]
See #121.

**Comment by cmhughes** [comment]
I'd actually prefer to leave this open, as it makes it clear that I need to mention it in the release notes :)

**Comment by cmhughes** [comment]
Resolved as of https://github.com/cmhughes/latexindent.pl/pull/127 upload to ctan imminently.
