### ISSUE TITLE
Formatting failed with exit code 255

### ISSUE THREAD

**Issue by allenryb** [cmhughes/latexindent.pl#123]
I use `vscode + LaTeX-Workshop extension` to type `.tex` file and `latexindent` is helpful.

Recently I found a problem. When I format the following `.tex` file,

```
\documentclass{article}
\usepackage{amsmath}
\begin{document}
\begin{align}
C^\infty (a [bb) a)
\end{align}
\end{document}
```

vscode with latexindent fails and reminds the following

> Formatting failed. Please refer to LaTeX Workshop Output for details.

LaTeX Workshop Output shows as follows
```
[20:07:22] Formatting with arguments -c,e:/RYB/temp/,e:/RYB/temp/__latexindent_temp.tex,-y="defaultIndent: '  '"

[20:07:23] Formatting failed with exit code 255

[20:07:23] stderr: Use of uninitialized value in pattern match (m//) at C:\Users\ADMINI~1\AppData\Local\Temp\par-41646d696e6973747261746f72\cache-02db827ff06080b5f2c6fae22ee75a9f59717f4c\inc\lib/LatexIndent/Arguments.pm line 125.

Can't call method "indent_children_recursively" on unblessed reference at C:\Users\ADMINI~1\AppData\Local\Temp\par-41646d696e6973747261746f72\cache-02db827ff06080b5f2c6fae22ee75a9f59717f4c\inc\lib/LatexIndent/Indent.pm line 270.
```

**How can I fix it?**
Thanks in advances!

### Additional Information

**Only the line `C^\infty (a [bb) a)` will cause the problem.**

If I replace this part by the following code, then the format can do well.

1. `C (a [bb) a)` : delete the symbol `\infty`
2. `C^\infty  [bb)` : delete the outer parenthesis `()`
3. `C^\infty (a [bb] a)` : modify the inner `[bb)` to '[bb]'

My system is `Windows 10 Home` with `texlive 2018`. Moreover, the problem remains after replacing the `latexindent` folder in `texlive 2018` by the newest codes in `CTAN`.

**Comment by cmhughes** [comment]
Thanks for this;I'll take a closer look soon, I hope, but on first glance,
it certainly looks like a bug.

**Comment by cmhughes** [comment]
Thanks for this. I'd call this a bug, and as of https://github.com/cmhughes/latexindent.pl/commit/14b98892f184c1af549e0b37fc53eab22878c6f8 it is resolved, and will be part of the next release. 

Thanks again.
Chris
