### ISSUE TITLE
add the possiblity of using \[ and \] as verbatim commands?

### ISSUE THREAD

**Issue by dzklaim** [cmhughes/latexindent.pl#124]
The formulas and expressions that I type regularly are impossible to align properly. I would like to disable the script completely on this blocks (no wrapping, align, remove paragraph) :)

thank your for yor work!

**Comment by cmhughes** [comment]
Thanks for this.

So something like the following:
```
specialBeginEnd:
    displayMath:
        begin: '\\\['
        end: '\\\]'
        lookForThis: 1
        verbatim : 1
```

**Comment by dzklaim** [comment]
that would be great :)

**Comment by cmhughes** [comment]
Ok! Tentatively thinking that this should be straight forward, but let me
look at it a little more in detail before committing.

There's a few things to wrap (!!!) up before this, so I've got no idea of
the timeline. My top priority for this project is currently the text wrap
issue, which I'm hoping to have finished soon.

Updates will follow on this thread.

**Comment by dzklaim** [comment]
thanks! my top priority is also the text wrap :)

**Comment by cmhughes** [comment]
I wonder if the following could work:
```
specialBeginEnd:
    displayMath:
        begin: '\\\['
        end: '\\\]'
        lookForThis: verbatim
```
To be treated as verbatim...?

**Comment by dzklaim** [comment]
yes it could work :) but have you implemented it? cause it does not work with my current installation :(

**Comment by cmhughes** [comment]
Not yet :) I'll keep this thread updated as and when I've got something for
you to test.

I'm optimistic this won't be too tricky. Famous last words!

**Comment by cmhughes** [comment]
@dzklaim as of https://github.com/cmhughes/latexindent.pl/commit/697162f61a46ae7ffe52ff23ed23dca10a5682c7 I'd say this is implemented. Can you pull from the `develop` branch and test it?

**Comment by cmhughes** [comment]
Resolved as of https://github.com/cmhughes/latexindent.pl/pull/127 upload to ctan imminently.
