### ISSUE TITLE
Beautification does not respect Editor-Tab-Length

### ISSUE THREAD

**Issue by mroettgen** [cmhughes/latexindent.pl#128]
I have my tab-length set to the default `2` on editor-level. However, latexindent seems to ignore this and just uses whatever I specify in its own settings as indent char once. This resulted in a "beautification" that was quite unexpected, as an indent of just a single space is not really useful.

**Expected behavior** would be that I can set the indent char to a single space in latexindent-settings, then beautification recognizes my editor-tab-length and beautifies accordingly.

**Workaround** for me for now is to set the indent-char to two spaces.

If I can provide any additional info, please let me know 🙂

**Comment by mroettgen** [comment]
Oops, I thought this was exclusively for the atom-beautify package for the atom editor 😯

Please see https://atom.io/ for the editor and https://github.com/Glavin001/atom-beautify for the plug-in that uses your project.

**Comment by cmhughes** [comment]
Ok, thanks.

I'd propose that you see if you can have an option to have the atom plugin call latexindent with the current value of your tab space.

The -y switch would be useful, something like

```
latexindent -y="defaultIndent=<value of tab>" myfile.tex
```

How does that sound?

**Comment by mroettgen** [comment]
I will try using this when I get back home tomorrow evening and let you know. 

Thanks for your help!

**Comment by cmhughes** [comment]
No worries, stay in touch and let me know if there's anything that I can provide.

**Comment by mroettgen** [comment]
I've looked around a bunch but can't seem to find a way to do this myself. Since there is a workaround, I don't think I'll invest more time in this.

The error doesn't seem to be on your end, I've found another issue confirming that: https://github.com/Glavin001/atom-beautify/issues/1706 

Maybe I'll try and get that issue reopened, thank you again for your time 🙂
