### ISSUE TITLE
Sentence indent settings from listing 269: inline math at the beginning of a sentence

### ISSUE THREAD

**Issue by kiryph** [cmhughes/latexindent.pl#130]
I have encountered a second issue with  using the settings from listing 269.
If a sentence is started with inline math, here `$E$`, subsequent lines belonging to this sentence are not indented by two spaces:
```
❯ latexindent demo.tex -m -l=localSettings-lst269.yaml -w
At vero eos et accusam et justo duo dolores et ea rebum.
Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit
  amet.
$E$ is a quantity ipsum dolor sit amet, consectetur adipisicing elit,
sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
  aliquip ex ea commodo consequat.
```

### Expected output
```tex
At vero eos et accusam et justo duo dolores et ea rebum.
Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit
  amet.
$E$ is a quantity ipsum dolor sit amet, consectetur adipisicing elit,
  sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
  aliquip ex ea commodo consequat.
```

**Comment by kiryph** [comment]
I found following setting in help section 6.2.2 sentencesBeginWith. Default is `[A-Z]`.
I have added `$` and `\` for inline math and commands such `\Cref{}` from cleveref.
```
        sentencesBeginWith:
            other: "[A-Z]|\$|\\\\"
```

Does this have side-effects?

**Comment by cmhughes** [comment]
Possibly, that'll b for you to determine on a case by case basis. In
general, I recommend that you customise your YAML.for each file.

**Comment by kiryph** [comment]
I think I can close this issue. I will see if this setting will work in all other situations.

I go paragraph by paragraph and see whether latexindent does what I want. It will take time until I start applying it more blindly. I also use git and have enabled persistent-undo in vim so I can always go back.

Also thanks for this feature rich formatting tool! Afaik, there is no other one comparable to latexindent.

**Comment by cmhughes** [comment]
That seems like a very sensible approach, and is exactly what I do.

You'll see that there are 100s (if not 1000s) of test cases; for each one, I test the tool to make sure that it behaves as expected. I use git as you describe.

Thanks for your kind words, that lifts me a great deal.im glad you like the tool :)
