### ISSUE TITLE
Ignore lines in certain environments or between special comment markers

### ISSUE THREAD

**Issue by kiryph** [cmhughes/latexindent.pl#132]
### List of environments to be ignored
There are many ways to embed different type of source code into a texfile. A few examples are

- bib files put into `\begin{filecontents}{my.bib}/\end{filecontents`
- luatex
- pythontex (package pythontex)
- gnuplot (package gnuplottex)
- asymptote
- markdown
- ...

They are typically content of a specific environment. Obviously, a list of these specific environments should be customisable.

### Ignore lines between special marker
A second feature request is to add support for manual markers to ignore lines in the code.

Tools such as [astyle](http://astyle.sourceforge.net/astyle.html#_Disable_Formatting) and [uncrustify](https://github.com/uncrustify/uncrustify) support the lines `// *INDENT-OFF*` and `// *INDENT-ON*`. clang-format uses `// clang-format off/on` and yapf (python) `# yapf: disable/enable`.
I would prefer a less tool specific marker such as `// *INDENT-OFF*` even though indent-off means more than just disabling indentation but all formatting at all.

**Comment by cmhughes** [comment]
Have you seen the verbatim and filecontents options?

Have you seen the noindent fields?

**Comment by kiryph** [comment]
Sorry! RTFM to myself.

`verbatimEnvironments` looks exactly what I meant with my first part and
`noIndentBlock:  
    noindent: 1`

```tex
% \begin{noindent}
       this code
              won't
be touched
by
            latexindent.pl!
%\end{noindent}
```
for my second part.

I am really sorry for not looking properly!

---

### Add FAQ/Cheat Sheet/Newbie Section to Documentation

The documentation now is at almost 100 pages. This takes a while to read. And it is only a tool for formatting. There other things to learn as well. I know this is no excuse to fill the issue tracker.

Also the number of options in latexindent.pl is quite impressive:

```
❯ cat /usr/local/texlive/2018/texmf-dist/scripts/latexindent/defaultSettings.yaml | grep -v '^#' | grep -v '^$' | wc -l
     305
```
Getting to know them takes a while.

A FAQ section could contain those questions which should not have been raised similar to this one. This section could grow as you feel.

Also I think a cheatsheet or/and a condensed list of options could be helpful for newbies. The option names are already quite self-explanatory. The list could contain the name, a default if applicable, and a reference to the corresponding section in the documentation with a sensible order and category names. I hope that this list is shorter than the list of listings.
IMHO the list of listings is not really helpful as it stands.

If one gets really fancy some kind of [VisualTikz](https://ctan.org/pkg/visualtikz) analogue could be created as a second pdf: only yaml snippet plus pictures.

**Comment by cmhughes** [comment]
No worries :) feel free to submit a pull request containing proposals for
cheat sheet/short versions/visuals

**Comment by cmhughes** [comment]
There's also specialBeginEnd which can be specified as verbatim

**Comment by koppor** [comment]
Would it be possible to have the mentioned environments as default be configured as `verbatimEnvironments`? For my current use case `markdown` would be enough 😇 . Reason: The tool latexindent.pl is great. There should be "sensible" defaults. With that, I mean, defaults applicable for the majority of users should be in place. If someone really wants to have its markdown environment reformatted, they can use `verbatimEnvironments` and set `markdown` to `0`.

**Comment by cmhughes** [comment]
Pull requests to develop welcome for review!
