### ISSUE TITLE
Indent of forest is weird

### ISSUE THREAD

**Issue by EternalPhane** [cmhughes/latexindent.pl#133]
1. Indent of each level is twice as much as `defaultIndent`.

    input:
    ```latex
    \begin{forest}
    [level 1
    [level 2]
    [level 2
    [level 3]
    ]
    ]
    \end{forest}
    ```
    output (with `defaultIndent` set to `4`):
    ```latex
    \begin{forest}
        [level 1
                [level 2]
                [level 2
                        [level 3]
                ]
        ]
    \end{forest}
    ```
2. Sometimes when node contains math mode texts, the indent is corrupted.

    input:
    ```latex
    \begin{forest}
    [\(1\)
    [\(2\)
    [3]
    [3]
    ]
    [2
    [3]
    [3]
    ]
    ]
    \end{forest}
    ```
    output (with `defaultIndent` set to `4`):
    ```latex
    \begin{forest}
        [\(1\)
            [\(2\)
                    [3]
                        [3]
                ]
                [2
                        [3]
                        [3]
                ]
        ]
    \end{forest}
    ```

**Comment by cmhughes** [comment]
I think you might be wanting `noAdditionalIndent`, as in 

`eternal.yaml`
---
```
noAdditionalIndentGlobal:
    namedGroupingBracesBrackets: 1
    UnNamedGroupingBracesBrackets: 1
```
and then call
```
latexindent.pl -l=eternal.yaml myfile.tex
```
which gives
```
\begin{forest}
	[level 1
		[level 2]
		[level 2
			[level 3]
		]
	]
\end{forest}

\begin{forest}
	[\(1\)
		[\(2\)
			[3]
			[3]
		]
		[2
			[3]
			[3]
		]
	]
\end{forest}
```

**Comment by cmhughes** [comment]
PS: I know the documentation is quite long, but https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html#noadditionalindent-and-indentrules is the part for this.

**Comment by EternalPhane** [comment]
I've been aware of `noAdditionalIndent`, but didn't dived in. Thanks a lot.

**Comment by cmhughes** [comment]
No worries :) glad this fixed it, do always feel free to ask questions -- the manual is quite long, and I do understand that it's not necessarily obvious what does what :)
