### ISSUE TITLE
wrap ignores commands

### ISSUE THREAD

**Issue by dzklaim** [cmhughes/latexindent.pl#136]
it seems to me that wrapping does not consider the size of something inside a command.

For example, if I try to wrap the text 
<pre>
xxxxxxxx~\xxx{xxx:xxxxxxxxxxxx_xxxxxx_x}, \xxx{xxx:xxxxxxxxxxxx_xxxxxx_x}, xx xxxxxxxx
</pre>

using 72 columms, I receive the same output. However, the text

<pre>
xxxxxxxx~Xxxx{xxx:xxxxxxxxxxxx_xxxxxx_x}, Xxxx{xxx:xxxxxxxxxxxx_xxxxxx_x}, xx xxxxxxxx
</pre>

seems to be wrapped correctly.

**Comment by cmhughes** [comment]
In your first example there is no white space; the text wrapping only
breaks at white space.

**Comment by dzklaim** [comment]
sorry. I mean the result of this
<pre>
xxxxxxxx~\xxx{xxx:xxxxxxxxxxxx_xxxxxx_x}, \xxx{xxx:xxxxxxxxxxxx_xxxxxx_x}, xx xxxxxxxx
</pre>
should be
<pre>
xxxxxxx~\xxx{xxx:xxxxxxxxxxxx_xxxxxx_x},
\xxx{xxx:xxxxxxxxxxxx_xxxxxx_x}, xx xxxxxxxx
</pre>
This is what we get when we replace "\" by "X" in the second example

**Comment by cmhughes** [comment]
When I start with 

`tmp.tex`
---
```
xxxxxxxx~\xxx{xxx:xxxxxxxxxxxx_xxxxxx_x}, \xxx{xxx:xxxxxxxxxxxx_xxxxxx_x}, xx xxxxxxxx
```
and 

`cmh.yaml`
---
```
modifyLineBreaks:
    textWrapOptions:
        columns: 72
```
and run 
```
latexindent.pl -m tmp.tex -l=cmh.yaml
```
then I receive
```
xxxxxxxx~\xxx{xxx:xxxxxxxxxxxx_xxxxxx_x},
\xxx{xxx:xxxxxxxxxxxx_xxxxxx_x}, xx xxxxxxxx
```
Is this as expected?

**Comment by dzklaim** [comment]
yes. that is exactly what I wanted :) I need to check if I had something else active that somehow conflicted

**Comment by cmhughes** [comment]
Ok, let me know if you have a replicable situation.
