### ISSUE TITLE
verbatim starts at its own line and finishes with line break?

### ISSUE THREAD

**Issue by dzklaim** [cmhughes/latexindent.pl#139]
is this possible?

I would like to tell latexindent to not touch my math environments. I use complex equations and expressions, it is virtually impossible to make them look right automatically. So, I prefer to do it by hand. The problem is that if I treat \\[ and \\] as verbatim then I can not use the SpecialBeginStartsOwnLine etc. 

thank you for your work!

**Comment by cmhughes** [comment]
This sounds reasonable, happy to look at this, it should be possible.

**Comment by dzklaim** [comment]
thank you!

**Comment by cmhughes** [comment]
For my reference, this will need addressing for 

- verbatim environments
- verbatim commands
- verbatim special

**Comment by cmhughes** [comment]
As of https://github.com/cmhughes/latexindent.pl/commit/9d077455145fd373f377d44f524ecd93d96a9bbe, this is implemented. There are two new poly-switches:

```
    verbatim:
        VerbatimBeginStartsOnOwnLine: 0
        VerbatimEndFinishesWithLineBreak: 0
```

This will be part of the next release, hopefully in the next few weeks. In the mean time, you can grab the `develop` version if you'd like to experiment :)

**Comment by dzklaim** [comment]
thank you very much! unfortunately I will not be able to test it until next week :S fingers crossed :D

**Comment by miohna** [comment]
I am not sure whether the issue, I have noticed, is linked to this new feature or should have worked before already:

```bash
$> cat test.yaml 
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1     
    environments:
        BeginStartsOnOwnLine: 1
        EndFinishesWithLineBreak: 1
    verbatim:
        VerbatimBeginStartsOnOwnLine: 1
        VerbatimEndFinishesWithLineBreak: 1
```
```bash
$> cat environments-verbatim-simple.tex 
A nested test
\begin{lstlisting}
    here is some verbatim
         something else
\end{lstlisting}
after verbatim.
```

With these inputs `./latexindent.pl -l test.yaml -m -w environments-verbatim-simple.tex` results in
```latex
A nested test \begin{lstlisting}
    here is some verbatim
         something else
\end{lstlisting} after verbatim.
```
but I expected an unchanged output. The full stop at the end does make the difference. Without, it works like I expect.

Is this actually a bug or do I misunderstand the feature here?

**Comment by cmhughes** [comment]
Thanks, that's an interesting test case.

Verbatim blocks and their poly switches are found as the first order of business.

The one sentence per line routine comes afterwards, and in your case undoes the line break.

As such, I'd say that the behaviour is expected.

**Comment by miohna** [comment]
Thanks for explaining the technical background. I see the point.

Do you thinks my requested behaviour could become a feature at some point in the future?

Do you see a workaround for now or is setting the switch to 3 and getting the extra line the only possible option?

**Comment by cmhughes** [comment]
No worries :)

I'm not sure... Verbatim code blocks are stored right at the beginning, and then kept away from the main processing. This is deliberate so that they are not changed by latexindent.

I'm not sure if it'll possible to have the two things work together. As you'll see, there are a lot of other things to tackle on latexindent :)

**Comment by miohna** [comment]
Okay, I see :-) I will find some workaround that does the job for me.

PS: Many thanks for this very useful tool.
