### ISSUE TITLE
Latexindent fails if an initialization file "indentconfig.yaml" is present in the home-dir

### ISSUE THREAD

**Issue by lucbouge** [cmhughes/latexindent.pl#141]
Dear Chris,

Thank you for your excellent software. 

I use version 3.5.1, 2018-09-15, with Perl 5.28.0 on a Mac with MacOS 10.13.6 (High Sierra).  Everything has been installed using the HomeBrew package manager. 

I have been trying to use an initialization file `$HOME/indentconfig.yaml` as specified in the documentation at URL https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html.

However, launching `latexindent` fails as soon as such a file is present, whatever its contents. In contrast, it works fine if no such file is present. 
```
$ cd
$ touch indentconfig.yaml
$ touch test.tex

$ /usr/local/texlive/2018/bin/x86_64-darwin/latexindent test.tex 
Can't use an undefined value as an ARRAY reference at /usr/local/texlive/2018/texmf-dist/scripts/latexindent/LatexIndent/GetYamlSettings.pm line 105.
```

**Comment by cmhughes** [comment]
Many thanks for this. Yes, this is definitely a bug, which I've fixed as of https://github.com/cmhughes/latexindent.pl/commit/94deaa3541635e1ea9e5ad5998cf22f97f26ca18. I'm going to release a minor version with this immediately, V3.5.3. Thanks again.

**Comment by cmhughes** [comment]
Thanks again, resolved as of https://github.com/cmhughes/latexindent.pl/pull/142
