### ISSUE TITLE
Disable backup entirely?

### ISSUE THREAD

**Issue by alok** [cmhughes/latexindent.pl#145]
I really don't want to save any backups, and would like to leave that task up to version control as I find the backup file to be unnecessary clutter. Is there a way to do this?

**Comment by cmhughes** [comment]
You can use the following
```
latexindent myfile -o myfile
```
But I don't recommend it!

**Comment by alok** [comment]
What if it's being read from STDIN and being written to STDOUT (my use case since I have it integrated with an editor)?

**Comment by cmhughes** [comment]
Back up files are only made when the -w flag is active.

**Comment by alok** [comment]
If I create a new directory `dir` with a single file `a.tex` in it, and then do this:

```
cd dir
latexindent < a.tex
```

It creates `indent.log` anyway, even though `-w` was not passed to it.

**Comment by cmhughes** [comment]
The log file is not a backup file, it's a log file :)

You can redirect it to a different directory using the -c switch. Alternatively, you can hide it using, for example
```
latexindent -g=.indent.log
```

**Comment by alok** [comment]
Alright, I'll redirect to `/dev/null`.

**Comment by alok** [comment]
Turns out redirecting to /dev/null gives the error `Can't open /dev/null at /usr/local/texlive/2021/texmf-dist/scripts/latexindent/LatexIndent/Document.pm line 165, <> line 309.`

**Comment by cmhughes** [comment]
Can you confirm the version you're using? Did this behaviour change because of an update?

**Comment by cmhughes** [comment]
OK, so how about I remove the 'die'  statement for log file creation?

**Comment by alok** [comment]
using version 3.9.1 (bundled with mactex 2021).

which die statement is that exactly?

**Comment by cmhughes** [comment]
https://github.com/cmhughes/latexindent.pl/blob/e198fa56012ce4341cfe7a2aa3d6ad5c38e3489b/LatexIndent/Document.pm#L165

Should be able to remove the die statement without issue.... Some experimentation needed, but should be ok

**Comment by cmhughes** [comment]
If you change line 165 of the above file to
```
open($logfile,">","${$self}{cruftDirectory}/$logfileName");
```
does that help....?

**Comment by cmhughes** [comment]
logfile die process removed as of https://github.com/cmhughes/latexindent.pl/commit/da2b15eb64ee0e14eff3e8f606930bce4cedbdd8. this will be part of the next release.

**Comment by cmhughes** [comment]
Related, for reference: https://github.com/cmhughes/latexindent.pl/issues/333 and https://github.com/cmhughes/latexindent.pl/pull/354

**Comment by Ashvith10** [comment]
@cmhughes is it possible to disable backup, while still allowing for overwrite of files sequentially? The `-o` switch in the docs isn't that clear to me:
```console
$ latexindent.pl myfile*.tex -o=++
```

**Comment by cmhughes** [comment]
The o switch doesn't create back up files
