### ISSUE TITLE
Why does `-l` require the config to be in the same directory?

### ISSUE THREAD

**Issue by alok** [cmhughes/latexindent.pl#147]
Quoting [this](https://latexindentpl.readthedocs.io/en/latest/sec-how-to-use.html?highlight=-l):

```
The -l flag can take an optional parameter which details the name (or names separated by commas) of a YAML file(s) that resides in the same directory as myfile.tex; you can use this option if you would like to load a settings file in the current working directory that is not called localSettings.yaml.
```

Why can't it just take an absolute path to a file in *any* directory and use that?

**Comment by cmhughes** [comment]
It can. Please see section 4.4

https://latexindentpl.readthedocs.io/en/latest/sec-indent-config-and-settings.html#localsettings-yaml

**Comment by cmhughes** [comment]
See also section 3

 *In fact, you can specify both relative and absolute paths for your YAML files; *
