### ISSUE TITLE
configuration for backup target dir

### ISSUE THREAD

**Issue by tpd-opitz** [cmhughes/latexindent.pl#150]
I'd like to have the opportunity to configure an `output directory` for the backup files. 
This would help to keep the working directory clean as well as to exclude backups from the SCM (e.g. by adding the backup target folder to `.gitignore`).

Also I could easily get rid of obsolete backups by simply deleting anything from the backup target folder.

The path to the backup output folder might either be a *relative path* to the `pwd` or an *absolute path* pointing anywhere in the file system.
A *relative path* should **not** be interpreted relative to the location of the file being processed, avoiding the need to create that subfolder in every level of a structured project setup.

**Comment by cmhughes** [comment]
Hello! Have you seen the -c switch?

**Comment by cmhughes** [comment]
https://latexindentpl.readthedocs.io/en/latest/sec-how-to-use.html#from-the-command-line

**Comment by tpd-opitz** [comment]
No, I really overlooked that. Thanks.

**Comment by cmhughes** [comment]
No worries :) the manual is quite long.
