### ISSUE TITLE
Arara 4.0 and latexindent with subdirectories

### ISSUE THREAD

**Issue by chgithub2019** [cmhughes/latexindent.pl#157]
Hi,

I was recently asked whether automatically indenting is possible in LaTeX and stumbled upon latexindent. In the last couple of days, I made it work for my texlive 2017 (arara version 3.0A and latexindent 3.3) and it works great. So far, so good :)

For some other reasons, I installed texlive 2018 and tried to get it to work there as well (arara 4.0 and latexindent 3.5.3). Again, everything was fine. The only issue I am having is indenting files in subdirectories. I use the following directive at the beginning of my tex file:

`% arara: indent: { overwrite : yes, files : [main.tex, 03_foldername/filename.tex], settings: local, where: 00_Arara_and_Latexindent/localSettings.yaml }`

The log file simply states that it cannot find filename.tex.

If I put the file in the same file as my main file (and remove the 03_foldername/), everything runs smoothly.

Is there any way to keep my folder structure and run latexindent in my subdirectories?

As far as I could see, there seems to be no solution for this on the internet, although I have the impression that subdirectories are deprecated in arara 4.0.

I am running everything on Windows 10.

Yours, 
Christian

**Comment by cmhughes** [comment]
Thanks for this! It might be better suited on the arara repository....?

**Comment by chgithub2019** [comment]
Hi, thanks for your response! It was actually a fifty-fifty decision where I raise this issue. 

If you tell me that this behavior is caused by arara, I will issue this in the arara project again and link their response here.

**Comment by chgithub2019** [comment]
Sure, also thanks for your help again!

Christian
