### ISSUE TITLE
Segmentation fault on Mojave 10.14.2

### ISSUE THREAD

**Issue by lioumens** [cmhughes/latexindent.pl#159]
After installing latexindent, the proper Perl dependencies and setting up the include files as suggested [here](https://tex.stackexchange.com/a/461689/181945). I get a segmentation fault when testing latexindent on a simple tex file. Even running `latexindent -v` will give me a segmentation fault. I've tried both the most recent Github release and the TexLive installation.

```bash
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.2
BuildVersion:	18C54
$ perl latexindent.pl -v
[1]    31099 segmentation fault  perl latexindent.pl -v
```

**Comment by cmhughes** [comment]
Thanks for this.

Could you try the following minimum Perl script and post the output:

```
 #!/usr/bin/perl

 use strict;
 use warnings;
 use utf8;
 use PerlIO::encoding;
 use Unicode::GCString;
 use open ':std', ':encoding(UTF-8)';
 use Text::Wrap;
 use Text::Tabs;
 use FindBin;
 use YAML::Tiny;
 use File::Copy;
 use File::Basename;
 use File::HomeDir;
 use Getopt::Long;
 use Data::Dumper;
 use List::Util qw(max);
 use Log::Log4perl qw(get_logger :levels);

 print "hello world";
 exit;
```

**Comment by lioumens** [comment]
I also get a segmentation fault. However, If I comment out two lines, I get the expected output `hello world%`.

```perl
# use Unicode::GCString
# use File::HomeDir
```

I did try reinstalling the `Unicode::GCString` and `File::HomeDir`, and it seems there are some permission issues, so I ran it again with escalated privilege, however the problem still persists. If I uncomment those two lines I will still get a segmentation fault.

I put some of the output in a gist [here](https://gist.github.com/lioumens/bbc0e54b8e6c45bbb17c66d06f3324e4).

The Perl version I'm using was installed through Homebrew.

```
$ perl -v
This is perl 5, version 28, subversion 1 (v5.28.1) built for darwin-thread-multi-2level

Copyright 1987-2018, Larry Wall
```

**Comment by cmhughes** [comment]
Thanks for this.

Starting with the code I posted above, can you strip it right down until
you get something that reproduces the error?

**Comment by lioumens** [comment]
With both files below, my computer will produce the error running `perl test.pl`.

```perl
#!/usr/local/bin/perl

use File::HomeDir;
```

```perl
#!/usr/local/bin/perl

use Unicode::GCString;
```

```bash
➜  ~ perl test.pl
[1]    1099 segmentation fault  perl test.pl
```

**Comment by cmhughes** [comment]
Is perlbrew available for the Mac? If so, could you try installing it?

I'll try to help, but it seems that this problem isn't actually with latexindent as demonstrated by your minimal script above.

**Comment by lioumens** [comment]
Installing the modules through Perlbrew seemed to do the trick. No more segmentation fault, and the program works as expected. Thank you for your work and help!

**Comment by cmhughes** [comment]
Great, glad it worked out!

**Comment by arielsei** [comment]
> Installing the modules through Perlbrew seemed to do the trick. No more segmentation fault, and the program works as expected. Thank you for your work and help!

how did you install the modules through perlbrew? If you can help, I would really appreciate it

**Comment by cmhughes** [comment]
Hello!
Have you seen:

https://latexindentpl.readthedocs.io/en/latest/appendices.html#manually-installed-modules

Let me know :)

**Comment by arielsei** [comment]
yes, I was trying to install it in Mac OS Catalina, but when I run it, it returns segmentation fault. I just installed Perlbrew and try to install perl 5.22 and it work

**Comment by xiangchen2011** [comment]
I met the same problem. And I used the above suggestion which is installing perl of 5.22.0 by [perlbrew](https://perlbrew.pl/) It works. BTW, my os version is 10.12. Before this, the default Perl has been updated to 5.30.0 which does not work at all.

**Comment by iliailmer** [comment]
Hey, I'm having the same issue, but the above does not seem to work. I encountered the problem via Latex-Workshop in vscode. Perl version:
```
This is perl 5, version 32, subversion 0 (v5.32.0) built for darwin-thread-multi-2level

Copyright 1987-2020, Larry Wall
```

The installation of `Unicode::GCString;` says the package is installed but segmentation fault still occurs upon running `use Unicode::GCString;`.
