### ISSUE TITLE
Nested align

### ISSUE THREAD

**Issue by rommeswi** [cmhughes/latexindent.pl#162]
Suppose I want to align ampersands in:

```
\begin{align}
A & =\begin{array}{cc}
BBB & CCC\\
E & F
\end{array}\\
Z & =\begin{array}{cc}
Y & X\\
W & V
\end{array}
\end{align}
```

Then currently latexindent will output

```
\begin{align}
	A   & =\begin{array}{cc} 
	BBB & CCC                \\
	E   & F                  
	\end{array}\\
	Z   & =\begin{array}{cc} 
	Y   & X                  \\
	W   & V                  
	\end{array}
\end{align}
```

Two issues I do not quite understand how to fix using the config:
1) How to ensure that each array is treated separately (the & symbols are aligned across the two arrays, there is extra whitespace in front of Y and W.
2) How to remove the extra whitespace in front of \\ inside the array.

Expected output is:
```
\begin{align}
	A & =\begin{array}{cc} 
	BBB & CCC \\
	E   & F                  
	\end{array} \\
	Z & =\begin{array}{cc} 
	Y & X \\
	W & V                  
	\end{array}
\end{align}
```

(What would of course be even more amazing is latexindent realizing that all the lines of the arrays are "to the right" of the first ampersand):
```
\begin{align}
	A & =\begin{array}{cc} 
	    BBB & CCC \\
	    E   & F                  
	    \end{array} \\
	Z & =\begin{array}{cc} 
	    Y & X \\
	    W & V                  
	    \end{array}
\end{align}
```

Many thanks for your efforts on latexindent!

**Comment by cmhughes** [comment]
Hello!
Thanks for this. For the spacing, take a look at https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html?highlight=ampersand#lst-aligndelims-advanced 

The first of your outputs is as expected. Nested alignment is a tricky thing. I'd hope to look at it at some point, but I think it would be a big under taking. Sorry about that. I'll label this as `expected behaviour`.

Best
Chris

**Comment by cmhughes** [comment]
See also https://github.com/cmhughes/latexindent.pl/issues/212

**Comment by cmhughes** [comment]
I'm closing this, and referencing it within https://github.com/cmhughes/latexindent.pl/issues/85. It's all part of the same problem, and I don't need it in multiple places.

**Comment by cmhughes** [comment]
Update! see https://github.com/cmhughes/latexindent.pl/issues/85 :) release to follow soon :)

**Comment by cmhughes** [comment]
Released as of https://github.com/cmhughes/latexindent.pl/releases/tag/V3.10.1, uploaded to ctan, you should be able to get it using your TeX distribution manager within about 24 hours, ctan allowing.
