### ISSUE TITLE
.indentconfig.yaml file not working

### ISSUE THREAD

**Issue by cristobaltapia** [cmhughes/latexindent.pl#165]
Hi, thanks for this nice software. I have been using it in Linux without problems until I wanted to edit some options with a custom `.indentconfig.yaml` file.
The content of it is:

```
# Default value of indentation
defaultIndent: "  "
```
So, very minimal. I just want to replace tabs with spaces. However, when I run latexindent I get the following warning in the log file:

```
...
WARN: The paths field cannot be read from /home/tapia/.indentconfig.yaml; this means it is either empty or contains invalid YAML
      See https://latexindentpl.readthedocs.io/en/latest/sec-indent-config-and-settings.html for an example
...
```

I don't know much about yaml files, but I think I don't have anything illegal in the file.

I am using the version 3.5.3.

**Comment by cmhughes** [comment]
Hello!
Thanks for this :)

Indentconfig.yaml contains *paths* to other yaml files that contain your
settings.

Does this make sense?

**Comment by cmhughes** [comment]
See https://latexindentpl.readthedocs.io/en/latest/sec-indent-config-and-settings.html#indentconfig-yaml-and-indentconfig-yaml

**Comment by cristobaltapia** [comment]
Hi @cmhughes , thanks for your reply. So I was interpreting it wrong. Thanks for the clarification. Still a bit confusing: why would you need separate configuration files, if they are all loaded anyways?
