### ISSUE TITLE
Improved installation advice for linux/OSX

### ISSUE THREAD

**Issue by mkerin** [cmhughes/latexindent.pl#166]
Hi,

It took me a small amount of head scratching to install latexindent, and I just thought I'd comment with some thoughts.

Your helper script at (https://github.com/cmhughes/latexindent.pl/blob/develop/helper-scripts/latexindent-module-installer.pl) is very useful, but it took me some time to find it. I think it would be sustantially easier to just list something akin to the following in the [quickstart](https://latexindentpl.readthedocs.io/en/latest/sec-introduction.html#quick-start) section (maybe under a linux/OSX header) 

```
brew install perl
brew install cpanm

cpanm YAML::Tiny
cpanm File::HomeDir
cpanm Unicode::GCString
cpanm Log::Log4perl
cpanm Log::Dispatch
```

Great package btw - thanks for making it available!

**Comment by cmhughes** [comment]
Hello!
Thanks very much for this, I'm glad that you like `latexindent.pl` :)

Documentation and installation of perl modules is certainly something that needs constant attention, and I'm always very happy when people bring it up, thanks for raising the issue!

Perhaps the snippets that you posted could be added to the Appendix: https://latexindentpl.readthedocs.io/en/latest/appendices.html#manually-installed-modules 

I'm not very familiar with the MacOS operating system; is the `brew` command something that is available to all MacOS, or is it something special? 

How does that sound? Let me know what you think!

**Comment by mkerin** [comment]
I'd say that (a) `brew` is a fairly mainstream package manager for OSX, and (b) if anyone uses an alternative package manager then it should be fairly easy to adapt the install commands.

Ha! - I see now that you do actually link to that part of the appenix as "You might also like to see ... as well as Section 9.1.". I totally missed this. I agree that it fits with the content in there.

**Comment by cmhughes** [comment]
Great, many thanks. As of https://github.com/cmhughes/latexindent.pl/commit/59ba59785e609e02ffc849a3ba85e23003a0c220 this is implemented in `develop`, let me know if it needs editing :)

**Comment by cmhughes** [comment]
Implemented as of https://github.com/cmhughes/latexindent.pl/pull/169 upload to ctan soon.
