### ISSUE TITLE
other delimiters in one sentence per line

### ISSUE THREAD

**Issue by Konfekt** [cmhughes/latexindent.pl#167]
Given the sample text
```
  The filter does different things depending on the file format; in most cases
  it is determined on the output of the "file" command [2], [6], that recognizes
  lots of formats. Only in a few cases the file suffix is used to determine what
  to display. Up to date file descriptions are included in the "file" package.
  Maintaining a list of file formats is therefore only a matter of keeping that
  package up to date.
```
the command
```sh
latexindent -modifylinebreaks --yaml='modifyLineBreaks:oneSentencePerLine:manipulateSentences:1;sentencesEndWith:other: "\;"'
```
yields
```
The filter does different things depending on the file format; in most cases it is determined on the output of the "file" command [2], [6], that recognizes lots of formats.
Only in a few cases the file suffix is used to determine what to display.
Up to date file descriptions are included in the "file" package.
Maintaining a list of file formats is therefore only a matter of keeping that package up to date.
```
and the command
```
latexindent -modifylinebreaks --yaml='modifyLineBreaks:oneSentencePerLine:manipulateSentences:1;sentencesEndWith:other: "\,|\;|\:"'
```
yields
```
  The filter does different things depending on the file format;
  in most cases
  it is determined on the output of the "file" command [2], [6], that recognizes
  lots of formats.
  Only in a few cases the file suffix is used to determine what to display.
  Up to date file descriptions are included in the "file" package.
  Maintaining a list of file formats is therefore only a matter of keeping that package up to date.
```
It is only with this value of `EndWith:other` that the sentence is split up after the `;`. 
Why also after `cases` and `recognizes` is not clear to me.

Looking at Listing 252 and 253 from the documentation from 2019-05-05, it is also not clear to me why `sentencesBeginWith:a-z:1` was not needed to split the sentence up after `:` as in Listings 254 and 255 for `,`. 

These issues came up while extending my Vim plug-in https://github.com/Konfekt/vim-sentence-chopper to leverage https://github.com/cmhughes/latexindent.pl .

**Comment by cmhughes** [comment]
Hello!
Many thanks for this, great question!

This is quite subtle :) At the moment, the part that begins with *in most cases* is **not** considered as a sentence, which is why `removeSentenceLineBreaks` has not been applied to it.

You need to tell `latexindent.pl` that sentences can also *begin* with lowercase letters. 

So, if you use the YAML

`localSettings.yaml`
-
```
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1     
        removeSentenceLineBreaks: 1
        sentencesEndWith:
          other: '\,|\;|\:'
        sentencesBeginWith:
          other: [a-z]
```
with your original text saved into `myfile.tex` and run
```
latexindent.pl -m -l myfile.tex
```
then you receive
```
The filter does different things depending on the file format;
in most cases it is determined on the output of the "file" command [2],
[6], that recognizes
lots of formats.
Only in a few cases the file suffix is used to determine what to display.
Up to date file descriptions are included in the "file" package.
Maintaining a list of file formats is therefore only a matter of keeping that package up to date.
```
Hopefully this is as you would like :)

**Comment by Konfekt** [comment]
Thank you! I would like that sentences are split up after the punctuation marks `.?!` and `;`. Is that possible?

Also, I thought ` removeSentenceLineBreaks: 1` is set by default?
The other outputs indicate so.

**Comment by Konfekt** [comment]
Another question is why all other settings of `other` did not split up sentences after `;`.

**Comment by cmhughes** [comment]
Yes, `removeSentenceLineBreaks: 1` is default. 

I didn't understand your follow-up; can you provide your input, YAML, and desired output, and hopefully I can help :)

**Comment by Konfekt** [comment]
What made me wonder is the following. Given 

- the default settings of `latexindent` and
-  the sample text
```
  The filter does different things depending on the file format; in most cases
  it is determined on the output of the "file" command [2], [6], that recognizes
  lots of formats. Only in a few cases the file suffix is used to determine what
  to display. Up to date file descriptions are included in the "file" package.
  Maintaining a list of file formats is therefore only a matter of keeping that
  package up to date.
```

the command
```sh
latexindent -modifylinebreaks --yaml='modifyLineBreaks:oneSentencePerLine:manipulateSentences:1;sentencesEndWith:other: "\;"'
```
yields
```
The filter does different things depending on the file format; in most cases it is determined on the output of the "file" command [2], [6], that recognizes lots of formats.
Only in a few cases the file suffix is used to determine what to display.
Up to date file descriptions are included in the "file" package.
Maintaining a list of file formats is therefore only a matter of keeping that package up to date.
```

- Why is there no line break after `;` with`other:"\;" ?
- Why is there no line break after `;` with`other:"\;:\:" ?
- Why is there no line break after `;` with `"\;|\:|\," ?
- Why is there a line break after `;` with `"\,|\;|\:" ? (To me the outcome should not change.)
- Why is there a line break after `;` with `"\,|\;|\:" even though`sentencesBeginWith:other: [a-z]` was not set (since we use the default value)?

An additional question concering your reply:

In the documentation from 2019-05-05 there is an option `sentencesBeginWith:other: [a-z]: 0`. Are both this option and the option `sentencesBeginWith:other: [a-z]` you gave valid?

**Comment by Konfekt** [comment]
If you wish, I can post the command and output (the input stays the same) for each of  the different settings of `other: ` listed above, but for readability refrained from doing so.

**Comment by Konfekt** [comment]
As an aside, if `sentencesBeginWith:other: [a-z]` is an alternative to `sentencesBeginWith:other:[a-z]: 1`, then, assuming these are interpreted as regular expressions, `sentencesBeginWith:other: [[:lower:]]` would have advantage of allowing for accented lowercase Unicode characters as well.

**Comment by cmhughes** [comment]
Thanks for the details, I'll do my best to answer.

> Why is there no line break after ; withother: "\;" ?

This is because you have put quotes around the `\;` If you use the following, noting that there are no quotes around the `\;`
```
latexindent -modifylinebreaks --yaml='modifyLineBreaks:oneSentencePerLine:manipulateSentences:1;sentencesEndWith:other: \;'
```
then you receive
```
The filter does different things depending on the file format;
in most cases
it is determined on the output of the "file" command [2], [6], that recognizes
lots of formats.
Only in a few cases the file suffix is used to determine what to display.
Up to date file descriptions are included in the "file" package.
Maintaining a list of file formats is therefore only a matter of keeping that package up to date.
```
The output in the above is received when you use `\;|\:` and `\;|\:|\,` and `\,|\;|\:`. Hopefully this addresses your first four bullet points.

For your fifth bullet point:

> Why is there a line break after ; with other: "\,|\;|\:" even thoughsentencesBeginWith:other: [a-z] was not set (since we use the default value)?

My apologies, my initial post was incorrect, and it is not necessary to specify `sentencesBeginWith` as I had originally thought (I haven't looked at this routine for a while). This is because of the syntax passed to the `-y` switch. 

> In the documentation from 2019-05-05 there is an option sentencesBeginWith:[a-z]: 1. Are both, this option and the option sentencesBeginWith:other: [a-z] you gave, valid?

Nearly! The first one that you gave should be  `sentencesBeginWith:a-z: 1` and the second one should be fine.

Thanks for your comment on `[[:lower:]] `, that's helpful. 

It's very clear that you've studied the documentation, so thank you very much for engaging with it so much! :)  I hope this helps, do let me know if not.

**Comment by Konfekt** [comment]
Thank you!

> The output in the above is received when you use \;|\: and \;|\:|\, and \,|\;|\:. Hopefully this addresses your first four bullet points.

I can confirm that this output is as intended. What is not clear to me is: 

- Why must the enclosing quotation marks `"..."` be removed to work?
- Why did it work for `"\,|\;|\:"` despite the enclosing quotation marks `"..."`?

However, when adding one of the settings`sentencesBeginWith:a-z: 1` or `sentencesBeginWith:other: [a-z]` or `sentencesBeginWith:other: [[:lower:]]` (to remove the line breaks between `;` and `.`),  then there is again no linebreak after `;`, despite using `\;|\:` instead of `"\;|\:"`. 

- How come?

Thanks for your comment about having thoroughly read the manual! As you see, these behaviors (for example, dependence on enclosing quotation marks) remain inexplicable to me. 

- Perhaps these could be documented as well?

**Comment by cmhughes** [comment]
Thanks for the follow-up.

> Why must the enclosing quotation marks "..." be removed to work?

YAML parsing for `settings.yaml` files can work with quotes and remove them (or not) as detailed in https://stackoverflow.com/questions/19109912/do-i-need-quotes-for-strings-in-yaml. 

The thing about the `-y` switch is that the settings aren't actually parsed by a YAML processor -- they are fed directly into the internal settings without any parsing. I haven't used the `-y` switch for any regular expressions as yet, so hadn't come up against this issue -- thank you for highlighting it!

> Why did it work for "\,|\;|\:" despite the enclosing quotation marks "..."?

This is quite subtle: the `"\,` is read as one pattern, and then the `|` is read as 'or' (as expected) and then the `\;` is read in, and is matched as desired. When using the quotes, the pattern `"\;"` is looked for, but the quotes aren't there! You can verify this by changing your input text to include `...the file format";` and then run
```
latexindent -modifylinebreaks --yaml='modifyLineBreaks:oneSentencePerLine:manipulateSentences:1;sentencesEndWith:other: "\;'
```
and you should see that the `";` is treated as the end of a sentence.

> However, when adding one of the settingssentencesBeginWith:a-z: 1 or sentencesBeginWith:other: [a-z] or sentencesBeginWith:other: [[:lower:]] (to remove the line breaks between ; and .) BEFORE the setting sentencesEndWith:other: \;|\:, then there is again no linebreak after ;, despite using \;|\: instead of "\;|\:".

When I run the command
```
latexindent.pl -m  --yaml='modifyLineBreaks:oneSentencePerLine:manipulateSentences:1;sentencesBeginWith:a-z:1;sentencesEndWith:other: \;'
```
then I receive the following output:
```
The filter does different things depending on the file format;
in most cases it is determined on the output of the "file" command [2], [6], that recognizes lots of formats.
Only in a few cases the file suffix is used to determine what to display.
Up to date file descriptions are included in the "file" package.
Maintaining a list of file formats is therefore only a matter of keeping that package up to date.
```
which I think is as desired...?

You might like to explore the `-tt` switch for debugging -- it means that a lot of information is output to `indent.log` and it might give a better sense of what's going on.

> Perhaps these could be documented as well?

Yes, I think you've highlighted something that should be written into the documentation, thank you! :)

**Comment by cmhughes** [comment]
See https://github.com/cmhughes/latexindent.pl/commit/7bb0dc99379ef689cbe440e2628393614db31297 for update to documentation.

**Comment by Konfekt** [comment]
Your options
```
latexindent -modifylinebreaks --yaml='modifyLineBreaks:oneSentencePerLine:manipulateSentences: 1,modifyLineBreaks:oneSentencePerLine:sentencesBeginWith:a-z: 1;sentencesEndWith:other: \;'
```
yield
```
The filter does different things depending on the file format; in most cases it is determined on the output of the "file" command [2], [6], that recognizes lots of formats.
Only in a few cases the file suffix is used to determine what to display.
Up to date file descriptions are included in the "file" package.
Maintaining a list of file formats is therefore only a matter of keeping that package up to date.
```
It seems that `;` is not interpreted as belong to `modifyLineBreaks:oneSentencePerLine:sentencesBeginWith:`.

Then again the options
```
--yaml='modifyLineBreaks:oneSentencePerLine:manipulateSentences: 1,modifyLineBreaks:oneSentencePerLine:sentencesBeginWith:other:a-z: 1,modifyLineBreaks:oneSentencePerLine:sentencesEndWith:other: \;'
```
yield
```
The filter does different things depending on the file format;
in most cases
it is determined on the output of the "file" command [2], [6], that recognizes
lots of formats.
Only in a few cases the file suffix is used to determine what to display.
Up to date file descriptions are included in the "file" package.
Maintaining a list of file formats is therefore only a matter of keeping that package up to date.
```

**Comment by Konfekt** [comment]
Also, `sentencesBeginWith:other: [[:lower:]]` does not work (yet?).

**Comment by Konfekt** [comment]
So thank you, other than the intricate quoting and the feature request to admit non-Latin lower case characters in `sentencesBeginWith`, everything works as expected.

**Comment by Konfekt** [comment]
This said, it seems that `sentencesBeginWith:a-z: 1` is too coarse a measure to remove the line breaks between `;` and `.`, but that would be a  can of worms to be opened in a separate issue.

**Comment by cmhughes** [comment]
Thanks for this :)

Could give me a test case for testing [[:lower]] ?

**Comment by Konfekt** [comment]
The text
```
The filter does different things depending on the file format; in most cases it is determined on the output of the "file" command [2], [6], that recognizes lots of formats.
```
with `sentencesBeginWith:other: [a-z]` becomes
```
The filter does different things depending on the file format;
in most cases it is determined on the output of the "file" command [2], [6], that recognizes lots of formats.
```
and with `[[:lower:]]
```
  The filter does different things depending on the file format;
  in most cases
  it is determined on the output of the "file" command [2], [6], that recognizes
  lots of formats.
```
If the question is about where one has a need for `[[:lower:]]`, then in French `à` is quite common, so applying `latexindent` with `sentencesBeginWith:other: [a-z]`
```
C'est bon; à six heures on y va.
```
would not insert a line break after `;`.

**Comment by cmhughes** [comment]
Great, many thanks. I'll take a look and report back to you.

**Comment by cmhughes** [comment]
I've done some work on this.

Starting with 

`myfile.tex`
-
```
The filter does different things depending on the file format;
  in most cases
  it is determined on the output of the "file" command [2], [6], that recognizes
  lots of formats.

C'est bon; à six 
heures on y va.
````

Test 1
=
Using the following yaml
```
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1     
        sentencesEndWith:
          other: '\;'
        sentencesBeginWith:
          other: [a-z]
```
gives the output:
```
The filter does different things depending on the file format;
in most cases it is determined on the output of the "file" command [2], [6], that recognizes lots of formats.

C'est bon;
à six
heures on y va.
```

Test 2
-
Using the following yaml
```
modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1     
        sentencesEndWith:
          other: '\;'
        sentencesBeginWith:
          other: [[:lower:]]
```
gives
```
The filter does different things depending on the file format;
in most cases it is determined on the output of the "file" command [2], [6], that recognizes lots of formats.

C'est bon;
à six heures on y va.
```

Test 3
-
Using the following, the `-y` switch:
```
latexindent.pl -m  myfile.tex -y="modifyLineBreaks:oneSentencePerLine:manipulateSentences:1;sentencesEndWith:other:\;;sentencesBeginWith:other:[[:lower:]]"
```
gives
```
The filter does different things depending on the file format;
in most cases
it is determined on the output of the "file" command [2], [6], that recognizes
lots of formats.

C'est bon;
à six
heures on y va.
```

Summary so far
=
Test 1 and Test 2 are as expected. **Test 3** does *not* produce the expected output.

Solution
=
This highlighted another problem with the parsing of the `-y` switch, in that it was splitting at the `:` universally. 

As of https://github.com/cmhughes/latexindent.pl/commit/6b8e0019d68672db05252e0b8dc97186644c6c0b this is resolved, and running
```
latexindent.pl -m  myfile.tex -y="modifyLineBreaks:oneSentencePerLine:manipulateSentences:1;sentencesEndWith:other:\;;sentencesBeginWith:other:[[:lower:]]"
```
gives the output as in Test 2, which is as expected.

For the future
=
I need to test these kind of things with both an actual YAML file, and also with the `-y` switch. Is there a way to parse the input from `-y` switch using actual YAML, rather than my pseudo parsing...?

**Comment by cmhughes** [comment]
If you'd like to pull from the `develop` branch, you can test this, if you' d like :) Thanks for reporting this!

**Comment by Konfekt** [comment]
Thanks, good work! Now I understand why `:lower:` didn't work and am glad my Vim plug-in helped rounding off`YAML` command-line parsing. 

> Is there a way to parse the input from -y switch using actual YAML, rather than my pseudo parsing...?

This is, you ask if there is common standard to pass YAML on the command-line and perhaps even a Perl library that handles it? I have no answers, though. Perhaps others do.

**Comment by cmhughes** [comment]
Many thanks, glad this works now.

I was asking the question mainly to myself :) I'll keep considering the
more general problem.

I'll consider this resolved, but I wouldn't be surprised to hear of similar
things in the future.

**Comment by cmhughes** [comment]
Implemented as of https://github.com/cmhughes/latexindent.pl/pull/169 upload to ctan soon.
