### ISSUE TITLE
single setting for other punctuation marks

### ISSUE THREAD

**Issue by Konfekt** [cmhughes/latexindent.pl#168]
How about, instead of three settings
```
modifyLineBreaks:
  oneSentencePerLine:
    sentencesEndWith:questionMark: 1
    sentencesEndWith:exclamationMark: 1
    sentencesEndWith:other: ""
```
a single setting with default value
```
modifyLineBreaks:
  oneSentencePerLine:
    sentencesEndWith:other: "\!|\?"
```
?

**Comment by cmhughes** [comment]
You're free and encouraged to make your own settings, but the default will remain as they are for this :)

**Comment by Konfekt** [comment]
This was a suggestion about deprecating the options
```
modifyLineBreaks:
  oneSentencePerLine:
    sentencesEndWith:questionMark: 1
    sentencesEndWith:exclamationMark: 1
```
and instead use as a default
```
modifyLineBreaks:
  oneSentencePerLine:
    sentencesEndWith:other: "\!|\?"
```
to reduce the number of YAML parameters.

The defaults can remain the same. If `sentencesEndWith:other:` is set to a non-default value that does not contain the punctuation marks `\!|\?` after deprecation, then a warning should be issued that these are included by default.
