### ISSUE TITLE
long option crashes when using text wrap options

### ISSUE THREAD

**Issue by ahippler** [cmhughes/latexindent.pl#170]
formatting :
```latex
\documentclass[ngerman,a4paper,fontsize=11pt,cdfont=false,cdfont=false,BCOR=0mm,parskip]{tudscrartcl}
```

with:
```yaml
modifyLineBreaks:
  textWrapOptions:
    columns: 80
```

results in:
```
[14:03:48] Formatting failed with exit code 255
[14:03:48] stderr: This shouldn't happen at /System/Library/Perl/5.18/Text/Wrap.pm line 84.
```

`latexindent --version    =   3.6, 2019-05-05`

```latex
\documentclass[ngerman,a4paper,fontsize=11pt, cdfont=false,cdfont=false,BCOR=0mm,parskip]{tudscrartcl}
```
is working. I think the problem are the options wich are not wrapped without a space.

**Comment by cmhughes** [comment]
Hello!

Thanks for this.

When I start with
`tmp.tex`
-
```
\documentclass[ngerman,a4paper,fontsize=11pt,cdfont=false,cdfont=false,BCOR=0mm,parskip]{tudscrartcl}
```
and 
`ahippler.yaml`
```
modifyLineBreaks:
  textWrapOptions:
    columns: 80
```
and I run
```
latexindent.pl -m tmp.tex -l=ahippler
```
then I receive
```
\documentclass[ngerman,a4paper,fontsize=11pt,cdfont=false,cdfont=false,BCOR=0mm
	,parskip]{tudscrartcl}
```

I'm working on `perlbrew` with `perl` version 5.26. I don't receive the errors that you report. 

Can you clarify?

**Comment by cmhughes** [comment]
I haven't heard back from you, perhaps the issue is resolved? 

In summary, I recommend updating your perl version to a more recent release.

If this doesn't resolve the issue, please do feel free to post back.

Best
Chris
