### ISSUE TITLE
Magic.c: loadable library and perl binaries are mismatched

### ISSUE THREAD

**Issue by douglasrizzo** [cmhughes/latexindent.pl#171]
Hello again. I am trying to use `latexindent` and got the following error:

    Magic.c: loadable library and perl binaries are mismatched (got handshake key 0xce00080, needed 0xcd00080)

I imagine this error is related to Perl, but since I have 0 experience with the language, I hope I could get some assistance. I tried upgrading Perl and CPAN with the `upgrade`  and `install CPAN` commands on the cpan console. I am now on CPAN version 2.27.

I also upgraded TeX Live with `tlmgr --all update`, but even after all the upgrading, the problem persists.

I tried finding out if this Magic.c library is something installed in my computer (Manjaro Linux) which I need to update or install a specific version, but I couldn't find any info on Magic.c.

**Comment by cmhughes** [comment]
Thanks very much for this, it sounds like an interesting issue. It sounds
like it might be related to your perl installation.

I'm not familiar with your distribution of Linux. On Ubuntu I use perlbrew,
I'm not sure if that would be helpful?

**Comment by douglasrizzo** [comment]
Manjaro is based on Arch. My Perl installation comes from their official repositories. I'll try to reinstall it. Whar version of Perl is preferred, 5 or 6?

**Comment by cmhughes** [comment]
It's built and designed to be run with version 5. I haven't done anything
with version 6.

**Comment by cmhughes** [comment]
Any update on this?

**Comment by douglasrizzo** [comment]
I reinstalled Perl 5 and solved some upgrading issues, but the problem remains. In any case, if you believe this issue is not related to the development of latexindent but happens due to my own installation, I agree on closing the issue.

**Comment by cmhughes** [comment]
What happens when you compile the minimum working example:

https://latexindentpl.readthedocs.io/en/latest/appendices.html#lst-helloworld

**Comment by douglasrizzo** [comment]
```
$ perl helloworld.pl

Can't load '/home/user/.perl5/lib/perl5/x86_64-linux-thread-multi/auto/Unicode/LineBreak/LineBreak.so' for module Unicode::LineBreak: /home/user/.perl5/lib/perl5/x86_64-linux-thread-multi/auto/Unicode/LineBreak/LineBreak.so: undefined symbol: Perl_utf8n_to_uvchr_msgs at /usr/share/perl5/core_perl/XSLoader.pm line 93.
 at /home/user/.perl5/lib/perl5/x86_64-linux-thread-multi/Unicode/LineBreak.pm line 63.
Compilation failed in require at /home/user/.perl5/lib/perl5/x86_64-linux-thread-multi/Unicode/GCString.pm line 24.
BEGIN failed--compilation aborted at /home/user/.perl5/lib/perl5/x86_64-linux-thread-multi/Unicode/GCString.pm line 24.
Compilation failed in require at helloworld.pl line 7.
BEGIN failed--compilation aborted at helloworld.pl line 7.

Apparently, it has something to do with Unicode::LineBreak or a core library called XSLoader. I tried upgrading Unicode::LineBreak, but it is already in its most recent version.

**Comment by douglasrizzo** [comment]
OK, apparently my distro has installed Perl 5.30, which released on May 22, 2019. I think I may have multiple Perl installations and some confusion is happening when loading libraries. I'll have to check how to fix this.

**Comment by douglasrizzo** [comment]
Sorry for triple posting (I don't know if this is a thing on GitHub). I've decided to manually delete `/home/user/.perl5/` and reinstall the packages needed for the MWE and `lateindent.pl`. Everything is working fine now.
As a side note,  it seems like `latexindent.pl` depends on Log::Dispatch::File, which is not a dependency of the MWE.

**Comment by cmhughes** [comment]
Really glad you got this fixed. No problems at all about the postings.

**Comment by searleser97** [comment]
I had the exact same problem, except my solution was to remove `PERL5LIB` and `PERL_LOCAL_LIB_ROOT` environment variables from my `.bashrc` file. Hope it helps someone
