### ISSUE TITLE
Additional spaces within long words with textwrap

### ISSUE THREAD

**Issue by waschk** [cmhughes/latexindent.pl#172]
I get additional spaces within a word if it is longer than the number of characters set in `modifyLineBreaks.textWrapOptions.columns`.

Input Tex File:
```
\documentclass{article}

\begin{document}
	Hello World
\end{document}
```

localsettings.yaml:
```
noAdditionalIndent:
  document: 0
modifyLineBreaks:
  textWrapOptions:
    columns: 3
    perCodeBlockBasis: 1
    environments: 1
```

Output Tex file:
```
\documentclass{article}

\begin{document}
	He
	ll
	o
	Wo
	rl
	d
\end{document}
```

This changed the resulting document from saying `Hello World` to `He ll o Wo rl d`.
What I would have expected as output is either ignoring the columns setting for that word or this:
```
\documentclass{article}

\begin{document}
	He%
	ll%
	o
	Wo%
	rl%
	d
\end{document}
```
It still enforces the specified columns value without changing the resulting document.

**Comment by cmhughes** [comment]
Hello!
Perhaps the separator field might be helpful....? 
 https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#lst-textwrap2-yaml

**Comment by waschk** [comment]
Not quite, with the separator `"%\n"` it would also put a % behind the o, resulting in `HelloWorld`.

As far as I can see there is no way to use a different separator when the wrap is within a word as opposed to between space separated words. Such an option would be very helpful.

**Comment by cmhughes** [comment]
Ok, many thanks.

Test wrapping is controlled by https://perldoc.perl.org/Text/Wrap.html.

From that page, it says:

When words that are longer than $columnsare encountered, they are broken
up. wrap()adds a "\n" at column $columns . This behavior can be overridden
by setting $hugeto 'die' or to 'overflow'. When set to 'die', large words
will cause die() <https://perldoc.perl.org/functions/die.html> to be
called. When set to 'overflow', large words will be left intact

I need to look into this, as it could be a new field to specify in the YAML.

**Comment by waschk** [comment]
So if I see that correctly it is currently not possible to specify a different separator for huge words? I'd be fine with setting $huge to overflow to put these long words on its own line.

May not look as neat, but as long as the resulting document stays the same, I am happy.

Thank you for all your support and this awesome tool in general.

**Comment by cmhughes** [comment]
Many thanks. You're correct, it's not currently possible, but I'm hopeful that I can experiment and add a new field. I'll update this thread as and when :)

**Comment by cmhughes** [comment]
As of https://github.com/cmhughes/latexindent.pl/commit/618371aa29db7490973745aa00478b45b4c56261 I've implemented a new option for `textwrap`. Starting with your original `.tex` and using the following

```
noAdditionalIndent:
  document: 0
modifyLineBreaks:
  textWrapOptions:
    columns: 3
    huge: overflow
    perCodeBlockBasis: 1
    environments: 1
```
then the output is
```
\documentclass{article}

\begin{document}
	Hello
	World
\end{document}
```

Is this as you would like? If you'd like to experiment, then you can either clone the `develop` branch, or otherwise just overwrite your copy of `ModifyLineBreaks.pm`. If you're not sure where that is on your system, take a look at `indent.log`.

Let me know!

**Comment by waschk** [comment]
Thanks a lot, works perfectly.

**Comment by cmhughes** [comment]
Great! this needs to stay open until the next release :)

**Comment by cmhughes** [comment]
This is implemented as of https://github.com/cmhughes/latexindent.pl/pull/173 

Thanks very much for raising this, it has been very helpful. I'll be uploading to ctan imminently.
