### ISSUE TITLE
Expand documentation clarifying the use of -c switch that moves cruft files to another directory

### ISSUE THREAD

**Issue by ashirwad** [cmhughes/latexindent.pl#180]
Hello, 

Thanks for this excellent tool! I have started using `latexindent` recently and found it to be really useful in beautifying latex documents.

I am creating this issue to bring to your attention the peculiar behavior of the `-c` switch that's supposed to move latexindent-generated files to a specified directory. When I use `-c=build`, latexindent does the following:
- moves only the backup files, and
- renames the `indent.log` file to `buildindent.log` and keeps it in the main directory. 

However, `-c=build/` (notice the trailing slash) gives the desired behavior. In your [SO answer](https://tex.stackexchange.com/a/144264/180993) you have not included the trailing slash (the cause of the unexpected behavior), however, in your [documentation](https://latexindentpl.readthedocs.io/en/latest/sec-how-to-use.html) you have used a trailing slash when defining the path for the cruft directory. So, you may want to add some clarifying remarks in your documentation emphasizing the use of a trailing slash.

Thanks!

**Comment by cmhughes** [comment]
Many thanks for this, I'll take a look and get back to you. It might be a
week or so because of work.

Thanks again!
Chris

**Comment by ashirwad** [comment]
No problem, take your time. :)

**Comment by cmhughes** [comment]
Thanks again for this, as of https://github.com/cmhughes/latexindent.pl/commit/b84e9dca376f09cb77a4e00234a3bde074d18f28 this is resolved. It'll be part of the next release, thanks again.
