### ISSUE TITLE
latexindent is not indenting text, and the log output doesn't indicate why this might be

### ISSUE THREAD

**Issue by zachsa** [cmhughes/latexindent.pl#181]
I installed latexindent to C:\latexindent, and running the C:\latexindent\latexindent.exe program seems to work, but the output is exactly the same as the input. From the logs, I can't see what's wrong:

```
INFO: latexindent.exe version 3.7.1, 2019-09-07, a script to indent .tex files
      latexindent.exe lives here: C:/latexindent/
      Tue Dec 10 08:38:18 2019
      Filename: <filename>.tex
INFO: Processing switches:
      -w|--overwrite: Overwrite mode active, will make a back up of <filename>.tex first
INFO: Directory for backup files and indent.log: .
INFO: YAML settings read: defaultSettings.yaml
      Reading defaultSettings.yaml from C:/latexindent/defaultSettings.yaml
INFO: YAML settings read: indentconfig.yaml or .indentconfig.yaml
      Reading path information from C:\Users\<username>/.indentconfig.yaml
      (Alternatively C:\Users\<username>/indentconfig.yaml can be used)
      ---
      paths:
        - C:\Users\<username>\.indentsettings.yaml
      
INFO: YAML settings, reading from the following files:
      Reading USER settings from C:\Users\<username>\.indentsettings.yaml
      ---
      commandCodeBlocks:
        stringsAllowedBetweenArguments:
          -
            amalgamate: '0'
      modifyLineBreaks:
        commands:
          subfloat:
            CommandStartsOnOwnLine: '1'
        environments:
          BeginStartsOnOwnLine: '1'
          EndStartsOnOwnLine: '1'
      
INFO: Backup procedure (-w flag active):
      copying <filename>.tex to ./<filename>.bak0
      Backup file: ./<filename>.bak0
      <filename>.tex will be overwritten after indentation
INFO: Phase 1: searching for objects
INFO: Phase 2: finding surrounding indentation
INFO: Phase 3: indenting objects
INFO: Phase 4: final indentation check
INFO: Output routine:
      Overwriting file <filename>.tex
      --------------
INFO: Please direct all communication/issues to:
      https://github.com/cmhughes/latexindent.pl

```

I have previously used this package, and if I remember correctly, the default settings were fine for me. In this case I added an indentconfig.yaml just as a means of testing. But still it's not working..

I am running latexindent via the following command:

```
latexindent -w <filename>.tex
```

This is on a Windows 10 machine, where I have installed TexLive - TexLive came with a latexindent.exe file that I deleted.

**Comment by cmhughes** [comment]
Hello,
Thanks for this.

Could you post your input file, the output, and what your expected output
is?


Chris

**Comment by zachsa** [comment]
Hi,

Thank you for your response!

I was expecting this:

```
            \definecolor{mycolor}{rgb}{0.122, 0.435, 0.698}
\newtcbox{\mybox}{
nobeforeafter,
height=10pt,
colframe=mycolor,
...
}
```

To be reformatted as this:

```
\definecolor{mycolor}{rgb}{0.122, 0.435, 0.698}
\newtcbox{\mybox}{
    nobeforeafter,
    height=10pt,
    colframe=mycolor,
    ...
}
```

It's been a long time since I setup latexindent, but I seem to remember spacing was automatically fixed.

But before posting this.. I tested on a block:

```
\begin{threeparttable}
\begin{tabularx}{\textwidth}{>{\hsize=0.2\hsize}Z|>{\hsize=1.8\hsize}X}
\textsc{\small{txt 1}} & txt 2                \\
& \footnotesize{txt 3}
\end{tabularx}
\end{threeparttable}
```

And that did become

```
\begin{threeparttable}
	\begin{tabularx}{\textwidth}{>{\hsize=0.2\hsize}Z|>{\hsize=1.8\hsize}X}
		\textsc{\small{txt 1}} & txt 2                \\
		                       & \footnotesize{txt 3}
	\end{tabularx}
\end{threeparttable}
```

I'm sorry to have flagged this incorrectly! However, I would be grateful to know where I could find an example of a settings.yaml file that handled spacing as well as indenting.

**Comment by cmhughes** [comment]
Could you be more specific about the spacing that you'd like?

**Comment by zachsa** [comment]
I was expecting stricter rules in terms of whitespacing - specifically: removing all unnecessary whitespace:

```
            \definecolor{mycolor}{rgb}{0.122, 0.435, 0.698}

\newtcbox{\mybox}{
nobeforeafter,
height=10pt,
colframe=mycolor,
...
}
```

I was expecting the spacing before `\definecolor` to be removed. I'm not sure on how to refer to the different parts of the latex language - with the `\newtcbox` command. I was expecting the "arguments" (if that is what they are) to be indented to a single tab equivalent.

Is this easy to configure? Really the reason that I use this latexindent is so that the `\begin - \end` blocks (if blocks is the correct word) nests correctly - this makes working in latex much easier I find

**Comment by cmhughes** [comment]
When I start with:
```
		\definecolor{mycolor}{rgb}{0.122, 0.435, 0.698}

\newtcbox{\mybox}{
nobeforeafter,
height=10pt,
colframe=mycolor,
...
}
```

and run `latexindent.exe -w myfile.tex` then I receive:
```
\definecolor{mycolor}{rgb}{0.122, 0.435, 0.698}

\newtcbox{\mybox}{
	nobeforeafter,
	height=10pt,
	colframe=mycolor,
	...
}
```

If this is not what you receive, please can you post complete details?

**Comment by zachsa** [comment]
That is not what I receive. My setup is this:

```
(1) First I installed TexLive
(2) Then I installed BeautifyLatex with Sublime
(3) Then I read somewhere that the latexindent.exe included with TexLive should be replaced. I did this
(4) Then I removed the latexindent.exe included with TexLive, and installed the package to C:\latexindent. This involved installing the perl modules
(5) Then I tried

   => latexindent.pl -w ..\Users\<username>\code\mydir\myfile.tex
   => latexindent.exe -w ..\Users\<username>\code\mydir\myfile.tex

Both of these format a begin block, but don't adjust all the spacing I would expect (which is why I posted). 

I have also tried commenting out my .indentsettings.yaml file - so I think the default settings is being read
```

The log output is what I included at the top of this message... Please let me know if there is anything else I should be saying!

**Comment by cmhughes** [comment]
Is your example complete, or is it part of something else? For example, is it within the preamble of another file?

**Comment by zachsa** [comment]
I've invited you to the repository, and have mentioned where the problem is in the readme file. please let me know if this will work.

This tex project used to work fine with latexindent, but now does not. I'm on the latest version of windows.

**Comment by cmhughes** [comment]
It looks like the piece of code you're describing is in the preamble.

Have you set indentPreamble to 1 in your settings?

**Comment by zachsa** [comment]
I started my computer up, and found that the latexindent install is now working as it should, although I don't know why it didn't work before. I did restart my computer after I installed latexindent. And for some reason BeautifyLatex is now broken.

Anyway, thank you very much for your help. Please let me know if there is anything in the ways of logs/config/etc. that I can provide further. Otherwise let me know if I can close this thread.

**Comment by cmhughes** [comment]
Cool, glad it all works now :) feel free to come back of ever you have any questions!

**Comment by 17tmh** [comment]
This rather old issue seems familiar:

I'd like to use the script for writing a thesis.

My setup seems fine.
I have changed nothing in `defaultSettings.yaml`. 
I can reproduce the first example
```
A quick start 
    demonstration for latexindent.pl.
    \begin{myenv}
      The body of environments and 
      other code blocks
        receive indentation.
    \end{myenv}
```
from the [docs](https://latexindentpl.readthedocs.io/en/latest/sec-introduction.html#quick-start)

But whenever I want to format one of my documents (which I can build fine, so no syntax error here), I get no changes at all...

**Comment by 17tmh** [comment]
Let me elaborate. I deleted most of the part of my document and still get this behavior:

If `doc.tex` is

```tex
\documentclass[
10pt,
a4paper,
listof=totoc,
]{scrartcl}

\usepackage[
inner=2.5cm,
outer=2.5cm,
%showframe				
]{geometry}
```

I get `result.tex`

```tex
\documentclass[
	10pt,
	a4paper,
	listof=totoc,
]{scrartcl}

\usepackage[
	inner=2.5cm,
	outer=2.5cm,
	%showframe				
]{geometry}
```
So this is working.

But if `doc.tex` is

```tex
\documentclass[
10pt,
a4paper,
listof=totoc,
]{scrartcl}

\usepackage[
inner=2.5cm,
outer=2.5cm,
%showframe				
]{geometry}

\begin{document}
\end{document}
```

the `result.tex` isn't changed at all:

```tex
\documentclass[
10pt,
a4paper,
listof=totoc,
]{scrartcl}

\usepackage[
inner=2.5cm,
outer=2.5cm,
%showframe				
]{geometry}

\begin{document}
\end{document}
```

What's going on here? Am I missing something?

**Comment by cmhughes** [comment]
Perhaps you want indentPreamble:1 as in

https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html#filecontents-and-preamble

**Comment by 17tmh** [comment]
Tanks, this helped a lot.
Quick follow up: Do I also have to make changes to `defaultSettings.yaml` if I want linewrapping?
Because this still doesn't work.

**Comment by cmhughes** [comment]
https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#text-wrap-simple-examples
