### ISSUE TITLE
Option for not aligning & in the lookforAlignDelim

### ISSUE THREAD

**Issue by swaroopguggilam** [cmhughes/latexindent.pl#186]
Firstly, thanks for this file, its really helpful.
Following is my problem:
```
\begin{alignat}{2}
    & asdfasdfadsaaaaaaaaaaadsaaaaaaaaaaaaaaaaaaaaaaasdfffffffffffffffffffff & & temp       \\
    &                                                                                     & & tempasdfasdf                                    \\
\end{alignat}
```
After I format it using latexindent.pl, all the & align, but I don't want that, because as one of my word is very long, its affecting the visibility of all the rows in my latex file.
Current Output:
```
\begin{alignat}{2}
    & asdfasdfadsaaaaaaaaaaadsaaaaaaaaaaaaaaaaaaaaaaasdfffffffffffffffffffff & & temp \\
    &                                                                        & & tempasdfasdf \\
\end{alignat}
```
Required Output:
```
\begin{alignat}{2}
    & asdfasdfadsaaaaaaaaaaadsaaaaaaaaaaaaaaaaaaaaaaasdfffffffffffffffffffff & & temp \\
    & & & tempasdfasdf \\
\end{alignat}
```
Is there an option to do this? (I want something similar to \\ (alignDoubleBackSlash: 0))
Thanks.

**Comment by cmhughes** [comment]
Hello, 
Thanks for this. Have you seen https://github.com/cmhughes/latexindent.pl/issues/182 

They seem very similar to me, let me know if they're different!

**Comment by swaroopguggilam** [comment]
Thank you for quick response.
They are kind of similar, but would still highlight following differences:
1) That one particularly focus on ignoring table headings, mine is in general ampersand signs
2) Mine above is under equations (alignat) and not tables, but I believe same command can be used for different type of blocks across latex like your other features.
Basically "Dont align at & routine or a variable to set this false" would be very helpful.
Thank you.

**Comment by cmhughes** [comment]
Ok, great. Please post to that issue, and close this one, it will be the
same feature.

**Comment by swaroopguggilam** [comment]
Done. Posted in that issue. Closing this.

**Comment by cmhughes** [comment]
Great, many thanks
