### ISSUE TITLE
Change the amount of indentation after \item

### ISSUE THREAD

**Issue by abrahammurciano** [cmhughes/latexindent.pl#192]
It seems that currently settings such as these from [here](https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html#lst-indentafteritems)

```yaml
indentAfterItems:
    itemize: 1
    enumerate: 1
    description: 1
    list: 1
```
produces this indentation
```tex
\begin{itemize}
	\item some text here
	      some more text here
	      some more text here
	\item another item
	      some more text here
\end{itemize}
```
with precisely 6 spaces after each `\item`. I understand that this is meant so that new lines are aligned with the first, but it does not make sense if there is no text on the first line as I do in my own syle, e.g.
```tex
\begin{itemize}
	\item
	      some more text here % no need for 6 spaces, a tab would do fine
	      some more text here
	\item
	      some more text here
\end{itemize}
```
This also causes misalignment (all subsequent indentations are 2 spaces off the tabulation) with any indentation within the item, such as my example below. There should be a setting at least to make the indentation the same as the default indentation, e.g. a tab instead of 6 spaces.
![image](https://user-images.githubusercontent.com/25041135/78463285-3954de00-76db-11ea-9759-a1243868f838.png)

**Comment by cmhughes** [comment]
Hello,
Thanks for this. Have you seen indentRules, in particular

https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html#lst-item-rules1

**Comment by abrahammurciano** [comment]
Hmm... I'd been looking for that. Couldn't find it earlier, thanks. I'll try that out and let you know if that's what I needed

**Comment by abrahammurciano** [comment]
Awesome, thats exactly what I needed, thanks.

**Comment by cmhughes** [comment]
Great! Glad to hear it :) happy indenting!
