### ISSUE TITLE
Spaces before/after braces

### ISSUE THREAD

**Issue by PaulPichaureau** [cmhughes/latexindent.pl#193]
If there is some spaces around braces, `latexindent` fails to identify environment. For example

> Let \begin{equation* }
> H(x)  = \int_1^x g \frac{1}{  t} \dt  = \int_1^x t \e^{ -t} \dt = \pac{ -t\e^{-t } }_1^x + \int_1^x  \e^{-t} \dt
> \end{equation*}

The `equation*` environment is not detected, probably because there is a space before the closing space.

Moreover, I would like to automatically remove all such space. The desired output, with the previous example, should be
> Let 
> \begin{equation* }
>   H(x)  = \int_1^x g \frac{1}{t} \dt  = \int_1^x t \e^{-t} \dt = \pac{-t\e^{-t}}_1^x + \int_1^x  \e^{-t} \dt
> \end{equation*}

So I suggest to 
1. correct the first behaviour (which seems a bug, IMHO)
2. add a feature to remove space after opening brace and before closing brace.

**Comment by PaulPichaureau** [comment]
Ok, sorry for the noise, I've closed this issue. At second thought, there is many cases where this could be a wrong idea.

**Comment by cmhughes** [comment]
Ok, no worries. 

You might like the fine-tune feature, https://latexindentpl.readthedocs.io/en/latest/sec-fine-tuning.html#fine-tuning
