### ISSUE TITLE
Issues with text wrap and remove paragraph line breaks

### ISSUE THREAD

**Issue by TheConfuZzledDude** [cmhughes/latexindent.pl#194]
Hi, with the config set to
```yaml
modifyLineBreaks:
    textWrapOptions:
        all: 1
        columns: 120
        perCodeBlockBasis: 1
    removeParagraphLineBreaks:
        all: 1
        beforeTextWrap: 1
noAdditionalIndentGlobal:
    mandatoryArguments: 1
    commands: 1
```
The text 
```tex
analysis, ``\textit{The Case for Writing a Kernel in Rust}'' by A. Levy et al., and ``\textit{Rust as a Language for High Performance GC Implementation}'' by Y. Lin, S. M. Blackburn, A. L. Hosking, and M. Norrish. Finally, I will be analysing two class presentations on C++ and Erlang, as C++ is perhaps the
```
is formatted to 
```tex
analysis, ``\textit{The Case for Writing a Kernel in Rust}'' by A. Levy et al., and ``\textit{Rust as a Language for High Performance GC Implementation}'' by Y. Lin, S. M. Blackburn, A. L.
Hosking, and M. Norrish. Finally, I will be analysing two class presentations on C++ and Erlang, as C++ is perhaps the
most similar language to Rust in terms of
```
with the one line stretching out far beyond the desired limit.
The desired output would be
```tex
programming language, which has become best known for its emphasis on memory safety and concurrency, focusing on how
these features affect its performance in its various intended use cases. Two papers have been chosen to facilitate this
analysis, ``\textit{The Case for Writing a Kernel in Rust}'' by A. Levy et al., and ``\textit{Rust as a Language for
High Performance GC Implementation}'' by Y. Lin, S. M. Blackburn, A. L. Hosking, and M. Norrish. Finally, I will be
analysing two class presentations on C++ and Erlang, as C++ is perhaps the most similar language to Rust in terms of
```
which I can achieve by disabling text wrap so that all paragraph line breaks are removed, and then enabling text wrap (not on a perCodeBlockBasis), and disabling paragraph line breaks. I've messed around a bit with the settings, but I haven't been able to achieve a solution, so any help would be appreciated

**Comment by cmhughes** [comment]
Thanks for this. I think the behaviour you report is expected, which I'll try to explain. Starting with the code you provided:

**mwe.tex**
```
analysis, ``\textit{The Case for Writing a Kernel in Rust}'' by A. Levy et al., and ``\textit{Rust as a Language for High Performance GC Implementation}'' by Y. Lin, S. M. Blackburn, A. L. Hosking, and M. Norrish. Finally, I will be analysing two class presentations on C++ and Erlang, as C++ is perhaps the
```
case 1: perCodeBlockBasis: 1
-
Using the following settings, which is as you provided (note that `removeParagraphLineBreaks` will not effect this code)
```
modifyLineBreaks:
    textWrapOptions:
        columns: 120
        perCodeBlockBasis: 1
        all: 1
```
gives the output
```
analysis, ``\textit{The Case for Writing a Kernel in Rust}'' by A. Levy et al., and ``\textit{Rust as a Language for High Performance GC Implementation}'' by Y. Lin, S. M. Blackburn, A. L.
Hosking, and M. Norrish. Finally, I will be analysing two class presentations on C++ and Erlang, as C++ is perhaps the
```
This is as expected, because activating the `perCodeBlockBasis: 1` means that the text wrap routine will be called *once the code blocks have been found* (https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#text-wrapping-on-a-per-code-block-basis).

case 2: perCodeBlockBasis: 0
-
Using the settings
```
modifyLineBreaks:
    textWrapOptions:
        columns: 120
noAdditionalIndentGlobal:
    mandatoryArguments: 1
    commands: 1
```
gives the output
```
analysis, ``\textit{The Case for Writing a Kernel in Rust}'' by A. Levy et al., and ``\textit{Rust as a Language for
High Performance GC Implementation}'' by Y. Lin, S. M. Blackburn, A. L. Hosking, and M. Norrish. Finally, I will be
analysing two class presentations on C++ and Erlang, as C++ is perhaps the
```
Note that (https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#textwrapoptions-modifying-line-breaks-by-text-wrapping) this has been operated upon *before* the code blocks have been found.

It seems that case 2 is closer to what you would like...?

**Comment by TheConfuZzledDude** [comment]
Yeah exactly, the problem is though, that with case 2, it will only get that result when the paragraph is entirely on a single line. If I were to then add content to a line afterwards, and then reformat, the overflowing part would be placed on a new line, which may only have a few words in it.

This makes the text wrap not very useful for documents that you are tweaking, which is why you usually use `removeParagraphLineBreaks` and `beforeTextWrap`, as it strips all the line breaks before the text wrap, meaning that any new content that's been added will be wrapped and "reflowed". But the issue there, is that this requires setting `perCodeBlockBasis` (as otherwise beforeTextWrap doesn't work), which works almost completely as I want, except that as commands and other code blocks in a paragraph are wrapped separately, it can push the rest of the paragraph past the text wrap boundary (as shown in the example).

Effectively, my desired result would be such that all line breaks are removed, and then the text is wrapped, ignoring code blocks. This would essentially take paragraphs, and completely "reflow" them, with any commands that are just used to provide markup (like `\texttt`) being wrapped in exactly the same place as the regular contents of the paragraph. The end result being that each line is wrapped after the desired amount of columns, with no parts sticking out. I can achieve this  by doing two passes of the formatter, the first removing the line breaks, and the second doing the text wrap (with `perCodeBlockBasis` turned off), but this is highly undesirable.

Ideally, the desired configuration would be to either have `beforeTextWrap` work without `perCodeBlockBasis` so that I can reflow an entire paragraph, or having some way to ignore some code blocks during the text wrap, so that commands and their arguments are wrapped with the other content.

I hope I made sense here, it's somewhat difficult for me to describe this stuff precisely as I feel I'm somewhat missing the correct terminology

**Comment by cmhughes** [comment]
Thanks for the follow-up, it's good to keep the discussion going. 

> Yeah exactly, the problem is though, that with case 2, it will only get that result when the paragraph is entirely on a single line. If I were to then add content to a line afterwards, and then reformat, the overflowing part would be placed on a new line, which may only have a few words in it.

Can you be specific about this, by providing a small, complete example that demonstrates the output that you get at the moment, together with what you would like it to be?

**Comment by TheConfuZzledDude** [comment]
Yeah, so following on from the previous example, if I have the paragraph
```tex
these features affect its performance in its various intended use cases. Two papers have been chosen to facilitate this
analysis, ``\textit{The Case for Writing a Kernel in Rust}'' by A.~Levy et al., and ``\textit{Rust as a Language for
High Performance GC Implementation}'' by Y.~Lin, S.~M.~Blackburn, A.~L.~Hosking, and M.~Norrish. Finally, I will be
```
If I go back and add extra text (`This is some added \emph{CONTENT}`) to that first line, such that it goes past the wrap boundary
```tex
these features affect its performance in its various intended use cases. Two papers have been chosen to facilitate this This is some added \emph{CONTENT}
analysis, ``\textit{The Case for Writing a Kernel in Rust}'' by A.~Levy et al., and ``\textit{Rust as a Language for
High Performance GC Implementation}'' by Y.~Lin, S.~M.~Blackburn, A.~L.~Hosking, and M.~Norrish. Finally, I will be
```
Upon formatting with just `columns: 120` and `perCodeBlockBasis: 0`, the result will be 
```
these features affect its performance in its various intended use cases. Two papers have been chosen to facilitate this
This is some added \emph{CONTENT}
analysis, ``\textit{The Case for Writing a Kernel in Rust}'' by A.~Levy et al., and ``\textit{Rust as a Language for
High Performance GC Implementation}'' by Y.~Lin, S.~M.~Blackburn, A.~L.~Hosking, and M.~Norrish. Finally, I will be
```
Note that the second line is very short and looks out of place.
The desired result can be achieved by first formatting with no text wrap options, and only `removeParagraphLineBreaks` to strip all the line breaks, and then formatting again, with the previous options, producing
```tex
these features affect its performance in its various intended use cases. Two papers have been chosen to facilitate this
This is some added \emph{CONTENT} analysis, ``\textit{The Case for Writing a Kernel in Rust}'' by A.~Levy et al., and
``\textit{Rust as a Language for High Performance GC Implementation}'' by Y.~Lin, S.~M.~Blackburn, A.~L.~Hosking, and
M.~Norrish. Finally, I will be
```
The best analogy I can give is that this would be the equivalent result to writing a paragraph in an editor like Microsoft Word, such that when you write enough text that it goes past the wrap threshold, it is placed at the beginning of the next line, displacing text that's already there, instead of just placing the overflowing text on a new line of its own

**Comment by cmhughes** [comment]
Thanks for this, that's helpful.

Starting with your file,
```
these features affect its performance in its various intended use cases. Two papers have been chosen to facilitate this This is some added \emph{CONTENT}
analysis, ``\textit{The Case for Writing a Kernel in Rust}'' by A.~Levy et al., and ``\textit{Rust as a Language for
High Performance GC Implementation}'' by Y.~Lin, S.~M.~Blackburn, A.~L.~Hosking, and M.~Norrish. Finally, I will be
```
and using the following settings
```
modifyLineBreaks:
    textWrapOptions:
        columns: 120
        perCodeBlockBasis: 1
        all: 1
    removeParagraphLineBreaks:
        all: 1
        beforeTextWrap: 1
```
then I receive the following output:
```
these features affect its performance in its various intended use cases. Two papers have been chosen to facilitate this
This is some added \emph{CONTENT} analysis, ``\textit{The Case for Writing a Kernel in Rust}'' by A.~Levy et al., and
``\textit{Rust as a Language for High Performance GC Implementation}'' by Y.~Lin, S.~M.~Blackburn, A.~L.~Hosking, and M.~Norrish. Finally, I will be
```

As I start to understand your issue more, I'm increasingly thinking that it is the same thing that is highlighted within https://github.com/cmhughes/latexindent.pl/issues/158. In that issue, I have said:

> I think this problem comes down to the fact that textWrap can operate before the code blocks have been found (6.1.1 of https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#textwrapoptions-modifying-line-breaks-by-text-wrapping) and that removeParagraphLineBreaks happens after the code blocks have been found.

Does this sound consistent with your view?

**Comment by TheConfuZzledDude** [comment]
Yeah I think that's pretty much correct. For now, I can make do without text wrapping and just rely on the soft wrapping feature of my editor (Vim), which works well enough but has quite a few issues, and just apply the text wrap as a final step

**Comment by cmhughes** [comment]
Ok, that's great, many thanks. In which case, I'm going to close this as a duplicate, but reference it from https://github.com/cmhughes/latexindent.pl/issues/158

**Comment by TheConfuZzledDude** [comment]
Ok, thanks!
