### ISSUE TITLE
Could not open defaultSettings.yaml

### ISSUE THREAD

**Issue by ravijo** [cmhughes/latexindent.pl#195]
I am using Atom Editor to format my latex code. I am getting the following error-

```
Could not open defaultSettings.yaml at /usr/local/texlive/2020/texmf-dist/scripts/latexindent/LatexIndent/GetYamlSettings.pm line 69.
Hide Stack Trace
Error: Could not open defaultSettings.yaml at /usr/local/texlive/2020/texmf-dist/scripts/latexindent/LatexIndent/GetYamlSettings.pm line 69.
    at /home/ravi/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:183:23
    at tryCatcher (/home/ravi/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ravi/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ravi/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ravi/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ravi/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/home/ravi/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/ravi/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/ravi/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:147:5)
    at Async.drainQueues (/home/ravi/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Below is the information about the environment-
```
ravi@home:~$ atom --version
Atom    : 1.45.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0

ravi@home:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="14.04.6 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.6 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

ravi@home:~$ latex --version
pdfTeX 3.14159265-2.6-1.40.21 (TeX Live 2020)
kpathsea version 6.3.2
Copyright 2020 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.02

ravi@home:~$ uname -r
4.4.0-148-generic
```

Invoking `latexindent.pl` directly from a terminal is also resulting similar error as shown below-
```
ravi@home:~$ /usr/local/texlive/2020/texmf-dist/scripts/latexindent/latexindent.pl 
Please enter text to be indented: (press CTRL+D when finished)
Could not open defaultSettings.yaml at /usr/local/texlive/2020/texmf-dist/scripts/latexindent/LatexIndent/GetYamlSettings.pm line 69.
```

Any workaround, please?

**Comment by cmhughes** [comment]
Thanks for this. I wonder if something changes in texlive 2020....? I
haven't installed it yet.

A quick work around is to grab a copy of defaultSettings.yaml from this
repository, and place it in the directory with latexindent.pl.

I'll leave this open, and see if I can recreate it. I'll report back when I
know more.

**Comment by ravijo** [comment]
@cmhughes 

> Thanks for this. I wonder if something changes in texlive 2020.

No. I was facing this problem with old texlive too. It is some other type of problem 

Thanks!

**Comment by cmhughes** [comment]
That's helpful.

Can you tell me your operating system?

Does defaultSettings.yaml exist anywhere on your system?

**Comment by cmhughes** [comment]
On my Ubuntu, 18.04 LTS, texlive 2019 installs `latexindent` to the following directory:
```
/usr/local/texlive/2019/texmf-dist/scripts/latexindent/
```
Can you provide the output from
```
ls -l /usr/local/texlive/2019/texmf-dist/scripts/latexindent/
```
Your perl version should be fine; I test on multiple different perl versions using travis CI (see https://travis-ci.org/cmhughes/latexindent.pl if you're interested).

Are you able to run the minimal perl file given in the appendix of the documentation: https://latexindentpl.readthedocs.io/en/latest/appendices.html#lst-helloworld

If you can let me know about all of these, hopefully that will help us take it forward.

**Comment by ravijo** [comment]
Hi @cmhughes 

Thank you very much.

> Can you provide the output from
> 
> ```
> ls -l /usr/local/texlive/2019/texmf-dist/scripts/latexindent/
> ```

Yes. Please see the output reported at terminal below-
```
ravi@Dell:~$ ls -l /usr/local/texlive/2020/texmf-dist/scripts/latexindent/
total 28
-rwxr-xr-x 1 root root 17660 Apr 14 21:49 defaultSettings.yaml
drwxr-xr-x 2 root root  4096 Apr 14 01:29 LatexIndent
-rwxr-xr-x 1 root root  2910 Mar 22 06:20 latexindent.pl
```

> Are you able to run the minimal perl file given in the appendix of the documentation: https://latexindentpl.readthedocs.io/en/latest/appendices.html#lst-helloworld

Yes. Please see the output reported at terminal below-
```
ravi@Dell:~/Desktop$ perl helloworld.pl 
hello worldravi@Dell:~/Desktop$ 
```

Just mentioning that I tried upgrading the perl version as suggested [here](https://askubuntu.com/a/257818/569883). It took a long time to upgrade though. I still see the same version as shown at the terminal below-
```
ravi@Dell:~/Desktop$ perl --version

This is perl 5, version 18, subversion 2 (v5.18.2) built for x86_64-linux-gnu-thread-multi
(with 55 registered patches, see perl -V for more detail)

Copyright 1987-2013, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

Additional Info.
-------------------
Since I am using latexindent for a decade, I have an older version too. I can invoke it from the terminal. Please see below-
```
ravi@Dell:~/latexindent$ ./latexindent.pl
latexindent.pl version 2.1R
usage: latexindent.pl [options] [file][.tex]
      -h  help (see the documentation for detailed instructions and examples)
      -o  output to another file; sample usage
                latexindent.pl -o myfile.tex outputfile.tex
      -w  overwrite the current file- a backup will be made, but still be careful
      -s  silent mode- no output will be given to the terminal
      -t  tracing mode- verbose information given to the log file
      -l  use localSettings.yaml (assuming it exists in the directory of your file)
      -d  ONLY use defaultSettings.yaml, ignore ALL user files
      -c=cruft directory used to specify the location of backup files and indent.log
```

Thank you very much.

**Comment by ravijo** [comment]
Hi @cmhughes

Thank you very much.

> Can you tell me your operating system? 

Yes. It is Ubuntu 14.04 LTS as reported [here](https://github.com/cmhughes/latexindent.pl/issues/195#issue-599336784).

> Does defaultSettings.yaml exist anywhere on your system?

Yes. There are many of them. See below, please-
```
ravi@Dell:~$ sudo updatedb
[sudo] password for ravi: 
ravi@Dell:~$ locate defaultSettings.yaml
/home/ravi/Desktop/latexindent.pl/defaultSettings.yaml
/home/ravi/latexindent/defaultSettings.yaml
/usr/local/texlive/2015/texmf-dist/scripts/latexindent/defaultSettings.yaml
/usr/local/texlive/2020/texmf-dist/scripts/latexindent/defaultSettings.yaml
```
Here is an explanation of each defaultSettings.yaml file-

1. `/home/ravi/Desktop/latexindent.pl/defaultSettings.yaml`: I cloned it from GitHub last night to see if the latest version is working. I reported it [here](https://github.com/cmhughes/latexindent.pl/issues/195#issuecomment-613404398).
2. `/home/ravi/latexindent/defaultSettings.yaml`: This is a very old version. It is working fine and I reported it [here](https://github.com/cmhughes/latexindent.pl/issues/195#issuecomment-613791759).
3. `/usr/local/texlive/2015/texmf-dist/scripts/latexindent/defaultSettings.yaml`: This is an old version of Texlive. The latexindent was not working in this texlive.
5. `/usr/local/texlive/2020/texmf-dist/scripts/latexindent/defaultSettings.yaml`: Since latexindent was not working with texlive 2015, I decided to upgrade texlive. Unfortunatly, still latexindent is not working.

Thank you again.

**Comment by ravijo** [comment]
Hi @cmhughes

It is working now. I am not sure what was the culprit though! I upgraded `cpan` as well.

Thank you very much.

**Comment by cmhughes** [comment]
That's great, I'm glad it's working. It's not clear to me what wasn't working, but all's well that ends well!

Do always feel free to post with questions and comments :)
