### ISSUE TITLE
conda-forge feedstock

### ISSUE THREAD

**Issue by tdegeus** [cmhughes/latexindent.pl#196]
I'm having trouble running `latexindent` shipped with MacTeX:

```none
Can't locate Log/Log4perl.pm in @INC (you may need to install the Log::Log4perl module) (@INC contains: /usr/local/texlive/2019/texmf-dist/scripts/latexindent /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.4 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /usr/local/texlive/2019/texmf-dist/scripts/latexindent/LatexIndent/LogFile.pm line 22.
BEGIN failed--compilation aborted at /usr/local/texlive/2019/texmf-dist/scripts/latexindent/LatexIndent/LogFile.pm line 22.
Compilation failed in require at /usr/local/texlive/2019/texmf-dist/scripts/latexindent/LatexIndent/Document.pm line 25.
BEGIN failed--compilation aborted at /usr/local/texlive/2019/texmf-dist/scripts/latexindent/LatexIndent/Document.pm line 25.
Compilation failed in require at /Library/TeX/texbin/latexindent line 27.
BEGIN failed--compilation aborted at /Library/TeX/texbin/latexindent line 27.
```

A quick look gives related issues: 

* https://github.com/cmhughes/latexindent.pl/issues/102
* https://github.com/cmhughes/latexindent.pl/issues/104
* https://github.com/cmhughes/latexindent.pl/issues/166

To deal with this issues more permanently it would be great if a feedstock could be created on conda-forge. This could deal with all the dependencies at once! I have experience with conda and creating feedstocks on conda-forge, but no experience with perl. So it'd be willing to make the effort, but I'd need some guidance.

**Comment by cmhughes** [comment]
Thanks very much for this. As you say, there has been quite a few
questions/issues on this. I'm grateful that you've highlighted this and I'd
be happy to help in any way I can.

This message is just a place holder, I'll plan to post again over the
weekend with follow-up questions/comments. Thanks again.

**Comment by tdegeus** [comment]
Sounds good. All in all I don't think it should be super difficult, the only thing that I need some guidance on are the dependencies. If I look at the CI here it seems that you use a repository manager for perl, that we would have to see how to best piggyback on. The most important questions thereby are:
* Does the user need all of them, or are some just for the CI?
* Are the dependencies you use just scripts (evaluated only at runtime) or are things actually compiled (sorry if this is a naive question, again, I have zero Perl experience).

**Comment by cmhughes** [comment]
Thanks again for this. 

To your first question: yes, the user does need all of the modules.

I'm afraid that I don't know the answer to your second question; I don't think that it's a naive question!

Perhaps the following resources might be helpful:

- https://latexindentpl.readthedocs.io/en/latest/appendices.html#required-perl-modules, particularly
```
brew install perl
 brew install cpanm

 cpanm YAML::Tiny
 cpanm File::HomeDir
 cpanm Unicode::GCString
 cpanm Log::Log4perl
 cpanm Log::Dispatch
```
- https://tex.stackexchange.com/questions/390433/how-can-i-install-latexindent-on-macos
- https://tex.stackexchange.com/questions/445521/latexindent-cant-locate-log-log4perl-pm-in-inc-you-may-need-to-install-the-l

I hope this helps to progress, but do let me know if you have any other questions or comments.

**Comment by tdegeus** [comment]
Thanks. I started with the dependencies, however after a while of keeping finding ever more dependencies of dependencies I got demotivated : https://github.com/conda-forge/staged-recipes/pull/11325 . Aren't there a few encompassing libraries?

**Comment by cmhughes** [comment]
Can I check where you are with this issue? What do you need from me?

**Comment by tdegeus** [comment]
It would be great if you can get you insight how to efficiently get the dependencies (and in particular the dependencies' dependencies, and their dependencies, etc.) @cmhughes . I started adding the dependencies that are listed above, but that opened pandora's box, see https://github.com/conda-forge/staged-recipes/pull/11325 . I quote one of the comments by @timsnyder 
> `conda skeleton cpan --recursive YAML::Tiny File::HomeDir Unicode::GCString Log::Log4perl Log::Dispatch::File` from my rebased PR branch ran for 22.5m generating 105 package recipes before it hit an unrecoverable error.

I think that to move forward what is needed is a clear dependency-map. Could you generate one @cmhughes ?

**Comment by cmhughes** [comment]
Ok, many thanks. I'll try and take a look. Sounds like an interesting
project.

**Comment by cmhughes** [comment]
Sorry for the delay.

I followed https://stackoverflow.com/questions/358891/how-do-i-find-the-module-dependencies-of-my-perl-script and added the following line
```perl
print join("\n", map { s|/|::|g; s|\.pm$||; $_ } keys %INC);
```
to the `latexindent` subroutine with `LatexIndent/Document.pm`. 

This gives the following output. Is it as you need...?
```
Log::Log4perl::Layout::PatternLayout
Specio::Exception
LatexIndent::IfElseFi
Log::Log4perl::Util
Fcntl
LatexIndent::Heading
LatexIndent::Preamble
Scalar::Util
warnings::register
Encode::MIME::Name
Specio::PartialDump
Text::Wrap
re
Specio::Library::Numeric
Cwd
File::Basename
Log::Log4perl::Config::Watch
Package::Stash::XS
Exception::Class
File::Spec::Unix
Specio::DeclaredAt
Package::Stash
Log::Log4perl::Layout::PatternLayout::Multiline
Log::Log4perl::DateFormat
Config_heavy.pl
LatexIndent::GetYamlSettings
LatexIndent::HiddenChildren
Specio::Constraint::Parameterizable
Encode
MRO::Compat
Log::Dispatch::Vars
Params::ValidationCompiler::Exception::ValidationFailedForMooseTypeConstraint
LatexIndent::OptionalArgument
Specio::Helpers
LatexIndent::Environment
Config
namespace::clean
XSLoader
Specio::Constraint::Role::CanType
Sub::Exporter::Progressive
IO::Handle
Unicode::LineBreak::Constants
Params::ValidationCompiler::Exception::Named::Required
LatexIndent::ModifyLineBreaks
Sub::Util
LatexIndent::Version
mro
Log::Log4perl::Layout
Role::Tiny
LatexIndent::RoundBrackets
vars
Specio::Exporter
File::HomeDir::Unix
File::Which
Params::ValidationCompiler
base
Unicode::GCString
Log::Log4perl::JavaMap
LatexIndent::AlignmentAtAmpersand
Specio::Registry
Config_git.pl
Log::Log4perl::Filter
LatexIndent::Command
Unicode::LineBreak
LatexIndent::HorizontalWhiteSpace
Sys::Hostname
B::Hooks::EndOfScope::XS
Class::Data::Inheritable
Log::Log4perl::Config::BaseConfigurator
Devel::StackTrace
Log::Log4perl::Level
LatexIndent::DoubleBackSlash
Eval::Closure
Specio::TypeChecks
PerlIO
lib
Module::Runtime
B
Devel::StackTrace::Frame
Symbol
LatexIndent::Item
Specio::Coercion
Data::Dumper
File::HomeDir
LatexIndent::UnNamedGroupingBracesBrackets
Encode::Alias
Sub::Identify
LatexIndent::FileExtension
Log::Log4perl::NDC
FindBin
namespace::autoclean
Params::ValidationCompiler::Compiler
Specio::Constraint::AnyCan
B::Hooks::EndOfScope
Log::Dispatch::Output
Specio::Constraint::Union
LatexIndent::FileContents
Log::Log4perl
LatexIndent::LogFile
LatexIndent::Special
Specio::Library::Builtins
strict
LatexIndent::Sentence
Specio::Constraint::Role::Interface
LatexIndent::Indent
LatexIndent::Verbatim
LatexIndent::MandatoryArgument
overload
Log::Log4perl::Logger
LatexIndent::KeyEqualsValuesBraces
YAML::Tiny
Module::Implementation
Log::Log4perl::MDC
LatexIndent::NamedGroupingBracesBrackets
LatexIndent::Arguments
Params::ValidationCompiler::Exception::Positional::Required
LatexIndent::TrailingComments
LatexIndent::Replacement
Specio::Role::Inlinable
Getopt::Long
LatexIndent::Else
utf8
LatexIndent::Switches
Params::ValidationCompiler::Exception::BadArguments
LatexIndent::Tokens
Text::Tabs
LatexIndent::BackUpFileProcedure
File::HomeDir::FreeDesktop
Params::ValidationCompiler::Exception::Positional::Extra
Params::ValidationCompiler::Exceptions
Time::HiRes
open
Specio
File::Copy
LatexIndent::BlankLines
Encode::Config
Params::ValidationCompiler::Exception::Named::Extra
LatexIndent::Braces
Log::Log4perl::Filter::Boolean
Storable::Limit
constant
Log::Log4perl::Config::PropertyConfigurator
File::Spec
Specio::Library::String
Exporter
Storable
Log::Dispatch::File
File::HomeDir::Driver
Log::Log4perl::Appender
namespace::clean::_Util
Log::Log4perl::Util::TimeTracker
Log::Dispatch
warnings
Encode::Encoding
Log::Log4perl::Layout::SimpleLayout
Exporter::Heavy
PerlIO::encoding
Log::Log4perl::Appender::String
Specio::Constraint::Simple
SelectSaver
parent
Log::Dispatch::Base
IO
Try::Tiny
MIME::Charset
Log::Log4perl::Config
LatexIndent::Document
Carp
Variable::Magic
Specio::Declare
Log::Dispatch::Types
Specio::Constraint::Parameterized
overloading
Log::Log4perl::Appender::Screen
bytes
Exception::Class::Base
List::Util
Role::Tiny::With
Specio::OO
```

**Comment by tdegeus** [comment]
That is indeed a good step! Do you know if this is the 'root' of the dependencies ? I.e. will there be more recursive dependencies? The latter is where I got stuck before, each dependency exposed a bunch of other dependencies, so after adding them for hours there was still no hope of getting them all. 

Another question is, is it right to think of bundles ? I.e. is or could `Log` or `Log::Log4perl` be a bundle?

**Comment by cmhughes** [comment]
Thanks for this.



On Mon, 2 Nov 2020, 10:29 Tom de Geus, <notifications@github.com> wrote:

> Do you know if this is the 'root' of the dependencies ? I.e. will there be
> more recursive dependencies?
>
I think these represent 'root', but this is the first time I've explored
this.

> Another question is, is it right to think of bundles ? I.e. is or could
> Log or Log::Log4perl be a bundle?
>
I think that 'Log ::Log4perl' be the bundle. But as above, not
entirely sure....

**Comment by cmhughes** [comment]
I'm going to close this for now. I don't have anything else to add, but let me know if you have any other questions.

**Comment by koppor** [comment]
Based on https://github.com/cmhughes/latexindent.pl/issues/196#issuecomment-616204184, I could create the `apt-get` command (by googling each module name with `debian ` added to the google word):

    sudo apt-get install -y libyaml-tiny-perl libfile-homedir-perl libunicode-linebreak-perl liblog-log4perl-perl libtest-log-dispatch-perl

**Comment by tdegeus** [comment]
@cmhughes We finally managed to overcome perl issues, and the feedstock is now ready : https://github.com/conda-forge/staged-recipes/pull/16914 

If you would like to be a co-maintainer please state this in the comment of the PR.

**Comment by cmhughes** [comment]
That's great news, we'll done for taking that forward!

It's unlikely I'm qualified to be a maintainer for the project, but let me know (as you have here) if you have any questions :)

**Comment by cmhughes** [comment]
Just noting for everyone's reference : Log4perl and GCString no longer required, see


https://github.com/cmhughes/latexindent.pl/releases/tag/V3.9

https://github.com/cmhughes/latexindent.pl/releases/tag/V3.17
