### ISSUE TITLE
How to disable output to a log file

### ISSUE THREAD

**Issue by jleaves** [cmhughes/latexindent.pl#198]
Latexindent is a great tool. It's really helpful for formatting latex code.

However, every time I run it, a log file is generated. Most of the time, I don't need that log file. Is there a way to disable outputting to a log file completely? Sorry if I miss anything, but I can't find that option in the documentation.

**Comment by cmhughes** [comment]
Thanks for this, and I'm glad the tool works for you:)

Have you seen the -c switch, which allows you to output the cruft files to
another directory?

**Comment by cmhughes** [comment]
https://latexindentpl.readthedocs.io/en/latest/sec-how-to-use.html#from-the-command-line

**Comment by cmhughes** [comment]
Thanks for this.

I think some folks have set up the -c switch to output to some kind of null directory.

Another option is to use the -g switch to specify a hidden log file, for example, 

-g=.indent.log 

note the .

There's no options for completely disabling the log file. You might also like the -s switch.

**Comment by jleaves** [comment]
Thanks.

If I use `-c=some/nonexistent/directory`, it will exit without any indentation done because of that. Can you kindly elaborate more on the "null directory" approach?

**Comment by cmhughes** [comment]
Which OS are you using?

**Comment by jleaves** [comment]
> Which OS are you using?

Windows. 

The output in the terminal is

```
Could not find directory xxx
Exiting, no indentation done. at D:/.../Latexindent/Logfile.pm line 104.
```

And it is not some permission issue, since the same output even with administrative privileges.

**Comment by cmhughes** [comment]
Thanks for this, apologies for the delay.

It's not obvious if there is a null directory available for windows (Linux has `/dev/null`). 

You could try making the logfile hidden by, for example:
```
latexindent -g .indent.log myfile.tex
```
Does that help to progress?

**Comment by jleaves** [comment]
Thank you. I don't think this hidden file approach will really make the file hidden in Windows. But anyway, I think It's ok to just designate a specified directory to hold the log file. So this issue can be closed for now.

**Comment by cmhughes** [comment]
Ok, many thanks, do feel free to stop by if you have questions in the future.

**Comment by cmhughes** [comment]
https://github.com/cmhughes/latexindent.pl/releases/tag/V3.9.3
