### ISSUE TITLE
Can't locate File/HomeDir.pm

### ISSUE THREAD

**Issue by yfpeng** [cmhughes/latexindent.pl#2]
I got "Can't locate File/HomeDir.pm" msg while using your source code.

**Comment by mahdikooshkbaghi** [comment]
> I had to install an additional package. In Debian/Ubuntu it is called libfile-homedir-perl .

In Arch, I needed to install `perl-file-homedir` from AUR.

**Comment by cmhughes** [comment]
Feel free to update documentation :) pull request to develop
