### ISSUE TITLE
single 0 will vanish in environment {align} and {align*}

### ISSUE THREAD

**Issue by qiancy98** [cmhughes/latexindent.pl#201]
When writing my paper I find a bug in latexindent. I'm using Windows 10 OS and VS Code for editor. The minimal code is as follows:
```
\documentclass[a4paper,10pt]{article}
\usepackage{amsmath}

\begin{document}
\begin{align*}
    0
\end{align*}
\begin{align}
    0
\end{align}
\end{document}
```
It compiles well. However, after running latexindent, the two lines with single `0` just vanish, and becomes
```
\documentclass[a4paper,10pt]{article}
\usepackage{amsmath}

\begin{document}
\begin{align*}

\end{align*}
\begin{align}

\end{align}
\end{document}
```

**Comment by cmhughes** [comment]
Thanks for this.

It does look like a bug, I'll test it soon.

A few things that you can try to get round it:

- is align* within lookForAlignDelims? If it is, then setting it to 0 might
help
- failing that, you might add align* to verbatimEnvironments as detailed in
https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html#lst-verbatimenvironments

Thanks again, I'll report back.

**Comment by cmhughes** [comment]
Many thanks for reporting this. This is resolved as of https://github.com/cmhughes/latexindent.pl/pull/202

An upload to ctan is imminent, and you should be able to get V3.8.1 from your tex distribution in the next few days.
