### ISSUE TITLE
old version of latexindent.exe

### ISSUE THREAD

**Issue by uyfv554** [cmhughes/latexindent.pl#203]
I wonder where I could find the old version of the executable **latexindent.exe**. Thank you.

**Comment by cmhughes** [comment]
Thanks for this. I'll update the releases page for this.

Not sure when I commit to this, but hopefully soon.

**Comment by cmhughes** [comment]
Quick update on this: releases (https://github.com/cmhughes/latexindent.pl/releases?after=V3.4.3) for V3.4.2 and before contain the executable within the associated `.zip` folder. 

I'll work on a solution for V3.4.3 and subsequent releases.

**Comment by cmhughes** [comment]
Update: I've been through the releases, and added `latexindent.exe` as an asset to each one of the releases: https://github.com/cmhughes/latexindent.pl/releases

I'll continue to add `latexindent.exe` as an asset in the future.
