### ISSUE TITLE
YAML (JSON) schema for the config file?

### ISSUE THREAD

**Issue by kachkaev** [cmhughes/latexindent.pl#206]
👋 @cmhughes, may thanks for creating `latexindent`!

I’m new to the tool, so haven’t got much further than creating `latexindent.yaml` in my LaTeX Project and configuring VSCode [LaTeX Workshop](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop) to apply my local config file on save.

<details>
<summary>settings.json</summary>
<pre>
{
  "latex-workshop.latexindent.path": "/usr/local/texlive/2020/texmf-dist/scripts/latexindent/latexindent.pl",
  "[latex]": {
    "editor.defaultFormatter": "James-Yu.latex-workshop"
  },
  "latex-workshop.latexindent.args": [
    "--local",
    "%DIR%/latexindent.yaml",
    "--modifylinebreaks",
    "-cruft",
    "%DIR%/",
    "%TMPFILE%"
  ]
}
</pre>
</details>

My feature request is about the user experience for editing `latexindent.yml`. At the moment, the only way to know which options are valid is to read [latexindent pdf](http://mirror.ox.ac.uk/sites/ctan.org/support/latexindent/documentation/latexindent.pdf) or [the website](https://latexindentpl.readthedocs.io/en/latest/). If there is a typo in the config key of if a key is under a wrong section, there is no feedback until some tex file is saved. Besides, there is no intellisense (autocompletion) for keys and values.

VSCode can [read YAML (JSON) schemas](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) and thus significantly improve the UX. Here is an example of what autocompletion looks like when I edit a [Kubernetes](https://kubernetes.io/) deployment or [ESLint](https://eslint.org/) config:

<img width="815" alt="Screenshot 2020-06-07 at 12 41 21" src="https://user-images.githubusercontent.com/608862/83968176-35059680-a8bf-11ea-9574-f7a9f557f346.png">

---

<img width="867" alt="Screenshot 2020-06-07 at 13 00 22" src="https://user-images.githubusercontent.com/608862/83968181-3931b400-a8bf-11ea-8c51-fcffd9f72731.png">

---

<img width="763" alt="Screenshot 2020-06-07 at 13 00 47" src="https://user-images.githubusercontent.com/608862/83968193-4a7ac080-a8bf-11ea-8438-8c9460125d6d.png">

Autocompletion for ESLint seems to come from https://json.schemastore.org/eslintrc, because somebody once contributed to https://www.schemastore.org/json/ and VSCode picked that up. The k8s schemas probably come from a corresponding VSCode extension – I haven’t fully traced that.

YAML / JSON schemas are not only useful for intellisense, but can also be picked by linting tools such as [`yaml-schema-validator`](https://www.npmjs.com/package/yaml-schema-validator) (I'm sure there are plenty of such of a kind).

A schema for `latexindent.pl` YAMLs can enable some nice scenarios, so it’d be great if you could consider creating it. What do you think?

**Comment by cmhughes** [comment]
Hi @kachkaev ,
Many thanks for this, it sounds like an interesting idea, and it's always good to try to improve the user experience 

The links you've provided should help me to look into this, thank you.

As I do so, could you help me with the following questions:

- is VSCode available for Linux?
- would other editors (such as vim, for example) have natural ways to connect with this...?

Thanks again!
Chris

**Comment by kachkaev** [comment]
Thanks for your reply and for the potential interest @cmhughes!

> is VSCode available for Linux?

Yep, VSCode has `*.deb` and `*.rpm` distributions: https://code.visualstudio.com/download

There’s also https://vscodium.com, which is the same editor, but built by the community instead of Microsoft.

> would other editors (such as vim, for example) have natural ways to connect with this...?

I believe so, yes. YAML / JSON schemas are a pretty wide-spread concept, so I’m sure there is a solid integration into many editors and other tools. I first encountered if long before switching to VSCode a few years ago.

Check out this page for example: https://vega.github.io/editor/#/examples/vega-lite/rect_binned_heatmap. Because the JSON starts with `"$schema": "https://vega.github.io/schema/vega-lite/v4.json"`, the rest of the document can be statically analysed to a certain extent. Try replacing `"width"` with `"widthx"` or shorten it down to `"w"` and press `ctrl+space`.

Since JSON and YAML files are essentially the same thing, a once-generated schema is applicable to both formats. The spec can be found at https://json-schema.org

**Comment by cmhughes** [comment]
That's helpful, many thanks.

I'll take a more detailed look at this soon. From what you've said here, it
sounds like a good idea.

In the mean time, if you have any success in progressing it, do feel free
to let me know and to submit a pull request.

**Comment by cmhughes** [comment]
If anyone feels like taking this on (or, simply starting it), please do feel free. All pull requests to the `develop` branch :)

**Comment by cmhughes** [comment]
Very sorry for the delay on this. Development is slow at the moment for various reasons.

If anyone feels like starting it, please feel free :) all pull requests to `develop` branch.

**Comment by cmhughes** [comment]
Looks helpful:

https://json-schema.org/learn/getting-started-step-by-step.html

https://json-schema.org/learn/miscellaneous-examples.html

**Comment by cmhughes** [comment]
@kachkaev some good news, I've made created https://github.com/cmhughes/latexindent.pl/blob/develop/documentation/latexindent-yaml-schema.json :) It's on the `develop` branch.

If you'd like to take a look, I'd welcome any feedback. Documentation is in https://github.com/cmhughes/latexindent.pl/blob/develop/documentation/appendices.tex :)

**Comment by kachkaev** [comment]
Hi @cmhughes 👋 That’s great news indeed, thanks a lot for your effort!

I’m not actively working on any LaTeX documents at the moment, so won’t be able to check out the new feature any time soon – sorry. I’m sure I’ll benefit from it next time, so thanks a lot again! And a happy New Year! 🎉

**Comment by cmhughes** [comment]
@kachkaev many thanks, that's great :)

I've implemented this as of https://github.com/cmhughes/latexindent.pl/releases/tag/V3.13.5 and have uploaded it to ctan. 

Improvements and feedback welcome as and when you (and others) come to it. Happy new year!

**Comment by cmhughes** [comment]
Relevant part of documentation at https://latexindentpl.readthedocs.io/en/latest/appendices.html#latexindent-yaml-schema-json

**Comment by Freed-Wu** [comment]
How about publish
<https://github.com/cmhughes/latexindent.pl/blob/V3.13.5/documentation/latexindent-yaml-schema.json>
to [schemastore](https://www.schemastore.org/json/)?

**Comment by Freed-Wu** [comment]
schema store needs a URL. <https://github.com/SchemaStore/schemastore/pull/3510/files#diff-1b8f038f5afb1158263a1fc83b9c0ca5a7438cceb90adad99d87168f70edc815R476>

Keep the json schema's URL not changed is OK to get updated :smile:
