### ISSUE TITLE
[Docs] Running in Alpine Linux

### ISSUE THREAD

**Issue by jun-sheaf** [cmhughes/latexindent.pl#213]
I ran into several issues while installing this package on Alpine Linux. The reason was not inherently due to this package, but its dependencies; however, it would be good to put the following solution into the docs for others to use.

So I haven't looked too deeply into the reason *why*, but several dependencies will fail building due to several fundamental modules that are incompatible with Alpine. On a good note however, several packages fill these gaps on Alpine. The following snippet (coded Docker-style) will allow `latexindent` to run on Alpine:

```Dockerfile
# Installing perl
RUN apk --no-cache add miniperl perl-utils

# Installing incompatible latexindent perl dependencies via apk
RUN apk --no-cache add \
    perl-log-log4perl \
    perl-log-dispatch \
    perl-namespace-autoclean \
    perl-specio \
    perl-unicode-linebreak

# Installing remaining latexindent perl dependencies via cpan
RUN apk --no-cache add curl wget make
RUN ls /usr/share/texmf-dist/scripts/latexindent
RUN cd /usr/local/bin && \
    curl -L https://cpanmin.us/ -o cpanm && \
    chmod +x cpanm
RUN cpanm -n App::cpanminus
RUN cpanm -n File::HomeDir
RUN cpanm -n Params::ValidationCompiler
RUN cpanm -n YAML::Tiny
RUN cpanm -n Unicode::GCString
```

The packages that don't fail building are built natively at the end.

**Comment by cmhughes** [comment]
Many thanks for this, I don't have any experience of Alpine so it's helpful
to have these instructions.

Would you like to submit a pull request to the develop branch that gives
these details? The appropriate file would be in the documentation folder,
appendices.tex I think.

**Comment by cmhughes** [comment]
Implemented into develop as of https://github.com/cmhughes/latexindent.pl/pull/214. Thanks again!
