### ISSUE TITLE
Option for paragraph reflow/wrap according to a defined width.

### ISSUE THREAD

**Issue by RaulDurand** [cmhughes/latexindent.pl#216]
Using vim, it is usually convenient to use linebreaks to keep a paragraph inside de window width, but one ends up
with a paragraph with different line lengths.

An option for paragraph reflow/wrap according to a defined width would be ideal to keep those paragraphs tidy.

**Comment by cmhughes** [comment]
Hello!
Thanks for this. Could you give a demonstration of some sample text, both "before" and "after" together with what you might imagine the associated YAML settings to look like?
Thanks!
Chris

**Comment by cmhughes** [comment]
Let me know
