### ISSUE TITLE
Spaces Are Converted to Tabs in the Middle of Line

### ISSUE THREAD

**Issue by psttf** [cmhughes/latexindent.pl#217]
Hello and thank you for this great tool!

I've noticed that spaces become replaced with tabs but there seems to be no documentation on this feature. Excuse me if I missed it somewhere.

Minimal example:

- `test.tex`:
```
x       y
```
- `.indentconfig.yaml`
```yaml
modifyLineBreaks:
    textWrapOptions:
        columns: 80
```

Running `latexindent test.tex -m -w -l=.indentconfig.yaml` (on Windows 8.1) results in having the following content in `test.tex`:

```
x	y
```

Seven spaces became replaced with one tab! If there are more spaces they may be replaced with more tabs. But in any case such substitution may break alignments if they were done with spaces. Is it possible to turn off this behavior or fix it?

**Comment by cmhughes** [comment]
Hello!
Thanks for this, and I'm glad that you like the tool :)

I can confirm the behaviour that you describe. This doesn't seem ideal. A quick look hasn't revealed the cause, and I'll need to dig into this some more. 

I do note that if I change the number of spaces to be *six* spaces, then the script does not change the six spaces into tabs. 

Possible route for exploration: value of tabstop, as detailed in https://perldoc.perl.org/Text/Tabs.html. 

I'll explore this some more, but for the moment I'll label it as a bug. Thanks!

**Comment by cmhughes** [comment]
As of https://github.com/cmhughes/latexindent.pl/commit/87cec14181fc6adb128a0a96a4480aed05257a8c I have implemented the `tabstop` option for the text wrap routine. Explicitly, if you specify the following settings:
```yaml
modifyLineBreaks:
    textWrapOptions:
        columns: 80
        tabstop: 9
```
then the output that you specified remains unchanged.

If you get the `develop` branch, then you'll have access to this. Otherwise, I hope to do a release soon, which will contain this. I'll leave this issue open until it has been released.

Thanks for reporting this!

**Comment by psttf** [comment]
So, if space-collapsing behavior is not wanted then it is solved by adding `tabstop: <n+1>` where `n` is the maximum number of spaces that should be kept as is without collapsing, right?

**Comment by cmhughes** [comment]
Thanks again, this is implemented as of https://github.com/cmhughes/latexindent.pl/pull/227. Upload to ctan imminent.

**Comment by cmhughes** [comment]
Yes, that is correct :)

**Comment by psttf** [comment]
Thank you!
