### ISSUE TITLE
Windows executable

### ISSUE THREAD

**Issue by lovellbrian** [cmhughes/latexindent.pl#219]
Dear Chris,
I am having trouble with the current version of latexindent and MikTeX running via WinEdt.   I found that the windows exe that was automatically installed called perl.  I have replaced this with your standalone version from this repository and get the following error which is quite strange.  Any suggestions or pointers would be much appreciated.  I am using this mainly to covert files to one sentence per line.

Command Line:   latexindent.exe -w -l "conference_101719.tex"
Startup Folder: C:\Users\e3blovel\Desktop\papers2020\IJCB_TianrenWang

File 'C:/Program Files/MiKTeX/miktex/bin/x64/../../texmf-dist/scripts/latexindent/defaultSettings.yaml' does not exist at C:\Users\e3blovel\AppData\Local\Temp\par-6533626c6f76656c\cache-c2732a5e5eefb8882dfd54c2aabd335a5b583bb1\inc\lib/LatexIndent/GetYamlSettings.pm line 64.

Cheers,
Brian

**Comment by cmhughes** [comment]
Hi Brian,
Thanks for this.

It looks like it can't find defaultSettings.yaml. You can get the latest
version from this repository and place it in the same folder as the
executable.

Does this help?
Chris

**Comment by lovellbrian** [comment]
Dear Chris,

Thank you for very prompt and correct response.   That fixed the runtime problem. 

I now want to convert to oneSentencePerLine format for better Git editing.  I tried the command line below but this does not break at end of sentences.  Can you suggest what the line should be? Do I need to edit the yaml file?

 

I have been reading

https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html 

 

 

Command Line:   latexindent.exe -w -m -l=manipulate-sentences.yaml "conference_101719.tex"

Startup Folder: C:\Users\e3blovel\Desktop\papers2020\IJCB_TianrenWang

 

\documentclass[conference]{IEEEtran}

\IEEEoverridecommandlockouts

 

 

Regards,

Brian

**Comment by lovellbrian** [comment]
Dear Chris,

Nevermind I figured out that I need a local yaml config file to change the indentation settings.  All good now, I understand how this is configured. 

 

Command Line:   latexindent.exe -w -m -l=localSettings.yaml "conference_101719.tex"

Startup Folder: C:\Users\e3blovel\Desktop\papers2020\IJCB_TianrenWang

 

Thank you for your kind assistance and effort.  Output looks great. 

 

 

Regards,

Brian

 

From: Brian Lovell <lovell.brian@gmail.com> 
Sent: Thursday, 10 September 2020 8:17 PM
To: 'cmhughes/latexindent.pl' <reply@reply.github.com>; 'cmhughes/latexindent.pl' <latexindent.pl@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [cmhughes/latexindent.pl] Windows executable (#219)

 

Dear Chris,

Thank you for very prompt and correct response.   That fixed the runtime problem. 

I now want to convert to oneSentencePerLine format for better Git editing.  I tried the command line below but this does not break at end of sentences.  Can you suggest what the line should be? Do I need to edit the yaml file?

 

I have been reading

https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html 

 

 

Command Line:   latexindent.exe -w -m -l=manipulate-sentences.yaml "conference_101719.tex"

Startup Folder: C:\Users\e3blovel\Desktop\papers2020\IJCB_TianrenWang

 

\documentclass[conference]{IEEEtran}

\IEEEoverridecommandlockouts

 

 

Regards,

Brian

**Comment by cmhughes** [comment]
Fantastic, that's great to hear, Brian, glad it worked out :) happy indentation!

**Comment by lovellbrian** [comment]
Dear Chris,
Here are some notes on getting latexindent to work Miktex and WinEdt.   By default the current Miktex distribution installs the non-standalone version of latexindent.exe and this was the main source of my problem and confusion.  I could not understand why the exe file was calling perl.  Thanks so much.

--
Dear team,
Here are some brief instructions to get latexindent to work on your tex files.  Apart from nicely formatting your tex files for easy maintenance, there is the option to force oneline per sentence.  This makes multiple author revisions via GIT work much better as each sentence becomes a single editing unit instead of each paragraph.   I think this is a good idea for our all papers before inviting coauthors.  I am happy to do the conversion and this is how it is done.



  1.  Install latest MikTex  https://miktex.org/download and update packages
  2.  Check out C:\Program Files\MiKTeX\miktex\bin\x64\latexindent.exe and you will find it is only 62kb which means it is a link to perl and not a standalone exe
  3.  Replace this file with the standalone exe file from https://ctan.org/tex-archive/support/latexindent and also place the file defaultSettings.yaml in the same directory C:\Program Files\MiKTeX\miktex\bin\x64
  4.  Now latexindent is runnable and the documentation is at https://latexindentpl.readthedocs.io/en/latest/

Adding to WinEdt Tex editor. You can also use commandline etc.

  1.  Install WinEdt from https://www.winedt.com/
  2.  Run a macro to add latexindent to WinEdt from http://www.winedt.org/config/menus/latexindent.html
  3.  Create a localSettings.yaml in your source tex document directory  (Edit/latexindent/Modify localSettings.yaml)

Default settings will be:
defaultIndent: "  "

onlyOneBackUp: 1

Change to:
defaultIndent: "  "

onlyOneBackUp: 1

modifyLineBreaks:
    oneSentencePerLine:
        manipulateSentences: 1

This will give one sentence per line behaviour for better git revision control.

Modify Execution Mode switches for latexindent to add localSettings.yaml listing (Options/Execution Modes):

[cid:image001.png@01D68837.8E9F6D40]


Now Edit/latexindent/latexindent should format your tex file appropriately.





Regards
Brian

The University of Queensland CRICOS No. 00025B
