### ISSUE TITLE
A guide on how to use this tool on Nixos / Nix

### ISSUE THREAD

**Issue by mingyuguo** [cmhughes/latexindent.pl#222]
I love this tool but really had difficulty get it working on nixos. After 1 hour of tinkering, this is how I got it working, so I am sharing it here for other nixos users. Please correct me if I am not doing it optimally.

I couldn't figure out how to install perl packages on nixos because nixos does things differently. I actually used to know how to program in perl but haven't touched it for many years already.

I also couldn't simply just add perlPackages.Log4Perl in my package list, because it refuses to be picked up by latexindent.pl.

Here is how I did it. I created an alias:

latexindent = "nix-shell -p perl perlPackages.Log4Perl perlPackages.LogDispatch perlPackages.YAMLTiny perlPackages.FileHomeDir perlPackages.UnicodeLineBreak --run '/path/to/latexindent.pl -m -l /path/to/myLatexIndent.yaml -' ";

then I set latexindent to be the  formatprg and equalprg in vim.

**Comment by cmhughes** [comment]
Many thanks for this :)

I'm sorry that the tool was difficult to get working. It's the feedback
that I see the most, particularly around the Log4Perl module. I'm very
hopeful to do something about this in the future.

I think this repository needs some kind of wiki page for these kinds of
instructions. I'll look into it and get back to you :)

Thanks again!

**Comment by cmhughes** [comment]
Thanks again for this. I've added it to the documentation as of https://github.com/cmhughes/latexindent.pl/commit/a40609ed2387bf85e190590e467dd37bafb4fadd
