### ISSUE TITLE
Formatting TikZ stuff?

### ISSUE THREAD

**Issue by jasonhan-vassar** [cmhughes/latexindent.pl#223]
Hi, I'm looking for a way to nicely auto-indent my LaTeX source code involving TikZ stuff. Here is an example of the formatting I'm looking for below. Notice how the node names and labels are all aligned.

![B019A6C5-C26A-4EB0-A8EB-7A40C21C57E6](https://user-images.githubusercontent.com/34594853/96547133-911ef500-1279-11eb-8659-85baa4f76767.png)

latexindent.pl is amazing and formats well, but doesn't quite indent the `\node` or `\path` stuff out of the box; does anyone have experience fine tuning the settings to support TikZ? Thanks for reading!

**Comment by cmhughes** [comment]
Thanks for this, it's an interesting question!

I wonder if the align at delimeter routine could be customised for this. A possible starting point is https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html#lst-delimiterregex1

I hope to take a look at this soon, but let me know if you make any progress. I suspect that we might also employ the specialBeginEnd field....

**Comment by cmhughes** [comment]
If I start with the following file, say `vassar.tex`

```tex
\begin{tikzpicture}[->,>=stealth',shorten >=1pt,auto,node distance=2.8cm,on grid,semithick,
every state/.style={fill=red,draw=none,circular drop shadow,text=white}]
  \path 
  (A) edge node {0,1,L}(B)
  edge node {1,1,R} (C)
  (B) edge [loop above]node {1,1,L}(B)
  edge node {0,1,L}(C)
  (C) edge node{0,1,L}(D)
  edge [bend left]node {1,0,R}(E)
  (D) edge[loop below] node {1,1,R}(D)
  edge node {0,1,R}(A)
  (E) edge[bend left] node {1,0,R} (A);
\end{tikzpicture}
```
and the settings in `vassa1.yaml`
```yaml
specialBeginEnd:
    path:
        begin: '\\path'
        end: ';'
        lookForThis: 1
    specialBeforeCommand: 1

lookForAlignDelims:
   path: 
      delimiterRegEx: '(edge|node)'
```
and run the command
```bash
latexindent.pl  vassar.tex -l vassar1.yaml -t -o=+-mod1
```
then I receive `vassar-mod1.tex`
```tex
\begin{tikzpicture}[->,>=stealth',shorten >=1pt,auto,node distance=2.8cm,on grid,semithick,
		every state/.style={fill=red,draw=none,circular drop shadow,text=white}]
	\path
		(A) edge              node {0,1,L}(B)
		    edge              node {1,1,R} (C)
		(B) edge [loop above] node {1,1,L}(B)
		    edge              node {0,1,L}(C)
		(C) edge              node {0,1,L}(D)
		    edge [bend left]  node {1,0,R}(E)
		(D) edge [loop below] node {1,1,R}(D)
		    edge              node {0,1,R}(A)
		(E) edge [bend left]  node {1,0,R} (A);
\end{tikzpicture}
```

If your `path` command does not finish with a line break, then the output isn't quite ideal:
```tex
\begin{tikzpicture}[->,>=stealth',shorten >=1pt,auto,node distance=2.8cm,on grid,semithick,
		every state/.style={fill=red,draw=none,circular drop shadow,text=white}]
	\path (A) edge              node {0,1,L}(B)
		    edge              node {1,1,R} (C)
		(B) edge [loop above] node {1,1,L}(B)
		    edge              node {0,1,L}(C)
		(C) edge              node {0,1,L}(D)
		    edge [bend left]  node {1,0,R}(E)
		(D) edge [loop below] node {1,1,R}(D)
		    edge              node {0,1,R}(A)
		(E) edge [bend left]  node {1,0,R} (A);
\end{tikzpicture}
```

It's not clear to me if this second output is an issue or not...

But, for the moment, I hope that I've got you started :)

**Comment by jasonhan-vassar** [comment]
Thanks so much! I haven't had the time to experiment yet, but after you pointed those two fields out, I was thinking those would be pretty useful for my problem. I'm going to experiment adding something to find `(A)`, `(B)`, `(matching anything inside parentheses)`, etc.

As for the line break issue, it's not quite ideal but it's a really small issue and I feel like I be nitpicking at that point. I did notice that `\item` supports indenting well: everything afterwards begins at the same starting indentation, even without a line break. Do you know if I could make `\path` do something similar?

**Comment by jasonhan-vassar** [comment]
After doing some testing with `\item` related settings, I've been struggling with getting latexindent.pl to recognize `\path` as an "item." I've added a few things to your YAML file:

```
specialBeginEnd:
    path:
        begin: '\\path'
        end: ';'
        lookForThis: 1
    specialBeforeCommand: 1

lookForAlignDelims:
   path: 
      delimiterRegEx: '(edge|node)'
   item: 
      delimiterRegEx: '(edge|node)'

indentAfterItems:
    tikzpicture: 1

itemNames:
    path: 1
```

Here is an example of the `\item` indentation that I'm looking for below. This solves my line break problem nicely.

```
\begin{tikzpicture}[->,>=stealth',shorten >=1pt,auto,node distance=2.8cm,on grid,semithick,
        every state/.style={fill=red,draw=none,circular drop shadow,text=white}]
    \item (A) edge              node {0,1,L}(B)
              edge              node {1,1,R} (C)
          (B) edge [loop above] node {1,1,L}(B)
              edge              node {0,1,L}(C)
          (C) edge              node {0,1,L}(D)
              edge [bend left]  node {1,0,R}(E)
          (D) edge [loop below] node {1,1,R}(D)
              edge              node {0,1,R}(A)
          (E) edge [bend left]  node {1,0,R} (A);
\end{tikzpicture}
```

However, I'm having some trouble of getting `tikzpicture` to treat `\path` as an item. My YAML has my attempt at doing so, but here's a demonstration of what happens. The `itemize` environments are just there for further demonstration.

```
\begin{tikzpicture}[->,>=stealth',shorten >=1pt,auto,node distance=2.8cm,on grid,semithick,
        every state/.style={fill=red,draw=none,circular drop shadow,text=white}]
    \path (A) edge              node {0,1,L}(B)
            edge              node {1,1,R} (C)
        (B) edge [loop above] node {1,1,L}(B)
            edge              node {0,1,L}(C)
        (C) edge              node {0,1,L}(D)
            edge [bend left]  node {1,0,R}(E)
        (D) edge [loop below] node {1,1,R}(D)
            edge              node {0,1,R}(A)
        (E) edge [bend left]  node {1,0,R} (A);
\end{tikzpicture}

\begin{itemize}
    \path some text here
        some more text here
        some more text here
    \path another item
        some more text here
\end{itemize}

\begin{itemize}
    \item some text here
          some more text here
          some more text here
    \item another item
          some more text here
\end{itemize}
```

Could you please let me know if I'm making any mistakes with the YAML stuff? Thanks again!

**Comment by cmhughes** [comment]
Thanks for this.my current thinking is that you shouldn't need to specify this an item, and that this is a bug. I'll label it as such and hope to look at it soon, and report back. :)

**Comment by cmhughes** [comment]
I've fixed this as of https://github.com/cmhughes/latexindent.pl/commit/501b72f830fc606408dc51a23c3932fd4303e031 You can grab the `develop` branch if you'd like to have a working version; otherwise I'll be doing a release soon that will be uploaded to ctan. 

Thanks again for reporting this.

(I'd like to try to get some of the other bugs resolved, before releasing.)

**Comment by jasonhan-vassar** [comment]
It's working now, thanks again! I appreciate you taking the time to check out the issue and quickly developing a fix :)

**Comment by cmhughes** [comment]
Great! I'll leave this open until it has been released.

**Comment by cmhughes** [comment]
Thanks again, this is implemented as of https://github.com/cmhughes/latexindent.pl/pull/227. Upload to ctan imminent.
