### ISSUE TITLE
latexindent doesn't run without sudo on MacOS

### ISSUE THREAD

**Issue by nikchha** [cmhughes/latexindent.pl#224]
Hi and thank you for providing this cool tool.

I am trying to install latexindent on MacOS because LaTeX Workshop in VS Code raises an Error when compiling.

**Installation Process**

1.  `latexindent` was shipped with MacTex that was installed vial `brew cask install mactex-no-gui`
2. I installed perl and cpanm with the following commands:

```
brew install perl
brew install cpanm
```

3. I used your `latexindent-module-installer.pl` script to install the missing modules with `sudo perl latexindent-module-installer.pl`

**Error**

When I test my latexindent.pl installation running the following command `latexindent` I get the following error:

```
Can't load '/Users/username/perl5/lib/perl5/darwin-thread-multi-2level/auto/Unicode/LineBreak/LineBreak.bundle' for module Unicode::LineBreak: dlopen(/Users/username/perl5/lib/perl5/darwin-thread-multi-2level/auto/Unicode/LineBreak/LineBreak.bundle, 1): Symbol not found: _linebreak_format_NEWLINE
  Referenced from: /Users/username/perl5/lib/perl5/darwin-thread-multi-2level/auto/Unicode/LineBreak/LineBreak.bundle
  Expected in: flat namespace
 in /Users/username/perl5/lib/perl5/darwin-thread-multi-2level/auto/Unicode/LineBreak/LineBreak.bundle at /usr/local/Cellar/perl/5.32.0/lib/perl5/5.32.0/XSLoader.pm line 96.
 at /Users/username/perl5/lib/perl5/darwin-thread-multi-2level/Unicode/LineBreak.pm line 63.
Compilation failed in require at /Users/username/perl5/lib/perl5/darwin-thread-multi-2level/Unicode/GCString.pm line 24.
BEGIN failed--compilation aborted at /Users/username/perl5/lib/perl5/darwin-thread-multi-2level/Unicode/GCString.pm line 24.
Compilation failed in require at /usr/local/texlive/2020/texmf-dist/scripts/latexindent/LatexIndent/AlignmentAtAmpersand.pm line 20.
BEGIN failed--compilation aborted at /usr/local/texlive/2020/texmf-dist/scripts/latexindent/LatexIndent/AlignmentAtAmpersand.pm line 20.
Compilation failed in require at /usr/local/texlive/2020/texmf-dist/scripts/latexindent/LatexIndent/Document.pm line 38.
BEGIN failed--compilation aborted at /usr/local/texlive/2020/texmf-dist/scripts/latexindent/LatexIndent/Document.pm line 38.
Compilation failed in require at /Library/TeX/texbin/latexindent line 27.
BEGIN failed--compilation aborted at /Library/TeX/texbin/latexindent line 27.
```
When I run latexindent with `sudo latexindent` it does work as expected. However, VS Code runs latexindent without sudo.

**Comment by cmhughes** [comment]
Hi,
thanks for this.

I'm not familiar with Mac OS, but have seen a few questions on installation.

I'm not sure why you had to run the module installation as sudo....?

Have you tried the following:

 brew install YAML::Tiny
 brew install File::HomeDir
 brew install Unicode::GCString
 brew install Log::Log4perl
 brew install Log::Dispatch::File

See also https://tex.stackexchange.com/questions/390433/how-can-i-install-latexindent-on-macos

**Comment by nikchha** [comment]
Hi, thank you for your reply. 

I installed the modules with `sudo` because some dependencies failed when installing without `sudo`. It was also proposed in https://tex.stackexchange.com/questions/390433/how-can-i-install-latexindent-on-macos.
In particular, the following dependency:

```
Configuring Mac-SystemDirectory-0.13 ... N/A
! Configure failed for Mac-SystemDirectory-0.13. See /Users/username/.cpanm/work/1603444926.88404/build.log for details.
! Installing the dependencies failed: Module 'Mac::SystemDirectory' is not installed
```

Brew does only install perl but the modules are not available on brew and must be installed via cpan.

Best,
Niklas

**Comment by cmhughes** [comment]
Ok, thanks for this.

Is it the issue that the directories you've listed can't be read by a non-sudo user? If so, can you change the ownership/read permissions...?

**Comment by nikchha** [comment]
Thank you

I tried to change the permissions to the `latexindent` script with `sudo chown -R username /usr/local/texlive/2020` and `sudo chown -R username /Library/TeX/texbin` as proposed in https://tex.stackexchange.com/questions/540306/latexindent-doesnt-work-without-sudo

However, `latexindent` still does only work with `sudo` which causes the error in `vscode`.

Meanwhile, `Mac::SystemDirectory` was successfully installed in my last reinstall of `perl` so that didn't cause the error.

**Comment by cmhughes** [comment]
Are you able to run the minimum script at

https://latexindentpl.readthedocs.io/en/latest/appendices.html#lst-helloworld

**Comment by nikchha** [comment]
Hi, thank you for your quick reply.
The minimum script results in the same error when executed without `sudo`.

`perl helloworld.pl`  ->

```
Can't load '/Users/username/perl5/lib/perl5/darwin-thread-multi-2level/auto/Unicode/LineBreak/LineBreak.bundle' for module Unicode::LineBreak: dlopen(/Users/username/perl5/lib/perl5/darwin-thread-multi-2level/auto/Unicode/LineBreak/LineBreak.bundle, 1): Symbol not found: _PL_strict_utf8_dfa_tab
  Referenced from: /Users/username/perl5/lib/perl5/darwin-thread-multi-2level/auto/Unicode/LineBreak/LineBreak.bundle
  Expected in: flat namespace
 in /Users/username/perl5/lib/perl5/darwin-thread-multi-2level/auto/Unicode/LineBreak/LineBreak.bundle at /System/Library/Perl/5.18/XSLoader.pm line 71.
 at /Users/username/perl5/lib/perl5/darwin-thread-multi-2level/Unicode/LineBreak.pm line 63.
Compilation failed in require at /Users/username/perl5/lib/perl5/darwin-thread-multi-2level/Unicode/GCString.pm line 24.
BEGIN failed--compilation aborted at /Users/username/perl5/lib/perl5/darwin-thread-multi-2level/Unicode/GCString.pm line 24.
Compilation failed in require at helloworld.pl line 7.
BEGIN failed--compilation aborted at helloworld.pl line 7.
```

`sudo perl helloworld.pl` -> `hello world`

**Comment by cmhughes** [comment]
Ok, that's helpful.

It looks to me that you need to change the ownership of the directories
given in the error messages.

The command

ls -l

Should give you details of which user owns the directories. At the moment,
I would expect the details to.give that sudo owns them.

**Comment by nikchha** [comment]
Hi and thank you for your reply.

I tried to change permissions to 

1. `sudo chown -R username `/Library/TeX/texbin`
2. `sudo chmod -R +rw /Users/username/perl5`
2. `sudo chmod -R +rw /usr/local/Cellar/perl` (brew install location)

I also checked the ownership of each folder and nothing is owned by `root` but all by my `username`.

I have no idea what else I can do at this point - what surprises me the most is that it works perfectly with `sudo` (root).

**Comment by cmhughes** [comment]
How about the ownership of the latexindent executable? It might be called
latexindent.pl or otherwise simply latexindent

**Comment by nikchha** [comment]
Thanks again for your great support.

The executable is also owned by the username (and not root)

`-rwxr-xr-x   1 username  wheel   2912 Jun 11 23:11 latexindent.pl`

**Comment by cmhughes** [comment]
No worries, I'm sorry this isn't working.

Have you tried the solution given at: https://superuser.com/a/83321/250491

**Comment by nikchha** [comment]
No worries, I appreciate your great support! I would really like to use your Tool with VSCode and LaTeX Workshop, but maybe its some fundamental issue with MacOS and perl.

MacOS Catalina does not offer the Repair Permission utility anymore and they suggest a clean install. I will do so when the new MacOS Big Sur will be released later this year and report if there's still an issue with perl.

**Comment by cmhughes** [comment]
OK, many thanks. I'll close this for the moment. Let me know how things go as and when you have an update.

**Comment by nikchha** [comment]
Just a quick heads up - latexindent does word without `sudo` on my clean installed MacOS Big Sur.

Thank you for your support. I guess it was some permission issue.

**Comment by cmhughes** [comment]
That's great to hear, thanks very much for letting me know :)
