### ISSUE TITLE
oneSentencePerLine not working

### ISSUE THREAD

**Issue by wrd90** [cmhughes/latexindent.pl#226]
Hello,

First of all thank you for creating such a useful tool!
I have been trying to get the oneSentencePerLine config option to work, but for some reason I cannot seem to do so.

I have set up an example, containing the log file, a sample configuration and a tex input file for the test, and the output which is generated. Latexindent was invocated using the following command:

`latexindent -s -l=latexIndentSettings.yaml test.tex -o out.tex`

Any help is greatly appreciated!

Best,
David

[oneSentencePerLineTest.zip](https://github.com/cmhughes/latexindent.pl/files/5438253/oneSentencePerLineTest.zip)

**Comment by cmhughes** [comment]
Hi David,
Thanks for this, I'm glad you like the tool.

You'll need to use -m switch:

> latexindent -m -s -l=latexIndentSettings.yaml test.tex -o out.tex
>
Does this work for you?
Best
Chris

Any help is greatly appreciated!

**Comment by wrd90** [comment]
Hi Chris,

Thank you for your quick response. Yes, it does work! Silly me, I thought you could activate the flag both by the command line argument and the config file.

Have a great day!

Best,
David

**Comment by cmhughes** [comment]
Great, glad it worked! :) Happy indentation!
