### ISSUE TITLE
Unexpected behavior with perCodeBlockBasis ?

### ISSUE THREAD

**Issue by nicolasmeric** [cmhughes/latexindent.pl#228]
Hello,
here is a MWE (latexindent-bug.tex) to emphasize my issue:

```latex
\documentclass{article}

\begin{document}
test test test test \test{test} test test test test test test test tes
\end{document}
```

and a localSettings.yaml file:

```yaml
modifyLineBreaks:
  textWrapOptions:
    columns: 80
    perCodeBlockBasis: 1
    all: 1
```

The output of the command `latexindent -l -m latexindent-bug.tex`:

```latex
\documentclass{article}

\begin{document}
test test test test \test{test} test test test test test test test
tes
\end{document}
```

If I comment out the perCodeBlockBasis configuration:

```yaml
modifyLineBreaks:
  textWrapOptions:
    columns: 80
    # perCodeBlockBasis: 1
    # all: 1
```

I have this ouput:

```latex
\documentclass{article}

\begin{document}
test test test test \test{test} test test test test test test test tes
\end{document}
```

Is it expected to have a line break when using perCodeBlockBasis and none when not using it ?

Here is the indent.log whith perCodeBlockBasis: 
```log
INFO: latexindent version 3.8.3, 2020-11-06, a script to indent .tex files
      latexindent lives here: /path/texlive/2020/texmf-dist/scripts/latexindent/
      Sat Nov 14 23:45:44 2020
      Filename: latexindent-bug.tex
INFO: Processing switches:
      -l|--localSettings: Read localSettings YAML file
      -m|--modifylinebreaks: modify line breaks
INFO: Directory for backup files and indent.log: .
INFO: YAML settings read: defaultSettings.yaml
      Reading defaultSettings.yaml from /path/texlive/2020/texmf-dist/scripts/latexindent/defaultSettings.yaml
INFO: YAML settings read: indentconfig.yaml or .indentconfig.yaml
      Home directory is /path (didn't find either indentconfig.yaml or .indentconfig.yaml)
      To specify user settings you would put indentconfig.yaml here: /path/indentconfig.yaml
      Alternatively, you can use the hidden file .indentconfig.yaml as: /path/.indentconfig.yaml
INFO: YAML settings read: -l switch
      Adding ./localSettings.yaml to YAML read paths
INFO: YAML settings, reading from the following files:
      Reading USER settings from ./localSettings.yaml
      ---
      modifyLineBreaks:
        textWrapOptions:
          all: '1'
          columns: '80'
          perCodeBlockBasis: '1'
      
INFO: Phase 1: searching for objects
INFO: Phase 2: finding surrounding indentation
INFO: Phase 3: indenting objects
INFO: Phase 4: final indentation check
INFO: Output routine:
      Not outputting to file; see -w and -o switches for more options.
      --------------
INFO: Please direct all communication/issues to:
      https://github.com/cmhughes/latexindent.pl
```

**Comment by cmhughes** [comment]
Thanks for this, it's a good question.

Both of the outputs that you see are as expected. I'll try to explain.

> Is it expected to have a line break when using perCodeBlockBasis and none when not using it ?

Yes. Using `perCodeBlockBasis` instructs `latexindent.pl` to find all of the code blocks, and then perform text wrapping. Part of the internal workings of the script is that it replaces code blocks by unique IDs. For your example, part of the process has your `document` environment looking like:
```tex
test test test test LTXIN-TK-COMMAND1-END test test test test test test test tes
```
The important point is that the replacement text makes the line length longer than 80 columns, so the text wrapping routine gives the output that you describe. 

The current inner workings (a few details in https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#conflicting-poly-switches-nested-code-blocks) aren't ideal, and I hope to improve them one day. Perhaps part of that will enable an improvement of this aspect of the script.

I hope this helps :)

**Comment by nicolasmeric** [comment]
Thanks for your answer.
It's a bit disturbing because it is not the assumed behavior and it can lead to unwanted line breaks.
Indeed, if one uses the following MWE:

```latex
\documentclass{article}

\begin{document}
test test test test \testtesttesttesttesttesttest{test} test test test test test test test tes
\end{document}
```
or this one:

```latex
\documentclass{article}

\begin{document}
test test test test \test{test test test test test test} test test test test test test test tes
\end{document}
```
the 80 columns textWrapOptions can not be observed.

Is there a way to handle these cases?

**Comment by cmhughes** [comment]
Using the settings

wrap1.yaml
-
```yaml
modifyLineBreaks:
  textWrapOptions:
    columns: 80
```

If I start with your file

mwe1.tex
-
```tex
\documentclass{article}

\begin{document}
test test test test \testtesttesttesttesttesttest{test} test test test test test test test tes
\end{document}
```
and run the command
```bash
latexindent.pl -l wrap1.yaml -m mwe1.tex
```
then I receive the output
```tex
\documentclass{article}

\begin{document}
test test test test \testtesttesttesttesttesttest{test} test test test test
test test test tes
\end{document}
```

If I start with the file

mwe2.tex
-
```tex
\documentclass{article}

\begin{document}
test test test test \test{test test test test test test} test test test test test test test tes
\end{document}
```
and run the command
```bash
latexindent.pl -l wrap1.yaml -m mwe2.tex
```
then I receive the output
```tex
\documentclass{article}

\begin{document}
test test test test \test{test test test test test test} test test test test
test test test tes
\end{document}

```
Are these as you would like?

**Comment by nicolasmeric** [comment]
Sorry,
I meant with the perCodeBlockBasis option set.

I'll try your way with my files and look at the documentation to see if I am faced with a case where perCodeBlockBasis is mandatory.
But it's a bit annoying to have to test before using this kind of option to circumvent some side effects.

Anyway, thank you for your hard work. latexindent is nevertheless a very powerful tool and is very welcome.

I still have some questions not directly related to this issue. I will open other issues and maybe you'll be as friendly as you are now and you'll answer me.

I let you choose what to do with the current issue.

Thanks.

**Comment by cmhughes** [comment]
Many thanks, do feel free to bring further questions to this repository :)

**Comment by cmhughes** [comment]
I'll be working on textWrap as my next `latexindent.pl` priority. I'm taking a little break having just released V3.10.1, but hope to pick this up soon. Thanks for your patience :)

**Comment by nicolasmeric** [comment]
Cool, I'll wait patiently.

Thanks for your work.

**Comment by cmhughes** [comment]
An update! 

As of https://github.com/cmhughes/latexindent.pl/commit/2ae21141ffc6a66eff66af39d60624ac3f1a537d I have implemented an upgrade to the text wrapping routine, which I demonstrate below. My apologies for the delay, I don't usually expect to take this long to resolve issues; the last couple of years have been quite intense.

I hope that this is as you would like. Let me know if you have any comments or questions.

If you would like to grab the latest copy of the https://github.com/cmhughes/latexindent.pl/tree/develop branch, then you can test it for yourself. 

I have started with the following text for each demonstration:
```tex
\documentclass{article}

\begin{document}
test test test test \test{test test test test test test} test test test test test test test tes
\end{document}
```

demonstration 1
-
Starting with the above and using the following settings
```yaml
modifyLineBreaks:
    textWrapOptions:
        columns: 80
        perCodeBlockBasis: 1
        beforeFindingOtherCodeBlocks: 1   # <------ NEW BIT
        all: 1
    removeParagraphLineBreaks:
        all: 1
        beforeTextWrap: 1
```
gives the following output
```tex
\documentclass{article}

\begin{document}
test test test test \test{test test test test test test} test test test test
test test test tes \end{document}
```
**Note**: the `\end{document}` has been moved off its own line. We change that in the next demonstration.

demonstration 2
-
Tweaking the settings from above to be
```yaml
modifyLineBreaks:
    textWrapOptions:
        columns: 80
        perCodeBlockBasis: 1
        beforeFindingOtherCodeBlocks: 1    
        all: 1
    removeParagraphLineBreaks:
        all: 1
        beforeTextWrap: 1
    environments:
        document:
            EndStartsOnOwnLine: 1
```
gives the output
```tex
\documentclass{article}

\begin{document}
test test test test \test{test test test test test test} test test test test
test test test tes
\end{document}
```

**Comment by cmhughes** [comment]
This has been implemented and is part of the project as of https://github.com/cmhughes/latexindent.pl/releases/tag/V3.11. Upload to ctan will follow immediately :)

Thanks again for your help, stay in touch as and when things come up for `latexindent`!
