### ISSUE TITLE
Suppress generation of log file?

### ISSUE THREAD

**Issue by jasonhan-vassar** [cmhughes/latexindent.pl#230]
Is there a way to prevent `indent.log` from being created each run? If not, would it make sense to add this option as a flag?

**Comment by cmhughes** [comment]
Hello!
Thanks for this.

You could make the logfile hidden using the -g flag, for example

latexindent.pl -g .myfile.log my file.tex

Alternatively you could use the -c flag,

https://latexindentpl.readthedocs.io/en/latest/sec-how-to-use.html#from-the-command-line

Let me know what you think
Chris

**Comment by jasonhan-vassar** [comment]
The `-c` flag seems like the best solution I guess, I'll just redirect the logs to my `Library/Logs` directory on macOS.

Out of curiosity, is there a reason the user cannot prevent the log from being created though? I would imagine the log contains pretty important debugging info and what not in that case.

**Comment by cmhughes** [comment]
Yes, that's the intention; the log file contains important information for
debugging purposes.

I'll close this one, feel free to post back in this repository if you have
any questions :)

**Comment by cmhughes** [comment]
Possible as of https://github.com/cmhughes/latexindent.pl/releases/tag/V3.9.3
