### ISSUE TITLE
Non-ASCII environment names do not get indented

### ISSUE THREAD

**Issue by nidrissi** [cmhughes/latexindent.pl#236]
The script does not indent environments whose name contain non-ASCII characters (e.g. accented characters, which could happen when I decide to call an environment `théorème` for example). Here are two example outputs, with one file that gets indented and the other that doesn't:

This gets indented:

```
\documentclass{article}

\begin{document}
\begin{test}
    Blablabla.
\end{test}
\end{document}
```

This doesn't:

```
\documentclass{article}

\begin{document}
\begin{testé}
Blablabla.
\end{testé}
\end{document}
```

**Comment by cmhughes** [comment]
Thanks for this, it's helpful to hear this.

Is there a way that you can use the fine Tuning field to help with this:

https://latexindentpl.readthedocs.io/en/latest/sec-fine-tuning.html

I'll take a look over the coming days, but if you make any progress, let me know :)

**Comment by cmhughes** [comment]
Referencing https://perldoc.perl.org/perlrecharclass, perhaps we can use the following in `localSettings.yaml`

```yaml
fineTuning:
    environments:
      name: '[\p{XPosixAlnum}a-zA-Z@\*0-9_\\]+' 
```
and run `latexindent.pl -l myfile.tex` then we receive
```tex
\documentclass{article}

\begin{document}
\begin{testé}
	Blablabla.
\end{testé}
\end{document}
```
