### ISSUE TITLE
Missing indentation when optional argument contains two levels of curly braces

### ISSUE THREAD

**Issue by bersbersbers** [cmhughes/latexindent.pl#237]
An example is 
```
\pgfplotstabletypeset[
    col sep=tab,
    string type,
    header=true,
    columns={a,b,c,d,e,f},
    columns/a/.style={column type=l},
    columns/b/.style={column type=p{1cm}},
]{file.csv}
```
but I was able to reduce this into this MWE:

```
\macro[
    a={b=c},
]{n}

\macro[
    a={b=c{d}},
]{n}
```

The first is indented correctly in my opinion, while the second is wrong. `latexindent 3.8.3, 2020-11-06`

**Comment by bersbersbers** [comment]
I wonder if this example is related, as it also misses indentation when additional `[]` are introduced:
```
\caption{Hi
there}

\caption{Hi
there \texttt{x_y[:]}}
```

**Comment by cmhughes** [comment]
Thanks for this.

Starting with your original example, I confirm that the default output is:
```tex
\pgfplotstabletypeset[
col sep=tab,
string type,
header=true,
columns={a,b,c,d,e,f},
columns/a/.style={column type=l},
columns/b/.style={column type=p{1cm}},
]{file.csv}
```
The problem is with `=p{1cm}`. We can fix this by *fine tuning* the script to ensure that it searches for `NamedGroupingBracesBrackets` which follow equals symbols:

localSettings.yaml
-
```yaml
fineTuning:
    NamedGroupingBracesBrackets:
      follow: '\h|\R|\{|\[|\$|\)|\(|='
```
and run
```
latexindent.pl -l myfile.tex
```
then the output is
```tex
\pgfplotstabletypeset[
	col sep=tab,
	string type,
	header=true,
	columns={a,b,c,d,e,f},
	columns/a/.style={column type=l},
	columns/b/.style={column type=p{1cm}},
]{file.csv}
```

**Comment by bersbersbers** [comment]
Thank you - this looks like magic to me! Also, I must admit I still cannot draw the line between faulty default behavior (aka a bug) and a user-configurable feature. Please let me know if I should invest more effort into solving questions on my own.

Any additional hint for
```
\pgfplotstabletypeset[
    begin table=\begin{table},
    end table=\end{table},
]{file.csv}
```

which results in
```
\pgfplotstabletypeset[
    begin table=\begin{table},
        end table=\end{table},
]{file.csv}
```
?

**Comment by cmhughes** [comment]
Thanks for this. Do feel free to post here if you can't find the answer in the documentation :)

For your other question, have you seen https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html#lst-motivatepreamblecommandsbeforeenvironments
