### ISSUE TITLE
Curly braces and commas confuse \caption

### ISSUE THREAD

**Issue by bersbersbers** [cmhughes/latexindent.pl#238]
This is a file that is not changed by `latexindent`. In summary, from this limited set of experiments, curly braces seem to add indentation and commas seem to fix that. And slashes (as well as underscores, not shown here) completely remove indentation.

```
\begin{figure}
	% 1 indent (as expected)
	\caption{Therefore
		xyz[i]}

	% 2 indents
	\caption{Therefore
			{xyz[i]}} % curly braces --> 1 additional indent

	% 1 indent again
	\caption{Therefore, % note the comma (fixes things here)
		{xyz[i]}}

	% 0 indents
	\caption{Therefore
	{x/z[i]}} % note the slash

	% 0 indents
	\caption{Therefore, % note the comma (does not fix things)
	{x/z[i]}}

	% 0 indents
	\caption{Therefore,
	x/z[i]} % note no curly braces

	% 0 indents
	\caption{Therefore,
	\texttt{x/z[i]}}
\end{figure}
```

**Comment by cmhughes** [comment]
Could you provide what your expected/desired output is?

**Comment by bersbersbers** [comment]
I think I would expect 1 indent for all examples, but I am ready to be convinced overwise ;)

**Comment by cmhughes** [comment]
Can you try the following settings? I can't test them at the moment, but it's the first thing I would try:

```yaml
fineTuning:
    NamedGroupingBracesBrackets:
      follow: '\h|\R|\{|\[|\$|\|\/
```

**Comment by bersbersbers** [comment]
> ```yaml
> fineTuning:
>     NamedGroupingBracesBrackets:
>       follow: '\h|\R|\{|\[|\$|\|\/
> ```

This looks somewhat broken near the end. Considering that the default value is `\h|\R|\{|\[|\$|\)|\(`, I understood this to be 
```yaml
fineTuning:
    NamedGroupingBracesBrackets:
        follow: '\h|\R|\{|\[|\$|\)|\(|\/'
```
and this seems to work fine - thanks!

I looked through the manual again to see what `NamedGroupingBracesBrackets` does exactly, and it seems it's a code block that represents elements such as `node[attribute]`. My misunderstanding (for a while now) was that I understood `follow` as a set of allowed *initial* characters allowed to start this code block (`follow` = "following one of these characters"), while it seems to be the set of characters allowed to compose the complete `[attribute]` part (`follow` = "all that follows"). Now it does make sense to me that adding special characters such as `=` (see #237) and `/` to this list can fix these issues - thanks for pointing me at it again.

**Comment by cmhughes** [comment]
> follow as a set of allowed initial characters allowed to start this code block (follow = "following one of these characters")

Yes, I would agree with this. 

I'm exploring a new approach at the moment which I hope will make all of this a little easier, but for the moment, I'm glad you have a solution :)
