### ISSUE TITLE
nested environments, etc.

### ISSUE THREAD

**Issue by heptadecagon** [cmhughes/latexindent.pl#24]
Hello,

Back in February, I wrote the TextMate list when latexindent was added to it. I use LaTeX Tidy often, TextMate's default LaTeX formatter, and found that latexindent was formatting documents much differently, and in a way that I think might not have been intended. I'm not sure if these issues have been dealt with or brought up already, but I thought I would bring them up here. (I think issue #22 might be related, but I think the text below might consider a little more.)

Thanks!
#### This is what I wrote:

Although latexindent nicely formats align environments and matrices, some of the automation available in latex tidy seems to have been lost.

For example, consider the following:

``` latex
\begin{lem}
    \label{1.19:lem1}
    \[ \left\{ 
    \begin{matrix}
        p \in \al\\
        q \notin \al 
    \end{matrix}
    \right\}\implies p < q.\]
\end{lem}
```

which was indented by latex tidy. Latexindent now indents this as:

``` latex
\begin{lem}\label{1.19:lem1} 
    \[ \left\{      
        \begin{matrix}
            p \in \al    \\
            q \notin \al 
        \end{matrix}
        \right\} 
        \implies p < q.\]
        \end{lem}
```

If I move the last `\]` to the next line, latexindent indents this as

``` latex
\begin{lem}\label{1.19:lem1} 
    \[ \left\{      
        \begin{matrix}
            p \in \al    \\
            q \notin \al 
        \end{matrix}
        \right\} 
        \implies p < q.
    \]
\end{lem}
```

which looks better, but means that I now have to format my files according to latexindent's rules for it to work correctly. Somehow, this seems to defeat the purpose of an automatic text formatter. The pattern in the example is repeated often in documents of mine thousands of lines long and so, when this behavior of latexindent cascades, it causes lines that should not be indented, to be indented. For example, the following was formatted by latexindent:

``` latex
\begin{lem}\label{xyz} 
    \[ \left\{      
        \begin{matrix}
            p \in \al    \\
            q \notin \al 
        \end{matrix}
        \right\} 
        \implies p < q.\]
        \end{lem}

        This text should be at the beginning of the line.

        \begin{lem}\label{xyz} 
            \[ \left\{      
                \begin{matrix}
                    p \in \al    \\
                    q \notin \al 
                \end{matrix}
                \right\} 
                \implies p < q.\]
                \end{lem}
```

Latex tidy would have had no problem with this. Documents of mine tend to consist of environments nested several levels deep, (which is why latex tidy is important to me) and now the test copy on which I tried latexindent has text indented off the screen. Other examples of unexpected behavior, which might not be a complete list... :

after `\documentclass{...}` latexindent does not adjust indentation, and so

``` latex
\documentclass{article}

\usepackage{...}

     \usepackage{...}

            \usepackage{...}
```

is left untouched. Latex tidy would have brought them to the beginning of the line.

Latexindent does not seem to put text inside `\[ \]` on a separate line, whereas latex tidy did, and so,

``` latex
asdadfa \[ sdfada \] asdfasdfa
```

would have been changed to

``` latex
asdadfa
\[ sdfada \]
asdfasdfa
```

Latexindent leaves it unchanged.

It is the same with environments:

``` latex
\begin{abc} jkl \end{abc}
```

would have been changed to

``` latex
\begin{abc}
   this text would be indented.
\end{abc}
```

but latexindent leaves it untouched. 

It also doesn't compress multiple blank lines. In summary, latex tidy could take almost any mess I typed and put it in the right place.

**Comment by cmhughes** [comment]
Hi heptadecagon,
Thanks for writing, and for providing some useful test cases. 

I think that, at the moment, there is quite a difference between `latexindent` and `latex tidy` (with which I am not familiar). My goal with `latexindent` was to provide a script that *indents* code that is otherwise in the format that the user has already specified. The current version has no intention to add or remove lines. 

Having said that, I think that it would be useful to have features like you describe. It should be possible to implement it, but I'm not sure how long that (and the associated testing) will take :) For the moment, I'll label this issue as an enhancement, and report back with any updates. Development is fairly slow as I don't have much time at the moment, but I consider this upgrade and the issue you linked to as my next `latexindent`-based priority :)

Best
Chris

**Comment by heptadecagon** [comment]
Hi Chris, my apologies for replying late, and for misinterpreting the purpose of ``latexindent``. I had thought it was intended to be a complete latex formatter. ``latex tidy`` does indentation, compresses multiple blank lines, puts ``\begin{..} \end{...}`` on their own lines, etc. ``latexindent`` seemed to do some of this, and also formatted tables and matrices nicely. Somehow I think issue #10 fixed the indentation problem I mentioned. I keep TeX updated using TeXlive, but it is possible I don't have the latest version.

Of course, no rush! I am quite happy with ``latex tidy``. I thought I might contribute possible bug reports and feature requests. In any case, thank you for your reply!

**Comment by cmhughes** [comment]
Just to let you know that I'm working on a completely new implementation of the script; early signs are that it is far more powerful than my original approach. You can see the work on this branch: https://github.com/cmhughes/latexindent.pl/tree/object-oriented-approach

I'm having to re-build it completely, so it'll take a while. Fingers crossed I'll be able to implement the features you described above. Watch this space!

**Comment by cmhughes** [comment]
As of https://github.com/cmhughes/latexindent.pl/commit/7e975c819de6a8e4c10174068f5ec68e6fa7f5e2, all of the features you describe (and more!) are implemented. 

See https://github.com/cmhughes/latexindent.pl/tree/object-oriented-approach/test-cases/specials and in particular `heptadecagon*.tex`. 

Almost all of the linebreak decisions can be customised; as of `v3.0` (not yet released), `latexindent` can add and remove line breaks, condense line breaks, add comment symbols, in addition to indenting code blocks a lot more robustly. I won't go into the details of how to customise the decisions in this thread, but once v3.0 is ready to go, the documentation should detail it. I'm hopeful to release `v3.0` early in 2017.

Thanks again for writing, this issue has been a great motivator in my new development push :)

**Comment by cmhughes** [comment]
Resolved at https://github.com/cmhughes/latexindent.pl/pull/56
