### ISSUE TITLE
How about formating only part of the document?

### ISSUE THREAD

**Issue by newptcai** [cmhughes/latexindent.pl#247]
If I am collaborating with others, they may have a different style. So I would like to only to format the part I am working on.

[One idea](https://github.com/Chiel92/vim-autoformat#ranged-definitions) would be to add a range argument, which takes two numbers as input, the first is the first line of the range to format and the second is the last line to format.

So maybe we can write
```
lateindent.pl --range 3 10 test.tex
```
to format only line 3 to 10 in test.tex

**Comment by cmhughes** [comment]
This seems reasonable but I'm afraid I don't have capacity for this at the moment, maybe in the future. There are already a lot of things that people want that are ahead of this. Apoloe

**Comment by cmhughes** [comment]
I'm sorry for not being able to consider this earlier this year, it came at a very intense time and there was a flurry of issues.

I'm happy to explore this now, so am reopening it.

Please expect to see followup feedback/questions from me on this thread.

For my reference : https://metacpan.org/release/JV/Getopt-Long-2.38/view/lib/Getopt/Long.pm#Options_with_multiple_values, particularly the example about coordinates.

**Comment by zeertzjq** [comment]
Maybe it can be two arguments `--range-start` and `--range-end` instead.

**Comment by cmhughes** [comment]
Possibly! I'm hoping to get to this over the next few weeks, and will let
you know :)

**Comment by cmhughes** [comment]
@newptcai I'm hoping to get to this soon, so keep an eye on this thread for updates. Hopefully what I've proposed above sounds reasonable :)

**Comment by newptcai** [comment]
@cmhughes I mostly want to use this with vim, or more specifically [vim-autofmt](https://devhub.io/repos/Chiel92-vim-autoformat) plugin. It allows me to select a few lines in vim, and send it to a formatter. So one range is good enough.

**Comment by cmhughes** [comment]
As of https://github.com/cmhughes/latexindent.pl/commit/4d0437d1c0cf8fbd3e2d5704ab3ee43523838d36 I've made some progress on this. 

It's still in development, so it is on its own branch (https://github.com/cmhughes/latexindent.pl/tree/feature/line-switch). I've got more work to do on it, but you're welcome to pull from that branch if you want to see early versions. 

I hope to finish this within the next few weeks :)

**Comment by cmhughes** [comment]
As of https://github.com/cmhughes/latexindent.pl/commit/1d292dc3cb58fd82016b610eef7a480711b88e03 this is implemented :) 

Have a look at the below, and feel free to pull from `develop` branch, and let me know. I'm planning to get this released soon :) Thanks for your help!

--lines switch available syntax
-
* line range, as in \texttt{--lines 3-7};
* single line, as in \texttt{--lines 5};
* multiple line ranges separated by commas, as in \texttt{--lines 3-5,8-10};
* negated line ranges, as in --lines !3-5 which translates to --lines 1-2,6-N, where N is the number of lines in your file;

demonstration 1
-
Starting with 

```tex
here is a nested test
\begin{one}
		first block, second line
		first block, third line
		first block, fourth line
	\begin{two}
		second block, first line
		second block, second line
		second block, third line
		second block, fourth line
	\end{two}
\end{one}
```
and running 
```
latexindent.pl --lines 3-5 myfile.tex
```
gives
```
here is a nested test
\begin{one}
first block, second line
first block, third line
first block, fourth line
	\begin{two}
		second block, first line
		second block, second line
		second block, third line
		second block, fourth line
	\end{two}
\end{one}
```

demonstration 2
-
Running
```
latexindent.pl --lines 3-5,8-10 myfile.tex
```
gives
```
here is a nested test
\begin{one}
first block, second line
first block, third line
first block, fourth line
	\begin{two}
		second block, first line
second block, second line
second block, third line
second block, fourth line
	\end{two}
\end{one}
```

**Comment by newptcai** [comment]
Wow. Thanks. This could really useful not just for tex but also for writing markdown in latex.
I will check it out.

**Comment by cmhughes** [comment]
Implemented as of https://github.com/cmhughes/latexindent.pl/releases/tag/V3.12 :)

Uploaded to ctan; you should be able to [update your distribution](https://tex.stackexchange.com/questions/55437/how-do-i-update-my-tex-distribution) and receive this update within the next 24 hours or so.

Thanks for your help!

**Comment by newptcai** [comment]
I tried this file
~~~
\documentclass[11pt]{article}

\begin{document}

here is a nested test
\begin{one}
first block, second line
first block, third line
first block, fourth line
	\begin{two}
		second block, first line
second block, second line
second block, third line
second block, fourth line
	\end{two}
\end{one}

\end{document}
~~~
with command
~~~
latexindent -y="defaultIndent:' '" --lines 14-20 test.tex 
~~~
Nothing changes in the doc. I am using version 3.13 in texlive 2021.

**Comment by newptcai** [comment]
It seems that I cannot re-open this issue. :slightly_frowning_face:

**Comment by cmhughes** [comment]
How many lines does the document have?

You can feel free to open a new issue, using the template.

**Comment by newptcai** [comment]
I see! Sorry I was in a rush when tested it. It works perfectly.

**Comment by grwlf** [comment]
Hi. Is it possible to make `latexindent --lines X-Y` to honor the start indentation of the first word on line X and only change the indentation of subsequent words ?

**Comment by cmhughes** [comment]
Specific example please, before and after.

**Comment by grwlf** [comment]
Here is the example
```tex
\begin{document}
\textbf{
  \begin{itemize}
\item This paragraph is not correctly indented. In order to fix it, I
open the editor (Vim), select the current block, in this case - the itemize
block, and call the "Indent the selection" function which internally calls
\texttt{latexindent --lines 3-9}. I'd like it to assume that the start of
the block is indented correclty, and only it's body needs adjustments.
  \end{itemize}
  Instead, I get the whole block shifted towards the column 0, ignoring the
  fact that it resides inside textbf tag.
}
\end{document}
```

As a result of `cat test.tex | latexindent --line 3-9` , I get

```tex
\begin{document}
\textbf{
\begin{itemize}
        \item This paragraph is not correctly indented. In order to fix it, I
              open the editor (Vim), select the current block, in this case - the itemize
              block, and call the "Indent the selection" function which internally calls
              \texttt{latexindent --lines 3-9}. I'd like it to assume that the start of
              the block is indented correclty, and only it's body needs adjustments.
\end{itemize}
  Instead, I get the whole block shifted towards the column 0, ignoring the
  fact that it resides inside textbf tag.
}
\end{document}
```

which is not what I want. Instead, I'd like `latexindent` to assume that the first word of the selection, namely `\begin{itemize}` is indented correctly. Having this knowledge, I'd like it to calculate the rest of the indentation and output something like

```tex
\begin{document}
\textbf{
  \begin{itemize}
    \item This paragraph is not correctly indented. In order to fix it, I
          open the editor (Vim), select the current block, in this case - the
          itemize block, and call the "Indent the selection" function which
          internally calls \texttt{latexindent --lines 3-9}. I'd like it to
          assume that the start of the block is indented correclty, and only
          it's body needs adjustments.
  \end{itemize}
  Instead, I get the whole block shifted towards the column 0, ignoring the
  fact that it resides inside textbf tag.
}
\end{document}
```
As far as I understand, `latexindent` could have remembered the original indentation of the first word and add it to every line it touches.

**Comment by cmhughes** [comment]
Thanks for the example. This is not possible; feel free to look into it, the file you'd need to start with is `LatexIndent/Lines.pm` :)

**Comment by grwlf** [comment]
> Thanks for the example. This is not possible; feel free to look into it, the file you'd need to start with is `LatexIndent/Lines.pm` :)

Nope, not now( My motivation is not that strong, plus I'm not familiar with perl..
