### ISSUE TITLE
Incorrect indentation of `\setlength` within `list` environment

### ISSUE THREAD

**Issue by alexreg** [cmhughes/latexindent.pl#249]
original .tex code
--
```latex
\begin{list}{}{%
	\setlength{\itemsep}{0em}%
	\setlength{\parsep}{0.5em}%
}%
	foo
\end{list}%
```

yaml settings
--
none

desired or expected output
--
```latex
\begin{list}{}{%
	\setlength{\itemsep}{0em}%
	\setlength{\parsep}{0.5em}%
}%
	foo
\end{list}%
```
(i.e., same as original)
or
```latex
\begin{list}{}{%
		\setlength{\itemsep}{0em}%
		\setlength{\parsep}{0.5em}%
	}%
	foo
\end{list}%
```
(also acceptable to me, I suppose)

actual output
--
```latex
\begin{list}{}{%
	\setlength{\itemsep}{0em}%
	      \setlength{\parsep}{0.5em}%
	      }%
	      foo
\end{list}%
```

**Comment by cmhughes** [comment]
Thanks for this.

I think this is a bug with the `item` routine. The problem is the command `\itemsep` which contains `\item` which is within `itemNames` and so used by the look for items routine. 

Until I can provide a more permanent fix, the current settings give your desired output:
```yaml
specialBeginEnd:
    itemsep:
        begin: '\\item'
        end: 'sep'
        lookForThis: 'verbatim'
```

**Comment by alexreg** [comment]
Ah, I see. I thought it was something to do with the name `itemsep`, yeah. Thanks for the workaround.

**Comment by cmhughes** [comment]
Thanks, this is resolved as of https://github.com/cmhughes/latexindent.pl/commit/333b01397b433762bb2aa5744c20972462f0c372. It'll be part of the next minor release, hopefully won't be long.

In the meantime, you can either grab a copy of the develop branch, or if you'd prefer, the only file to be updated is `LatexIndent/Item.pm`

**Comment by alexreg** [comment]
Thanks, that's great.

**Comment by cmhughes** [comment]
Resolved as of https://github.com/cmhughes/latexindent.pl/releases/tag/V3.9 and uploaded to ctan.
