### ISSUE TITLE
Only processes first file on command line

### ISSUE THREAD

**Issue by alexreg** [cmhughes/latexindent.pl#253]
Running, e.g., `latexindent -s -w file1.tex file2.tex file3.tex` seems to only process `file1.tex`.

**Comment by cmhughes** [comment]
Yes, that is intended.

**Comment by alexreg** [comment]
Oh right, how come? Is it the `-w` option specifically that does that? Everything in the `--help` output suggests the command is always capable of processing multiple files, unless I missed something.

**Comment by cmhughes** [comment]
Can you point to the specific part of the documentation that says the
script cn operate on multiple files?

**Comment by alexreg** [comment]
Sorry, my mistake! I misread `[file][.tex|.sty|.cls|.bib|...]` as `[file][.tex|.sty|.cls|.bib]...`.
