### ISSUE TITLE
Update help text for new settings filenames

### ISSUE THREAD

**Issue by alexreg** [cmhughes/latexindent.pl#255]
Small thing here. Currently, the help text for v3.9 displays:
```
      -l, --local[=myyaml.yaml]
          use localSettings.yaml (assuming it exists in the directory of your file, 
          or in the current working directory); alternatively, use myyaml.yaml, if it exists; 
          sample usage:
                latexindent.pl -l some.yaml myfile.tex 
                latexindent.pl -l=another.yaml myfile.tex 
                latexindent.pl -l=some.yaml,another.yaml myfile.tex 
```

This should presumably be updated to reflect that it looks for files of other names too (four in total) in those directories.

**Comment by cmhughes** [comment]
Many thanks. I'll get to this, but if you feel like doing it, it's Latexindent /LogFile.pm that needs changing. All pull requests to develop branch :)

**Comment by alexreg** [comment]
Okay, good to know, thanks!

**Comment by cmhughes** [comment]
Resolved as of https://github.com/cmhughes/latexindent.pl/pull/261

**Comment by cmhughes** [comment]
Resolved as of https://github.com/cmhughes/latexindent.pl/pull/262, upload to ctan imminent.
