### ISSUE TITLE
Yaml key case sensitive 

### ISSUE THREAD

**Issue by cmhughes** [cmhughes/latexindent.pl#258]
Need to resolve case sensitive of yaml keys, raised in https://github.com/cmhughes/latexindent.pl/issues/254

Outline : compare lower case version of key to lower case version of read-in key.

**Comment by cmhughes** [comment]
Perhaps a new key called something like

YamlCaseSensitive

Which can be 0/1....?

If 1, users could specify, for example, MyYamlKey and also myyamlkey. In this case, users would have to commit to using the names given in defaultSettings.yaml 

If 0, then MyYamlKey and myyamlkey would be the same thing. Users would only have to have the names as in defaultSettings.yaml but the case wouldn't matter.

**Comment by alexreg** [comment]
Yes, this is what I was getting at. The canonical form for `NamedGroupingBracesBrackets` should probably be `namedGroupingBracesBrackets` everywhere, for consistency. Personally, I'm not bothered if latexindent.pl is always case-insensitive to settings, but adding an option like this is also reasonable (with a default of case-insensitive).

**Comment by cmhughes** [comment]
Great, thanks for confirming :)

**Comment by cmhughes** [comment]
Needs confirmation in `-y` switch

**Comment by alexreg** [comment]
> Needs confirmation in `-y` switch

What do you mean?

**Comment by cmhughes** [comment]
Apologies, this is a note to myself to make sure that any tests are performed on the `-y` switch as well.

**Comment by cmhughes** [comment]
An update on this:

1. as of https://github.com/cmhughes/latexindent.pl/commit/d4402714f01a78286a5df68f3493c2d5e2a9c5d5, `defaultSettings.yaml` now has changed to fineTuning: namedGroupingBracesBrackets to ensure
consistency. Note that `LatexIndent/NamedGroupingBracesBrackets.pm` performs a check for both casings to ensure backwards compatibility. That is, `fineTuning: NamedGroupingBracesBrackets` is still supported. If we ever get to V4, then this check will be removed, and only `fineTuning: namedGroupingBracesBrackets` will be supported.
2. I've begun exploring having a case-insensitive yaml key in https://github.com/cmhughes/latexindent.pl/tree/yaml-case-sensitive-key. It's not clear to me if this is a good feature to have or not; on the one hand, allowing greater flexibility for users might be desirable, but on the other hand it means that, for example, if a user were to set YAML keys as case *in*sensitive, then they if a user specifies the following, for example, 
```yaml
verbatimEnvironments:
    verbatim: 1
    Verbatim: 1
```
then only the `verbatim` environment would be verbatim, and the `Verbatim` environment would not be. I'm unsure about this, hence the separate branch.

**Comment by alexreg** [comment]
@cmhughes Sounds great. I'm not sure about #2 either... does the YAML standard itself provide any guidelines on this?

**Comment by cmhughes** [comment]
I'm going to label this as implemented; in reference to the above, this means that point 1 has been implemented. Point 2 might be revisited in future.

Resolved as of https://github.com/cmhughes/latexindent.pl/pull/262, upload to ctan imminent.

**Comment by cmhughes** [comment]
@alexreg I've done some searches for yaml case insensitive, but no luck so far.

I might revisit it in future. For the moment, the issue you originally highlighted is resolved though :)

**Comment by alexreg** [comment]
@cmhughes Yep, that's more than good enough for now, thanks. I would probably opt for general case-insensitivity in the future, since YAML leaves it unspecified, but  it doesn't bother me too much either way.

**Comment by cmhughes** [comment]
Great, many thanks :)

and did you notice you're listed as a contributor now too? :) thanks for
the help!

**Comment by alexreg** [comment]
> and did you notice you're listed as a contributor now too? :) thanks for the help!

I noticed you updated the file but didn't actually check. Appreciate it! I mean, I'm not submitting issues or PRs for the kudos, but it's definitely nice to have a friendly and proactive maintainer to work with. :-)
