### ISSUE TITLE
Please update URL to reference [2]: arara

### ISSUE THREAD

**Issue by kleinbottle** [cmhughes/latexindent.pl#259]
anything else
--
https://github.com/islandoftex/arara

**Comment by cmhughes** [comment]
Thanks!

**Comment by cmhughes** [comment]
I'll get to this, but if you feel like doing it then it's documentation /contributors.bib that needs changing. All pull requests to develop branch :)

**Comment by cmhughes** [comment]
Resolved as of https://github.com/cmhughes/latexindent.pl/pull/262, upload to ctan imminent.
