### ISSUE TITLE
How to disable align of `\\` in align environment?

### ISSUE THREAD

**Issue by vanabel** [cmhughes/latexindent.pl#26]
I have some code as
```
\begin{align*}
a&=b+c\\
c&=d\\
\end{align*}
```
it will be indent to:
```
\begin{align*}
	a & =b+c \\
	c & =d   \\
\end{align*}
```
how to delte the space before `\\`, since when my formula is long, this will take a lot of space, and make my formula looks ugly. So is there a switch such that it looks like
```
\begin{align*}
	a & =b+c\\
	c & =d\\
\end{align*}
```

**Comment by cmhughes** [comment]
Thanks for the suggestion! This should be ok to implement as a switch; I'll label this as an enhancement and get back to you in the future :) Development is kind of slow at the moment as I have a number of other projects.

**Comment by schmimae** [comment]
Hello there, thanks for developing! I just want to add to this. It looks especially strange if you have something like

````\begin{align*}
	CCI_n          & = \frac{p_n-SMA(p_n)}{0.015 \cdot \sigma(p_n)}                                                                            \\
	\textrm{wobei} & n = \textrm{Perioden, i.\,d.\,R. 20};\p_n = \textrm{Typischer Preis/Kurs};\ SMA(p_n) = \textrm{SMA der typischen Preise}; \\
	               & \sigma(p_n) = \textrm{Standardabweichung}                                                                                 \\
\end{align*}````

**Comment by cmhughes** [comment]
@schmimae thanks, noted! :)

**Comment by cmhughes** [comment]
Thanks again for suggesting this feature. 

I have implemented it at https://github.com/cmhughes/latexindent.pl/commit/057e8f1a26974750a68b5b3e871c84b546a11302. Full details are in the documentation, but it roughly looks like this:

```
lookForAlignDelims:
   tabular: 
      delims: 1
      alignDoubleBackSlash: 1
      spacesBeforeDoubleBackSlash: 2
   tabularx:
      delims: 1
   longtable: 1
```

You can now specify a 'basic' and an 'advanced' version of any field in `lookForAlignDelims`. Specifying `alignDoubleBlackSlash: 0` turns off alignment of `\\`. You can also, optionally, choose to add spaces before `\\` using `spacesBeforeDoubleBackSlash`.

I hope this is similar to what you had in mind, let me know if there are any tweaks :)
