### ISSUE TITLE
User-profile path does not support Chinese

### ISSUE THREAD

**Issue by qiancy98** [cmhughes/latexindent.pl#263]
Please provide the following when posting an issue:

original .tex code
--
*Does not relate to this*
*An empty file is OK*

yaml settings
--
`C:\Users\QianCY\indentconfig.yaml`
```yaml
# Paths to user settings for latexindent.pl
#
# Note that the settings will be read in the order you
# specify here- each successive settings file will overwrite
# the variables that you specify
paths:
- D:\其他网盘\latexindent.yaml
```
`D:\其他网盘\latexindent.yaml`
```yaml
#  verbatim environments specified 
#  in this field will not be changed at all!
verbatimEnvironments:
    tikzpicture: 1

# name of code blocks that should have their body aligned at ampersand delimiters
lookForAlignDelims:
   align: 
      delims: 1
      alignDoubleBackSlash: 0
   align*: 
      delims: 1
      alignDoubleBackSlash: 0

# if you have indent rules for particular code blocks
# then you can populate them in indentRules; for example, you might just want 
# to use a space " " or maybe a double tab "\t\t"
indentRules:
   item: "\t"
```

actual/given output
--
*Does not relate to this*

desired or expected output
--
It should not warn in the log file, as I have provided the `D:\其他网盘\latexindent.yaml` file.
It should have used the settings in the `D:\其他网盘\latexindent.yaml` file as well, but it does not use it actually.

log file
--
command: `latexindent.exe '.\notes of sparsity.tex'-o=output.tex -s`
File: `indent.log`
```log
INFO:  latexindent.pl version 3.9.1, 2021-03-21, a script to indent .tex files
       latexindent.pl lives here: C:/Users/QianCY/AppData/Local/Programs/MiKTeX/scripts/latexindent/
       Fri Mar 26 23:11:11 2021
       Filename: .\notes of sparsity.tex
INFO:  Processing switches:
       -s|--silent: Silent mode active (you have used either -s or --silent)
       -o|--outputfile: output to file
INFO:  Directory for backup files and indent.log: .
INFO:  Perl modules are being loaded from the following directories:
       C:/Strawberry/perl/lib/FindBin.pm
       C:/Strawberry/perl/vendor/lib/YAML/Tiny.pm
       C:/Strawberry/perl/lib/File/Copy.pm
       C:/Strawberry/perl/lib/File/Basename.pm
       C:/Strawberry/perl/lib/Getopt/Long.pm
       C:/Strawberry/perl/vendor/lib/File/HomeDir.pm
       C:/Strawberry/perl/vendor/lib/Unicode/GCString.pm
INFO:  Latex Indent perl modules are being loaded from, for example:
       C:/Users/QianCY/AppData/Local/Programs/MiKTeX/scripts/latexindent/LatexIndent/Document.pm
INFO:  YAML settings read: defaultSettings.yaml
        Reading defaultSettings.yaml from C:/Users/QianCY/AppData/Local/Programs/MiKTeX/scripts/latexindent/defaultSettings.yaml
INFO:  YAML settings read: indentconfig.yaml or .indentconfig.yaml
       Reading path information from C:\Users\QianCY/indentconfig.yaml
       (Alternatively C:\Users\QianCY/.indentconfig.yaml can be used)
       ---
       paths:
         - D:\其他网盘\latexindent.yaml

INFO:  YAML settings, reading from the following files:
WARN:  C:\Users\QianCY/indentconfig.yaml
       specifies D:\其他网盘\latexindent.yaml but this file does not exist - unable to read settings from this file
INFO:  -o switch active: output file check
       -o switch called with file name without extension: output
       Updated to output.tex as the file extension of the input file is tex
INFO:  Phase 1: searching for objects
INFO:  Phase 2: finding surrounding indentation
INFO:  Phase 3: indenting objects
INFO:  Phase 4: final indentation check
INFO:  Output routine:
       Outputting to file output.tex
       --------------
INFO:  Please direct all communication/issues to:
        https://github.com/cmhughes/latexindent.pl
```

anything else
--
My OS: `Windows 10 20H2 19042.867` (Chinese version, with text coding `GB2312`)
My latexindent.pl version: `3.9.1, 2021-03-21`

With some old version of latexindent.pl it would output to screen (not! log! file!)
```
Wide character in print at C:/Strawberry/perl/site/lib/Log/Dispatch/File.pm line 150.
Wide character in print at C:/Strawberry/perl/site/lib/Log/Dispatch/File.pm line 150.
```

**Comment by cmhughes** [comment]
Thanks for this. Do you have any idea how to fix this?

**Comment by cmhughes** [comment]
Does the script read yaml files with Chinese characters from the - l switch?

For example, does the following work:

latexindent - l 其他网盘 my file.tex

**Comment by cmhughes** [comment]
I've done some experiments with this on my *Linux* Ubuntu machine:

1. I created `/home/cmhughes/其他网盘/latexindent.yaml`
2. I added 
```yaml
paths:
- /home/cmhughes/其他网盘/latexindent.yaml
```
to my `.indentconfig.yaml`

Then my logfile looks as follows
```
INFO:  latexindent.pl version 3.9.1, 2021-03-21, a script to indent .tex files
       latexindent.pl lives here: /home/cmhughes/projects/latexindent/
       Sat Mar 27 07:38:52 2021
       Filename: cmh.tex
INFO:  Processing switches:
       -sl|--screenlog: log file will also be output to the screen
       -s|--silent: Silent mode active (you have used either -s or --silent)
       -l|--localSettings: Read localSettings YAML file
INFO:  Directory for backup files and indent.log: .
INFO:  Perl modules are being loaded from the following directories:
       /home/cmhughes/perl5/perlbrew/perls/perl-5.30.3/lib/5.30.3/FindBin.pm
       /home/cmhughes/perl5/perlbrew/perls/perl-5.30.3/lib/site_perl/5.30.3/YAML/Tiny.pm
       /home/cmhughes/perl5/perlbrew/perls/perl-5.30.3/lib/5.30.3/File/Copy.pm
       /home/cmhughes/perl5/perlbrew/perls/perl-5.30.3/lib/5.30.3/File/Basename.pm
       /home/cmhughes/perl5/perlbrew/perls/perl-5.30.3/lib/5.30.3/Getopt/Long.pm
       /home/cmhughes/perl5/perlbrew/perls/perl-5.30.3/lib/site_perl/5.30.3/File/HomeDir.pm
       /home/cmhughes/perl5/perlbrew/perls/perl-5.30.3/lib/site_perl/5.30.3/x86_64-linux/Unicode/GCString.pm
INFO:  Latex Indent perl modules are being loaded from, for example:
       /home/cmhughes/projects/latexindent/LatexIndent/Document.pm
INFO:  YAML settings read: defaultSettings.yaml
        Reading defaultSettings.yaml from /home/cmhughes/projects/latexindent/defaultSettings.yaml
INFO:  YAML settings read: indentconfig.yaml or .indentconfig.yaml
       Reading path information from /home/cmhughes/.indentconfig.yaml
       (Alternatively /home/cmhughes/indentconfig.yaml can be used)
       ---
       paths:
         - /home/cmhughes/其他网盘/latexindent.yaml

INFO:  YAML settings read: -l switch
       Adding å¶ä»ç½ç.yaml to YAML read paths
INFO:  YAML settings, reading from the following files:
       Reading USER settings from /home/cmhughes/其他网盘/latexindent.yaml
       ---
       defaultIndent: ' '
       fineTuning:
         keyEqualsValuesBracesBrackets:
           name: '[a-zA-Z@\*0-9_\/.\h:\#-]+?'

       Reading USER settings from å¶ä»ç½ç.yaml
       ---
       backupExtension: .bak

INFO:  Phase 1: searching for objects
INFO:  Phase 2: finding surrounding indentation
INFO:  Phase 3: indenting objects
INFO:  Phase 4: final indentation check
INFO:  Output routine:
       Not outputting to file; see -w and -o switches for more options.
       --------------
INFO:  Please direct all communication/issues to:
        https://github.com/cmhughes/latexindent.pl
```

I need to see if I can replicate this on a Windows machine.

**Comment by qiancy98** [comment]
(Sorry I'm newer to GitHub and I sent the notification emails to wrong address. As a result, it is until now that I found your replying.)

Thank you for your reminder! Do to historical reasons, actually Windows use local encoding for areas other than English-speaking countries. (This decision was made before the raising of UTF-8.)
This means that actually we use GB2312 encoding for Windows system (which is, I mean, the encoding of its file system) in China (for compatibility of old softwares), while we use UTF-8 for text files (which is the requirement of modern softwares, including XeLaTeX and Python).
It makes life more complex that some (but few) computers selled in China are encoded in UTF-8. Luckily, the Windows system knows how it is encoded.

Actually, when I am running `latexindent -l="D:\其他网盘\latexindent.yaml" ".\notes of sparsity.tex" -o=output.tex -s`, it does works, however the path is not correctly encoded in UTF-8 (`其他网盘` becomes `ÆäËûÍøÅÌ`):
```log
INFO:  latexindent.pl version 3.9.2, 2021-04-06, a script to indent .tex files
       latexindent.pl lives here: C:/Users/QianCY/AppData/Local/Programs/MiKTeX/scripts/latexindent/
       Wed Apr 28 14:10:02 2021
       Filename: .\notes of sparsity.tex
INFO:  Processing switches:
       -s|--silent: Silent mode active (you have used either -s or --silent)
       -l|--localSettings: Read localSettings YAML file
       -o|--outputfile: output to file
INFO:  Directory for backup files and indent.log: .
INFO:  Perl modules are being loaded from the following directories:
       C:/Strawberry/perl/lib/FindBin.pm
       C:/Strawberry/perl/vendor/lib/YAML/Tiny.pm
       C:/Strawberry/perl/lib/File/Copy.pm
       C:/Strawberry/perl/lib/File/Basename.pm
       C:/Strawberry/perl/lib/Getopt/Long.pm
       C:/Strawberry/perl/vendor/lib/File/HomeDir.pm
       C:/Strawberry/perl/vendor/lib/Unicode/GCString.pm
INFO:  Latex Indent perl modules are being loaded from, for example:
       C:/Users/QianCY/AppData/Local/Programs/MiKTeX/scripts/latexindent/LatexIndent/Document.pm
INFO:  YAML settings read: defaultSettings.yaml
        Reading defaultSettings.yaml from C:/Users/QianCY/AppData/Local/Programs/MiKTeX/scripts/latexindent/defaultSettings.yaml
INFO:  YAML settings read: indentconfig.yaml or .indentconfig.yaml
       Reading path information from C:\Users\QianCY/indentconfig.yaml
       (Alternatively C:\Users\QianCY/.indentconfig.yaml can be used)
       ---
       paths:
         - D:\其他网盘\latexindent.yaml

INFO:  YAML settings read: -l switch
       Adding D:\ÆäËûÍøÅÌ\latexindent.yaml to YAML read paths
INFO:  YAML settings, reading from the following files:
WARN:  C:\Users\QianCY/indentconfig.yaml
       specifies D:\其他网盘\latexindent.yaml but this file does not exist - unable to read settings from this file
       Reading USER settings from D:\ÆäËûÍøÅÌ\latexindent.yaml
       ---
       indentRules:
         item: "\t"
       lookForAlignDelims:
         align:
           alignDoubleBackSlash: '0'
           delims: '1'
         align*:
           alignDoubleBackSlash: '0'
           delims: '1'
         aligned:
           alignDoubleBackSlash: '0'
           delims: '1'
       verbatimEnvironments:
         tikzpicture: '1'

INFO:  -o switch active: output file check
       -o switch called with file name without extension: output
       Updated to output.tex as the file extension of the input file is tex
INFO:  Phase 1: searching for objects
INFO:  Phase 2: finding surrounding indentation
INFO:  Phase 3: indenting objects
INFO:  Phase 4: final indentation check
INFO:  Output routine:
       Outputting to file output.tex
       --------------
INFO:  Please direct all communication/issues to:
        https://github.com/cmhughes/latexindent.pl
```

I tried to change the encoding of the yaml file to GB2312, but I got an error complaining about the encoding. It seems that the yaml file is required to be encoded in UTF-8.

To fix this problem, I wonder if there is any Windows API that can transform a (UTF-8)-encoded string to a string having the same encoding with local filesystem (for my computer, it is GB2312).
> Some searching on Chinese website shows that, this may be closely related to two APIs `WideCharToMultiByte` and `MultiByteToWideChar`.

**Comment by cmhughes** [comment]
Thanks this looks like useful information. But I still don't know what to do with it....

Could you look at LatexIndent/GetYamlSettings.pm and see if you can fix it....?

**Comment by qiancy98** [comment]
Well, after a lot of searching I found that this has been heavily discussed by Chinese users for their "Hello World" programs. We have to transform the encoding of `$settings` at line 228.
However I do not have an idea how to handle it transparently to users...
For the following reasons:
- I do not know a way to detect the system encoding.
- Someone may change the default encoding.

For the second one, we can simply require them to specify their encoding.
But for the first one, I have no idea because some users are green hands to Windows.

- The best way I have come up is to tell them how to check their encoding. (I guess the users will search for methods when they get the warning.) (At least for Chinese users, I will write a blog for this.)
- Or maybe we can require them to select their regions (I cannot use the word country as China has not reunified now...) and tell users to use this if they do not know their encoding.
- Or, for the users that only specify their regions, we can try both the encoding for their regions and the UTF-8 encoding, and only select one of them if both exist.
- Or there is a transparent (but time-consuming) method: test all the possible encodings one by one till some encoding meets.

At least for me, I love the first idea.

---
A simple code to transform a string to `GB2312` is like this (I do not know what these `use` are for, and hence I will not change it nor comment on it.)
```perl
#!perl -w
use autodie;
use Encode;

my $file ="./测试.txt";
# We have to first decode utf-8 because perl do not use utf-8 in default.
# We can `use utf8;` to set utf-8 encoding into default.
$file = encode("gb2312", decode("utf-8", $file));
open my $in,'<',"$file";

while (<$in>){
print;
}
```
Since the standard encoding of cmd as well as powershell is the same as that of the file system, we do not need to transform it (if you are not interested in the log). (Maybe we can add such a sentence in log `standard input is encoded in ASCII`, or require a key to specify the encoding of input, only for logging.)

---
Here are two websites found in localization of Firefox:
https://developer.mozilla.org/en-US/docs/Web/Guide/Localizations_and_character_encodings
https://encoding.spec.whatwg.org/
which may be helpful to us. After all, I do not know what encodings there are worldwide.

**Comment by qiancy98** [comment]
Seems this is related to the package `Encode` and I am now looking at its documents. https://perldoc.perl.org/Encode

**Comment by cmhughes** [comment]
Great, thanks for looking at this. If you get a fix, do feel free to submit to the develop branch.

**Comment by cmhughes** [comment]
Any ideas on how to progress this? :)

**Comment by qiancy98** [comment]
```perl
use I18N::Langinfo qw(langinfo CODESET);
use Encode;
my $encoding = langinfo(CODESET());
my $encodingCanonicalName = find_encoding($encoding)->name;
$logger->info("*The system encoding is $encoding, or $encodingCanonicalName for the canonical name.");
```
Such code gives the output
```log
INFO:  The system encoding is ANSI_X3.4-1968, or ascii for the canonical name.
```
While my file system is encoded in GB2312. Hence I cannot solve this problem...
Can we add a switch telling the encoding where the default is UTF-8?

**Comment by qiancy98** [comment]
My raised pull: #273
It seems that I merged to a wrong branch?
(Sorry I have not ever dealed with more than one branch).

**Comment by cmhughes** [comment]
Thanks very much for looking at this :)

I'll study this soon, hopefully over the next few days and get back to you.

Thank you again!

**Comment by cmhughes** [comment]
Implemented as of https://github.com/cmhughes/latexindent.pl/pull/273

**Comment by cmhughes** [comment]
I've updated the documentation in https://github.com/cmhughes/latexindent.pl/commit/7be23989fa849cc711002676baa6b196cf9c26a8 

Does this look ok? Do let me know if you have anything to add/change for this :) Thanks again!

**Comment by qiancy98** [comment]
Thank you! It seems that your document is wonderful!

**Comment by cmhughes** [comment]
Resolved as of https://github.com/cmhughes/latexindent.pl/pull/278, upload to ctan to follow.
