### ISSUE TITLE
Unwanted alignment for mistakenly matched brackets.

### ISSUE THREAD

**Issue by uduse** [cmhughes/latexindent.pl#264]
Please provide the following when posting an issue:

original .tex code
--
```latex
\documentclass{article}

\begin{document}
This is an interval $[0, 100)$

Victim A
Victim B

Victim C

This is another interval $(100, 200]$
\end{document}

```
yaml settings
--
The default setting.

actual/given output
--
```latex
\documentclass{article}

\begin{document}
This is an interval $[0, 100)$

				Victim A
				Victim B

				Victim C

				This is another interval $(100, 200]$
\end{document}
```

desired or expected output
--
`latexindent` shouldn't change anything here.

question
--
What should I do with the setting to make `latexindent` ignore matching like this?

**Comment by cmhughes** [comment]
Thanks for this. Can you try

specialBeginEnd:
    specialBeforeCommand: 1

**Comment by uduse** [comment]
Yes, it works! Thank you!

Is this a bug? or there's no way for `latexindent` to always determine such cases correctly so users have to be careful?

**Comment by cmhughes** [comment]
Great!

No this isn't a bug as it is expected behaviour, although I appreciate it isn't ideal.

I'm trying to explore a new approach in which this behaviour wouldn't happen.

In the mean time I hope the above works for you.
