### ISSUE TITLE
Indenter gets stuck on specific input

### ISSUE THREAD

**Issue by jasonhan-vassar** [cmhughes/latexindent.pl#266]
Hi, so I just ran into this strange edge case where `latexindent.pl` gets stuck indenting anything containing the following lines. I don't know how long it goes on for, but it certainly goes on for more than 10 seconds so I am assuming it's an error worth reporting. I am using 3.9.1 with no extra settings. Can you reproduce this?

```LaTeX
%     %\begin{noindent}
%     %\end{noindent}
```

It can be anywhere among other content and still cause the script to choke:

```LaTeX
\begin{forest}
 parse tree
 [$\neg (\neg P \to (Q \lor R))$
  [$\neg P \to (Q \lor R)$
   [$\neg P$ [$P$]]
   [$Q \lor R$
    [$Q$]
    [$R$]
   ]
  ]
 ]
\end{forest}

%     %\begin{noindent}
%     %\end{noindent}

\begin{forest}
 parse tree
 [$\neg (\neg P \to (Q \lor R))$
  [$\neg P \to (Q \lor R)$
   [$\neg P$ [$P$]]
   [$Q \lor R$
    [$Q$]
    [$R$]
   ]
  ]
 ]
\end{forest}
```

**Comment by cmhughes** [comment]
Thanks for this. It's certainly a bug, as the script shouldn't hang/stall because of this. I've fixed it as of https://github.com/cmhughes/latexindent.pl/commit/ee33e426c2f00d49002914973885682b0fd520ab and will get a new release published to ctan, hopefully today.

Thanks again :)

**Comment by cmhughes** [comment]
Resolved as of https://github.com/cmhughes/latexindent.pl/releases/tag/V3.9.2 and uploaded to ctan :)
