### ISSUE TITLE
Allow `latexindent file.tex > file.tex`

### ISSUE THREAD

**Issue by thomasahle** [cmhughes/latexindent.pl#269]
Yesterday I wanted to indent some latex code, and I ran `latexindent file.tex`, which of course outputs the result to the terminal. Admittedly I didn't read the docs, but I then ran `latexindent file.tex > file.tex`, which I expected would replace `file.tex` with the indented version. Instead, it deleted my last hour of work.

actual/given output
--
My file `file.tex` ended up empty.

desired or expected output
--
I would expect the command to be similar to `latexindent -w file.tex`.

anything else
--
I know this isn't strictly necessary since the `-w` command exists, but it seems like it wouldn't hurt to allow the pipe version as well. If only as a way to help stupid people not lose their work.

**Comment by cmhughes** [comment]
Hello,
Thanks for this. 

I'm not sure that this is a problem with `latexindent.pl`. See, for example, the details within the following links:

- [https://superuser.com/questions/597244/why-does-redirecting-the-output-of-a-file-to-itself-produce-a-blank-file](https://superuser.com/questions/597244/why-does-redirecting-the-output-of-a-file-to-itself-produce-a-blank-file)
- https://unix.stackexchange.com/questions/185596/redirection-not-overwriting-file-but-just-producing-a-blank-one

If I've misunderstood this, please do let me know.
Best
Chris

**Comment by thomasahle** [comment]
I see. I expected this had to do with the buffering used by latexindent, but if the right hand side of `>` is evaluated before the left, I guess there is no way to work around it.

**Comment by cmhughes** [comment]
Yes, that's my understanding. 

I don't think this is particular to latexindent. 

But, if I'm wrong then please do let me know :)

**Comment by cmhughes** [comment]
I'm going to close this,  but do let me know if you have any follow-up on this.
