### ISSUE TITLE
\end{} indented on next level 

### ISSUE THREAD

**Issue by Tchiller** [cmhughes/latexindent.pl#27]
Please see my post here: http://tex.stackexchange.com/a/248171

I would have expected the `\end{tabular}` on the same indent as `\begin{tabular}{%`

I hope, this has not been reported yet. Thank you very much.

**Comment by cmhughes** [comment]
Yep, definitely a bug, thanks for reporting it :) Are you also known as `LaRiFaRi`?

I'll look into a fix during my next development push; apologies in advance, it might not be for a while... Thanks again!

**Comment by Tchiller** [comment]
Yes, I am :-)
Thanks for looking at it. And no hurry!

**Comment by cmhughes** [comment]
Thanks again for reporting this!

I believe that I have fixed it in https://github.com/cmhughes/latexindent.pl/commit/b5b0309dd4b0051e6d09abb646d989868f8745b5

See `success/table4.tex` for demonstration. Thanks again, and let me know if this doesn't fix it in the way you intended :)

I'm working on a few more fixes & features, and hope to release a new version in 2016.
