### ISSUE TITLE
Missing indent when path includes braces in tikz \graph

### ISSUE THREAD

**Issue by zeertzjq** [cmhughes/latexindent.pl#271]
Please provide the following when posting an issue:

original .tex code
--
```latex
\documentclass{article}
\begin{document}
\begin{tikzpicture}
  \graph {
    1 -> { 1, 2 };
  };
\end{tikzpicture}
\end{document}
```

yaml settings
--
3.9.3 default

actual/given output
--
```latex
\documentclass{article}
\begin{document}
\begin{tikzpicture}
	\graph {
	1 -> { 1, 2 };
	};
\end{tikzpicture}
\end{document}
```

desired or expected output
--
```latex
\documentclass{article}
\begin{document}
\begin{tikzpicture}
	\graph {
		1 -> { 1, 2 };
	};
\end{tikzpicture}
\end{document}
```

anything else
--
The problem doesn't occur if there are no braces in the path.

**Comment by cmhughes** [comment]
Hello, thanks for this. Can you take a look at https://latexindentpl.readthedocs.io/en/latest/sec-fine-tuning.html#lst-finetuning1-mod1 and see if that fixes it?

**Comment by zeertzjq** [comment]
I can't figure out what regex I have to set to `arguments:between` as literally everything can appear in `\graph`. I guess `arguments:between` is what can appear between `{` and `}`, but I'm not sure.

**Comment by zeertzjq** [comment]
BTW, why must noindent blocks be in comments?

**Comment by zeertzjq** [comment]
Well, I guess PGF/TikZ is hard for latexindent to parse anyway as it is a different langauge. I'll add `tikzpicture` to `verbatimEnvironments` currently.

**Comment by cmhughes** [comment]
Try starting with https://latexindentpl.readthedocs.io/en/latest/sec-fine-tuning.html#lst-fine-tuning1

**Comment by cmhughes** [comment]
Any luck with this?

**Comment by zeertzjq** [comment]
The following configuration seem to work:
```yaml
fineTuning:
  arguments:
    before: '(?:#\d\h*;?,?\/?)+|\<.*?\>|\-\-|\->|in'
```
The `in` makes indentation correct after `\foreach` ... `in`

**Comment by cmhughes** [comment]
Great, nicely done!
