### ISSUE TITLE
Can't build documentation in PDF

### ISSUE THREAD

**Issue by vonbrand** [cmhughes/latexindent.pl#272]
Fedora 34, texlive-2020.

```
make latexpdf PAPER=letter
```

stops with:

! Package inputenc Error: Unicode character ♠ (U+2660)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.7605 annotated key parts of the file using ♠
                                                , ♥, ◆ and ♣, these wi...```
```

**Comment by cmhughes** [comment]
You need to compile it with shell escape.
