### ISSUE TITLE
I want no indent for `multicols` environment

### ISSUE THREAD

**Issue by NeoFantom** [cmhughes/latexindent.pl#280]
Currently, contents in `multicols` are indented by one level. I don't want this. I've tried adding `multicols*: 1` to `noAdditionalIndent` in `defaultSettings.yaml` file, but won't work. How to do this correctly?

**Comment by cmhughes** [comment]
Please use the issue template, and I'll do my best to help :)

**Comment by cmhughes** [comment]
Please provide the following when posting an issue:

original .tex code
--
*Please paste your .tex code here*

yaml settings
--
*Please paste your YAML settings (if any) here*

actual/given output
--
*Please paste the output you receive here*

desired or expected output
--
*Please paste your desired/expected output here; that is, what do you want the output to look like*

anything else
--
*Please put any comments or anything else here :)*

**Comment by cmhughes** [comment]
Starting with
```tex
\begin{multicols*}
my text goes here

    my text goes here
  my text goes here
        my text goes here
\end{multicols*}
```
and using 

NeoFantom.yaml
-
```yaml
noAdditionalIndent:
    multicols*: 1
```
and running 
```
latexindent.pl -l NeoFantom.yaml myfile.tex
```
then I receive
```tex
\begin{multicols*}
my text goes here

my text goes here
my text goes here
my text goes here
\end{multicols*}
```
