### ISSUE TITLE
multi-line argument lists are not indented

### ISSUE THREAD

**Issue by SoongJr** [cmhughes/latexindent.pl#284]
original .tex code
--
```latex
\documentclass[%
       % draft=true,     % draft mode (no images, layout errors shown)
 draft=false,     % final mode
]{scrreprt} % Classes: scrartcl, scrreprt, scrbook\usepackage[ngerman]{babel}

\begin{document}
\end{document}
```

yaml settings
--
`-y="defaultIndent: '  '"`

actual/given output
--
unchanged output:
```latex
\documentclass[%
       % draft=true,     % draft mode (no images, layout errors shown)
 draft=false,     % final mode
]{scrreprt} % Classes: scrartcl, scrreprt, scrbook\usepackage[ngerman]{babel}

\begin{document}
\end{document}
```

desired or expected output
--
```latex
\documentclass[%
  % draft=true,     % draft mode (no images, layout errors shown)
  draft=false,     % final mode
]{scrreprt} % Classes: scrartcl, scrreprt, scrbook\usepackage[ngerman]{babel}

\begin{document}
\end{document}
```

anything else
--
This must have something to do with the `\begin{document}` statement, because as soon as I remove that I get the desired output:
```latex
\documentclass[%
  % draft=true,     % draft mode (no images, layout errors shown)
  draft=false,     % final mode
]{scrreprt} % Classes: scrartcl, scrreprt, scrbook\usepackage[ngerman]{babel}

% \begin{document}
\end{document}
```

**Comment by SoongJr** [comment]
I don't know why I only checked after creating the issue, but yes the docs say that indentation is supported, and the example given formats correctly for me:
```latex
\matrix [
1&2 &3\\
4&5&6]{
7&8 &9\\
10&11
}
```
```latex
\matrix [
  1 & 2 & 3 \\
  4 & 5 & 6]{
  7  & 8  & 9 \\
  10 & 11
}```

I also re-checked the example given and if I only have this in the file, it formats correctly, but if doesn't indent properly when it's in the actual file.
I have to check this on my side to find what's causing this, it must be something outside the command (apparently after it, because that's the first part of my file...)

**Comment by SoongJr** [comment]
Luckily I found something right away, issue text is updated with actual working example (nothing else in the file this time, I swear)

**Comment by cmhughes** [comment]
Hello, thanks for this.

Please see `indentPreamble` in https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html#filecontents-and-preamble

**Comment by SoongJr** [comment]
Thanks @cmhughes ! So it was just a matter of reading the manual, sorry 😅 Yes, indentPreamble is the setting I want. Would have felt more intuitive to have it enabled by default so only if your preamble _is_ tricky you can then disable it, but I can definitely see why you didn't want to introduce this kind of incompatibility with earlier versions 😉

**Comment by cmhughes** [comment]
Great, glad it worked!

Having it turned off by default feels safest to me :) you should feel encouraged to set up your own global configuration using indentconfig.yaml as in 
https://latexindentpl.readthedocs.io/en/latest/sec-indent-config-and-settings.html#indentconfig-yaml-and-indentconfig-yaml

All the best
Chris
