### ISSUE TITLE
surround delimiters for displayed math equation with line breaks

### ISSUE THREAD

**Issue by Konfekt** [cmhughes/latexindent.pl#293]
There is 

- the commit https://github.com/cmhughes/latexindent.pl/commit/697162f61a46ae7ffe52ff23ed23dca10a5682c7 to treat display math blocks as verbatim

and

- the instructions https://github.com/cmhughes/latexindent.pl/blob/7f581fa855f02a1f8aabfb86e6a354a984196162/documentation/sec-replacements.rst that shows how to replace them by `equation*` environments, and
- the documented YAML options `modifyLineBreaks:environments:equation*:'BeginStartsOnOwnLine: 1;BodyStartsOnOwnLine: 1;EndStartsOnOwnLine: 1;EndFinishesWithLineBreak: 1` 

to turn 

```tex
a \[ x \] b
```

into

```tex
a
\begin{equation*}
x
\end{equation*}
b
```

However, how to turn

```tex
a \[ x \] b
```

into

```tex
a
\[
x
\]
b
```

that is, how to surround the delimiters for a displayed math equation with line breaks?

**Comment by cmhughes** [comment]
Great, glad to hear it :) Thanks for the note about `betterFullStop`, it's
always good to have feedback and references.
