### ISSUE TITLE
The YAML parser cannot parse JSON code

### ISSUE THREAD

**Issue by poscat0x04** [cmhughes/latexindent.pl#309]
According to the spec, YAML is a superset of JSON, but the YAML parser used by latexindent.pl fails to parse valid JSON code.

yaml settings
--
.indentconfig.yaml:
```yaml
{ "paths": ["/some/path"] }
```

actual/given output
--
indent.log:
```term
INFO:  YAML settings read: indentconfig.yaml or .indentconfig.yaml
WARN:  The paths field cannot be read from /home/poscat/.indentconfig.yaml; this means it is either empty or contains invalid YAML
       See https://latexindentpl.readthedocs.io/en/latest/sec-indent-config-and-settings.html for an example
```

**Comment by cmhughes** [comment]
Thanks for this.

Latexindent.pl uses `yaml::tiny` from https://metacpan.org/pod/YAML::Tiny which

>  provides support for only a limited subset of YAML. But the subset supported contains most of the features for the more common uses of YAML.

I'd like to keep latexindent as lean as possible and do not intend to require the 'full' yaml unless mission critical.

I don't think it will be possible to read such files.

**Comment by poscat0x04** [comment]
Alright
