### ISSUE TITLE
Make latexindent completely do not create backup

### ISSUE THREAD

**Issue by flaviusbuffon** [cmhughes/latexindent.pl#313]
I want to make  latexindent completely do not create backup.

My situation is :

I am using format.nvim plugin in neovim.
It will create a tmp file , then format the tmp file and write tmp file content into original file.

So, that means i do not need latexindent create backup file for me.

```
latexindent -o
```
can't work, 
because it will create file named as the plugin's tmp file .

**Comment by cmhughes** [comment]
Hello,
Could you try

latexindent.pl -c /dev/null myfile.tex

This should use a null directory for the 'cruft' files, such as backups.

Otherwise

latexindent.pl -o myfile.tex myfile.tex

Will bypass the backup process.

Chris

/dev/null

/dev/null

**Comment by flaviusbuffon** [comment]
Sorry, when i using 
```
latexindent -c /dev/null main.tex
```
It appears 
```
FATAL Could not find directory /dev/null
```
latexindent version 
3.13.3

**Comment by cmhughes** [comment]
Try the - o switch as above.

Otherwise use the - c switch to direct the cruft files to another directory.

**Comment by cmhughes** [comment]
See https://latexindentpl.readthedocs.io/en/latest/sec-how-to-use.html#from-the-command-line about the - c switch

**Comment by flaviusbuffon** [comment]
Thanks for your help!
