### ISSUE TITLE
MiKTeX misses latexindent.exe

### ISSUE THREAD

**Issue by judober** [cmhughes/latexindent.pl#314]
It seems that MiKTeX does not include `latexindent.exe` for windows.

When I run `latexindent` from the command I get
```
Can't locate YAML/Tiny.pm in @INC (you may need to install the YAML::Tiny module)
```
and more. So the perl version is called.

I looked into the MiKTeX File-bundle and could not find the .exe as you can verify [here](https://miktex.org/packages/latexindent/files).

This is a discrepency to the manual of latexindent that states that the .exe should be provided by MiKTeX.
So I guess I have to install latexindent.exe manually?

Also: Thanks for this nice package 😃

**Comment by cmhughes** [comment]
Thanks for this.

I've tried fixing it before with the author of Miktex, apparently unsuccessfully. I'll try again.

**Comment by yorelog** [comment]
I find latexindent.exe is here `MiKTeX\miktex\bin\x64\latexindent.exe`

**Comment by judober** [comment]
I don't have the `bin` folder in my `user\AppData\Local\MiKTeX\miktex` (nor in `Roaming`). Did you install in admin mode? I installed MiKTeX only for my user.

**Comment by cmhughes** [comment]
@yorelog thanks for this :)

Is the version of `latexindent.exe` the stand alone executable file from this repository?

**Comment by cmhughes** [comment]
I've been in touch with the Miktex author. It looks like this behaviour cannot be changed.

Any ideas on how to improve the documentation are welcome! Let me know.

**Comment by cmhughes** [comment]
Maybe I should add the following to the documentation

https://tex.stackexchange.com/questions/577250/how-to-use-latexindent-on-windows?atw=1&s=09

**Comment by cmhughes** [comment]
Perhaps helpful 

https://tex.stackexchange.com/questions/628782/latexindent-fail-in-vscode-cant-locate-log-log4perl-pm?noredirect=1#comment1568492_628782

**Comment by cmhughes** [comment]
documentation updated as of https://github.com/cmhughes/latexindent.pl/commit/301d985b0a55d44c289441c0822f627f93bd4673. 

I'll label this as implemented for the moment. All contributions welcome to the `develop` branch.

**Comment by cmhughes** [comment]
resolved as of https://github.com/cmhughes/latexindent.pl/releases/tag/V3.14 upload to ctan imminent.
