### ISSUE TITLE
no indentation before headings

### ISSUE THREAD

**Issue by EngCat** [cmhughes/latexindent.pl#317]
Hi, I'm using the Version 3.13.3 of the script. I need a bit of help.

Can I remove the indentation only **before** headings (\part, \chapter, \section....)?

Thanks in advance.

**Comment by cmhughes** [comment]
Hello! I'll try to help, but it would be best if you use the issue template to show me exactly what you're aiming for.

Please either edit your issue to use the template, or close this one and open a new issue that does use the template. Thanks!

**Comment by cmhughes** [comment]
duplicate of https://github.com/cmhughes/latexindent.pl/issues/318
