### ISSUE TITLE
no indentation before headings

### ISSUE THREAD

**Issue by EngCat** [cmhughes/latexindent.pl#318]
Please provide the following when posting an issue:

original .tex code
--
```
%%%%%%%%%%%
\chapter{Introduction}
1st line
2nd line

```
yaml settings
--
Default 

actual/given output
--
```
	%%%%%%%%%%%
	\chapter{Introduction}
	1st line
2nd line
```

desired or expected output
--
```
%%%%%%%%%%%
\chapter{Introduction}
	1st line
2nd line

```
anything else
--
Hi, I'm using the Version 3.13.3 of the script. I need a bit of help.

Can I remove the indentation only **before** headings (\part, \chapter, \section....)?

Thanks in advance.

**Comment by cmhughes** [comment]
Thanks for using the issue template :)

I don't see any difference between the before and after....

Can you clarify?

**Comment by EngCat** [comment]
Thanks for your time. I've updated the first post.
I need no indentation before headings, because otherwise TeXShop - my favourite editor - does not recognize headings tags that are useful for code navigation.

**Comment by cmhughes** [comment]
When I run `latexindent.pl` on your snippet I don't receive your actual output; I get
```tex
%%%%%%%%%%%
\chapter{Introduction}
1st line
2nd line
```

Please check your log file `indent.log` for any settings that you have loaded.

**Comment by EngCat** [comment]
With the default settings all is TAB shifted and biutified... If I change from "\t" to "" nothing is biutified at all

**Comment by cmhughes** [comment]
I don't get your actual /given output
```tex
	%%%%%%%%%%%
	\chapter{Introduction}
	1st line
2nd line
```

**Comment by cmhughes** [comment]
Any update on this? Let me know :)
