### ISSUE TITLE
noIndent block starting %\end{noindent} with spaces

### ISSUE THREAD

**Issue by cmhughes** [cmhughes/latexindent.pl#32]
```
% arara: indent: {overwrite: yes, trace: yes}

% \begin{noindent}
\begin{equation}
	f(x),\quad x\in[0,1)
	\end{equation}
	% \end{noindent}
		text
```
doesn't work as expected, presumably because `%\end{noindent}` starts with space.

Using

```
% arara: indent: {overwrite: yes, trace: yes}

% \begin{noindent}
\begin{equation}
	f(x),\quad x\in[0,1)
	\end{equation}
% \end{noindent}
		text
```
works as expected.

Check the line that matches `%\end{noindent}` and make sure that it can accept multiple spaces (possibly none) at the beginning.

**Comment by cmhughes** [comment]
Fixed at https://github.com/cmhughes/latexindent.pl/commit/309ec92da005747ae271ff2d08473568bec5294c

**Comment by whitecat** [comment]
It seems like you are getting close to a release.

**Comment by cmhughes** [comment]
Hoping to get version 3.0 released by the end of 2016 :)
