### ISSUE TITLE
what's the hyphen '-' used for in yaml

### ISSUE THREAD

**Issue by ostaith** [cmhughes/latexindent.pl#327]
for example, for this rule, can you explain the different hyphen functions? I didn't find them in `latexindent.pdf`
<pre>
commandCodeBlocks:
    roundParenthesesAllowed: 1
    stringsAllowedBetweenArguments:
      -                          # hyphen1, don't understand at all, and why line break?
        amalgamate: 1
      - 'node'                   # hyphen2, looks like they are different case
      - 'at'                     # hyphen3, looks like they are different case
      - 'to'
      - 'decoration'
      - '\+\+'
      - '\-\-'
      - '\#\#\d'
    commandNameSpecial:
      -                          # hyphen4, don't understand at all, and why line break?
        amalgamate: 1
      - '@ifnextchar\['
</pre>

I have some specialBeginEnd, I try to add rule like this, but it can't work:
<pre>
specialBeginEnd:
    myGroup:
        - 
          begin: '\\group_begin:'
          end: '\\group_end:'
          lookForThis: 1
        - 
          begin: '\\color@begingroup'
          end: '\\color@endgroup'
          lookForThis: 1
    specialBeforeCommand: 1
</pre>

I can only add rule like this, then it can indent as my expect:
<pre>
specialBeginEnd:
    myGroup1:
        begin: '\\group_begin:'
        end: '\\group_end:'
        lookForThis: 1
    myGroup2:
        begin: '\\color@begingroup'
        end: '\\color@endgroup'
        lookForThis: 1
    specialBeforeCommand: 1
</pre>

test code:
<pre>
\cs_new_protected:Npn \maoxuan_input_toc_aux:nn #1#2
  {
    \cleardoublepage
    \int_set:Nn \l_maoxuan_page_int { \value { page } }
    \group_begin:
    \setcounter { page } { \c_one_int }
    \cs_set_eq:NN \maoxuan_the_page: \maoxuan_the_page_toc:
    \tl_gset:Nn \thepage {#1}
    #2
    \cleardoublepage
    \group_end:
    \pagenumbering { arabic }
    \setcounter { page } { \l_maoxuan_page_int }
  }
</pre>

and:
<pre>
\vbox_set:Nn \l_maoxuan_thanks_box
  {
    \dim_set_eq:NN \tex_hsize:D \columnwidth
    \@parboxrestore
    \int_set_eq:NN \tex_interlinepenalty:D \interfootnotelinepenalty
    \protected@edef \@currentlabel { \l_maoxuan_thanks_symbol_tl }
    \color@begingroup
    \maoxuan_thanks_text:
    \color@endgroup
  }
</pre>

**Comment by ostaith** [comment]
sorry, now I know the hyphen's mean in yaml, it's a sequence structure, like list in python. but i still want to know, whether i can add two different specialBeginEnd in one `myGroup`?

**Comment by cmhughes** [comment]
You can try
```yaml
specialBeginEnd:
    myGroup1:
        begin: '(?:\\group_begin|\\color@begingroup) ' :
        end: '(?:\\group_end|\\color@endgroup)' :
    specialBeforeCommand: 1
