### ISSUE TITLE
Command-line option allowing no backups

### ISSUE THREAD

**Issue by tdegeus** [cmhughes/latexindent.pl#333]
I would like a command-line option switching of the the feature of writing `.bakX` files.

To give an argument: I'm using `git` so this feature is not useful, rather just adding noise. 

(I know it can be done in user settings, but I would like to be able to do it directly from the command-line)

**Comment by cmhughes** [comment]
Have you seen the - c switch?

**Comment by tdegeus** [comment]
I had not. But my wish remains unchanged ;)

**Comment by cmhughes** [comment]
Removing the backup files option feels too dangerous to me.

**Comment by tdegeus** [comment]
I'm not asking to remove the option, nor to change the default. I'm just asking to have the option not to write them, in the case that I have everything covered (e.g. with `git`).

**Comment by cmhughes** [comment]
Yes, I understand :)

But, having the option still seems dangerous to me.

If a user chooses this option without realising what they're doing, and
doesn't have version control, and something goes wrong, I might ultimately
end up responsible.

Safety first.

**Comment by tdegeus** [comment]
Allright. Thanks for the reply

**Comment by tdegeus** [comment]
Just a question out of curiosity : what happens if I have a `main.tex` and I happen to have made a back-up of something else `main.bak0`, and I set `onlyOneBackUp: 1`. Would `latexindent.pl` then overwrite the unrelated back-up?

**Comment by cmhughes** [comment]
It should aim for main.bak with this setting.

**Comment by tdegeus** [comment]
Ok, but actually my point was : how does `onlyOneBackUp: 1` know that it its backup that it is overwriting?

So my point is the following: having `latexindent.pl` write files that I don't operate on, makes me more insecure than it makes me feel secure. That's why I suggested the command-line option. 

I guess that with the current API I should do something like 
```
latexindent.pl -c ~/.cache/latexindent
```
if I don't want to worry?

**Comment by cmhughes** [comment]
Thanks for these points.

You're right, there is a case in which users may have used main.bak from
another command and then they set onlyOneBackUp to be 1, and then
latexindent.pl could overwrite main.bak.

However, I would argue that by setting onlyOneBackUp to 1, the user is
saying 'I take responsibility for my backup procedure, and I know what I'm
doing'.

The default behaviour of latexindent is to create a new backup each and
every time. Anything other than this requires the user to take action, at
which point they are taking responsibility.

Your proposed use of the c switch sounds consistent with its intended use
:)
