### ISSUE TITLE
Conda install complains about Unicode::GCString module 

### ISSUE THREAD

**Issue by musm** [cmhughes/latexindent.pl#334]
Following the instructions for the conda install: 

```
❯ latexindent
Can't locate Unicode/GCString.pm in @INC (you may need to install the Unicode::GCString module) (@INC contains: /usr/local/texlive/2021/texmf-dist/scripts/latexindent /home/mus/anaconda3/lib/perl5/5.32
```

Is there a fix?

**Comment by cmhughes** [comment]
Have you seen https://github.com/cmhughes/latexindent.pl/issues/303?

Tagging @tdegeus

**Comment by tdegeus** [comment]
Presumably you are on Mac's M1?

If you happen to use conda: I advanced the fix:
```
conda install -c conda-forge latexindent.pl
```
Note that the executable there is called `latexindent.pl` (and not `latexindent`).

**Comment by musm** [comment]
So actually on on WSL (ubuntu)
Yes, I've installed through
```
❯ conda install latexindent.pl -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.


❯ latexindent
Can't locate Unicode/GCString.pm in @INC (you may need to install the Unicode::GCString module) (@INC contains: /usr/local/texlive/2021/texmf-dist/scripts/latexindent /home/mus/anaconda3/lib/perl5/5.32/site_perl /home/mus/anaconda3/lib/perl5/site_perl /home/mus/anaconda3/lib/perl5/5.32/vendor_perl /home/mus/anaconda3/lib/perl5/vendor_perl /home/mus/anaconda3/lib/perl5/5.32/core_perl /home/mus/anaconda3/lib/perl5/core_perl .) at /usr/local/texlive/2021/texmf-dist/scripts/latexindent/LatexIndent/AlignmentAtAmpersand.pm line 20.
BEGIN failed--compilation aborted at /usr/local/texlive/2021/texmf-dist/scripts/latexindent/LatexIndent/AlignmentAtAmpersand.pm line 20.
Compilation failed in require at /usr/local/texlive/2021/texmf-dist/scripts/latexindent/LatexIndent/Document.pm line 41.
BEGIN failed--compilation aborted at /usr/local/texlive/2021/texmf-dist/scripts/latexindent/LatexIndent/Document.pm line 41.
Compilation failed in require at /usr/local/bin/latexindent line 27.
BEGIN failed--compilation aborted at /usr/local/bin/latexindent line 27.

~
```

**Comment by musm** [comment]
Ahh I just saw that it should be `latexindent.pl` not `latexindent`
```
~ took 17s
❯ which latexindent
/usr/local/bin/latexindent

~
❯ which latexindent.pl
/home/mus/anaconda3/bin/latexindent.pl

```

**Comment by tdegeus** [comment]
Great! So I presume that it works? 

Just a few words of explanation: ``Unicode::GCString`` is a compiled package and available on CPAN only for common hardwares. Apparently you virtual machine does not qualify. In principle you have the possibility to compile it yourself, but I presume you are just happy with the conda feedstock ?

**Comment by musm** [comment]
The conda installation works perfectly on my end, so presumably it's precompiled and shipped through that distribution mechanism. 

I've opened https://github.com/cmhughes/latexindent.pl/pull/335 to clarify the executables name

**Comment by tdegeus** [comment]
The conda works, because I advanced https://github.com/cmhughes/latexindent.pl/tree/feature/no-GCString

**Comment by musm** [comment]
Interesting, so `Unicode::GCString` is no longer a required dependency and I was seeing this error since the distributed version in texlive is presumably from an earlier version of latexindent?

**Comment by tdegeus** [comment]
It will not be a required dependency, so texlive is just using the stable release. On conda I took the liberty to advise the fix, so let's say it's running in beta mode, until https://github.com/cmhughes/latexindent.pl/issues/303 is fixed

**Comment by cmhughes** [comment]
GCString *is still required *.

I'm trying to remove the dependency in 303. It's not guaranteed it will
succeed, but I am trying.

**Comment by cmhughes** [comment]
Implemented in https://github.com/cmhughes/latexindent.pl/releases/tag/V3.17; see also https://github.com/cmhughes/latexindent.pl/issues/303
