### ISSUE TITLE
Request support / Feature request for `tabularray` tabulars

### ISSUE THREAD

**Issue by MartinRJDagleish** [cmhughes/latexindent.pl#343]
Hey, 

I am loving latexindent as a convenient way to indent my documents and to have better readable source code. 

The only problem I have encountered is that latexindent does not seem to work with the `tblr` environment by the package `tabularray`. 
It is basically like the `tabular` environment and I would like the alignments to be made at the & signs. 

Related question (which was implemented for `nicematrix` package):
https://tex.stackexchange.com/questions/568637/how-to-make-latexindent-align-columns-in-nested-environments

My question on TeX.SX:
https://tex.stackexchange.com/questions/634997/latexindent-add-tblr-tabularray-environment-as-tabular-for-aligning-at

**Comment by cmhughes** [comment]
Glad it's working for you.

Can you try
```yaml
lookForAlignDelims:
   tblr: 1
```

**Comment by lvjr** [comment]
I am the author of `tabularray` package. Could you please add environments `tblr`, `longtblr`, `talltblr`  to `defaultSettings.yaml` so that my users need not to manually change settings?

**Comment by cmhughes** [comment]
Many thanks, will do :)

**Comment by cmhughes** [comment]
Implemented as of https://github.com/cmhughes/latexindent.pl/commit/6d55394a65126d0c77c105ac92a5126777dd7c03

This will be part of the next release, coming soon. Please leave this open, and I'll close it when appropriate.

**Comment by cmhughes** [comment]
Implemented as of https://github.com/cmhughes/latexindent.pl/releases/tag/V3.16
