### ISSUE TITLE
Indent body of `document` environment

### ISSUE THREAD

**Issue by alexreg** [cmhughes/latexindent.pl#348]
Is there a way to get latexindent to leave the contents of the `document` environment indented?

original .tex code
--
```latex
\documentclass{article}

\begin{document}

    foo

\end{document}
```

yaml settings
--
none

actual/given output
--
```latex
\documentclass{article}

\begin{document}

foo

\end{document}
```
(indentation removed)

desired or expected output
--
same as input

**Comment by cmhughes** [comment]
Can you try
```yaml
noAdditionalIndent:
    document: 0
```

**Comment by alexreg** [comment]
That works, thank you. Is there a way to turn off `noAdditionalIndent` for all elements, not just `document`?

Small side point, not related: Can I get latexindent to always end the file with a newline?

**Comment by cmhughes** [comment]
https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html#summary

**Comment by alexreg** [comment]
Thanks very much.

**Comment by alexreg** [comment]
@cmhughes Sorry, what about the side point. Is that possible right now? I can create another issue if you like.

**Comment by cmhughes** [comment]
If you use the following, say `alex.yaml`, 
```yaml
replacements:
  -
    substitution: |-
       s/\R*?$/\n/s 
```
and then
```
latexindent.pl -rv -l alex.yaml
```
then you get
```tex
\documentclass{article}

\begin{document}

foo

\end{document}

```

**Comment by alexreg** [comment]
@cmhughes Thanks for that. A little bit hacky, mind you... but at least there's a solution already! Any chance of a `trailingNewLine` option in the future, perhaps? :-)

**Comment by cmhughes** [comment]
You can also use
```yaml
modifyLineBreaks:
    environments:
        document:
            EndFinishesWithLineBreak: 4
```
and then 
```
latexindent.pl -m -l alex1.yaml cmh.tex -w
```
This uses the `-m` switch instead of the `-rv` switch.

**Comment by alexreg** [comment]
@cmhughes Thank you. Doesn't that apply to all instances of `\end{...}` though?

**Comment by cmhughes** [comment]
Nope, just document.

**Comment by alexreg** [comment]
Thanks, I'll use that solution then.

**Comment by alexreg** [comment]
Ah, slight problem: I often have texcount comments (directives) after `\end{document}`. Any chance of adding an EndOfFile option in the future? :-)
