### ISSUE TITLE
Crash on start with Homebrew-installed version

### ISSUE THREAD

**Issue by TeddyHuang-00** [cmhughes/latexindent.pl#349]
Error Message
--
```sh
$ latexindent --version
SystemDirectory.c: loadable library and perl binaries are mismatched (got handshake key 0xfb80080, needed 0xc700080)
```

anything else
--
OS: Macos monterey 12.2.1
perl: 5.34.0
Homebrew 3.3.13
latexindent: 3.15

I had check most of the similar issues and installed the following packages
```sh
export CPATH="/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Perl/5.30/darwin-thread-multi-2level/CORE/:$CPATH"
cpan -i Log::Log4perl Log::Dispatch::File YAML::Tiny File::HomeDir Unicode::GCString App:cpanminus
```

but still `latexindent` would crash on start

BTW, I wasn't able to use `tlmgr` as it will throw `action not allowed in system mode` when trying to set repository and install `latexindent`

**Comment by cmhughes** [comment]
Have you tried installing directly from this repository?

**Comment by cmhughes** [comment]
latexindent.pl
LatexIndent/*.pm
defaultSettings.yaml

**Comment by TeddyHuang-00** [comment]
> Have you tried installing directly from this repository?

Yeah I've tried to do so, but it throws a bunch of errors like these

```sh
Bareword found where operator expected at latexindent-module-installer.pl line 8, near ""en" data"
	(Missing operator before data?)
Bareword found where operator expected at latexindent-module-installer.pl line 8, near ""auto" data"
	(Missing operator before data?)
Bareword found where operator expected at latexindent-module-installer.pl line 8, near ""light" data"
	(Missing operator before data?)
Can't modify numeric lt (<) in scalar assignment at latexindent-module-installer.pl line 8, near ""en" data"
syntax error at latexindent-module-installer.pl line 8, near ""en" data"
Excessively long <> operator at latexindent-module-installer.pl line 20.
```

---

However, I think the problem is on macOS's side. A quick solution to the problem is that I uninstalled `texlive` and `latexindent`, and installed `mactex` instead. After that I went through the `cpan` step again and things magically worked! So apparently `mactex` has included some fix to this problem. Maybe we could find some clues in that, or we may just leave it alone (just use `mactex` since it already included `latexindent`)

**Comment by TeddyHuang-00** [comment]
Sorry I haven't tried that yet.

However, I think the problem is on macOS's side. A quick solution to the problem is that just uninstall `texlive` and `latexindent`, and then install `mactex` instead. After that, go through the `cpan` step again and things will magically work! So apparently, `mactex` has included some fix to this problem. Maybe we could find some clues in that, or we may just leave it alone (just use `mactex` since it already included `latexindent`)

**Comment by cmhughes** [comment]
Let me know if you need any further details from me :)
