### ISSUE TITLE
execution of latexindent-module-installer.pl in Arch-based distribution requieres the installation of cpanminus package

### ISSUE THREAD

**Issue by KrappRamiro** [cmhughes/latexindent.pl#351]
Is there any way that is added to the documentation?

**Comment by cmhughes** [comment]
Sure, what specific line do you want added?

pull request welcome, it'll be documentation/sec-appendix.tex

**Comment by KrappRamiro** [comment]
If I understood you correctly, you want me to write a one-line guide to solve the problem, then do a pull request to documentation/sec-appendix.tex with that line, right? Ok, im on it :smile:

**Comment by cmhughes** [comment]
Great, thank you! Resolved at https://github.com/cmhughes/latexindent.pl/pull/352
