### ISSUE TITLE
Maximum character per line

### ISSUE THREAD

**Issue by jasjuang** [cmhughes/latexindent.pl#36]
Is it possible to autoformat so the max number of character number will be lets say 80 per line? It will be super awesome if you can add in this feature.

**Comment by cmhughes** [comment]
Hi jasjuang,
Thanks for your feedback :) Have you seen https://github.com/cmhughes/latexindent.pl/issues/33? Is yours a separate issue? Let me know :)
Best
Chris

**Comment by jasjuang** [comment]
Oops, yes it's the same. However, I will like to clarify that I hope it's not a simple line break when the character hits 80, breaking while aligning + - * / & in the equations/table (kinda like what clang format is doing for C++) will be super awesome.

Thanks,
Jason

**Comment by cmhughes** [comment]
Ok, no problem, Jason! 

I've added your comment to https://github.com/cmhughes/latexindent.pl/issues/33 and will close this issue, if you don't mind :)
Best
Chris
