### ISSUE TITLE
Move .bak to local folder in workspace

### ISSUE THREAD

**Issue by castn** [cmhughes/latexindent.pl#365]
Is it possible to configure a folder in which all backups will be moved in the configuration file of this script? I know it's possible for a single command. But can I even set it in the configuration, so that latexindent triggered by pre-commit can move it to a central location instead of leaving it at the location where the indented file is located?

I read through the doc, but haven't seen an option to do that. I hope I haven't overseen it. Or isn't this a good way to use the script, and that's why it doesn't exist?

**Comment by cmhughes** [comment]
Have you seen the c switch

https://latexindentpl.readthedocs.io/en/latest/sec-how-to-use.html#from-the-command-line

**Comment by castn** [comment]
Thx,
yeah, I completely missed it.
