### ISSUE TITLE
UnsatisfiableError when installing

### ISSUE THREAD

**Issue by eZSnake** [cmhughes/latexindent.pl#366]
Please provide the following when posting an issue:

original .tex code
--
I didn't get to testing any .tex files as the install appears to have a problem on my end

yaml settings
--
Templated used from https://gist.github.com/julian-west/e50b25a9aa10551e3452f5a6cfaa6aa3

To use:
     pre-commit run -a
Or:
     pre-commit install  # (runs every time you commit in git)
To update this file:
     pre-commit autoupdate
See https://github.com/pre-commit/pre-commit

repos:
Run latexindent.pl (get dependencies using Conda)
- repo: https://github.com/cmhughes/latexindent.pl.git
  rev: V3.17.2
  hooks:
  - id: latexindent-conda
    args: ["-–c=src/latex/backup_latexindent/"]

Standard hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-added-large-files             # prevents giant files from being committed
  - id: check-case-conflict                 # checks for files that would conflict in case-insensitive filesystems
  - id: check-merge-conflict                # checks for files that contain merge conflict strings
  - id: check-symlinks                      # checks for files that contain merge conflict strings
  - id: check-yaml                          # checks yaml files for parseable syntax
    exclude: ^conda\.recipe/meta\.yaml$
  - id: debug-statements                    # checks yaml files for parseable syntax
  - id: end-of-file-fixer                   # ensures that a file is either empty, or ends with one newline
  - id: mixed-line-ending                   # replaces or checks mixed line ending
  - id: requirements-txt-fixer              # sorts entries in requirements.txt
  - id: trailing-whitespace                 # trims trailing whitespace

Black, the code formatter, natively supports pre-commit
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    exclude: ^(docs)

Sort your imports in a standard form
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort

Upgrade older Python syntax
- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.1
  hooks:
  - id: pyupgrade
    args: ["--py36-plus"]

Changes tabs to spaces
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.13
  hooks:
  - id: remove-tabs
    exclude: ^(docs)

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear]

actual/given output
--
Copy pasted from cmd

An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\rehwa\\anaconda3\\condabin\\conda.BAT', 'env', 'create', '-p', 'C:\\Users\\rehwa\\.cache\\pre-commit\\repo2tqqmb5r\\conda-default', '--file', 'environment.yml')
return code: 1
expected return code: 0
stdout:
    Collecting package metadata (repodata.json): ...working... done
    Solving environment: ...working...
    Found conflicts! Looking for incompatible packages.
    This can take several minutes.  Press CTRL-C to abort.
    failed
    Solving environment: ...working...
    Found conflicts! Looking for incompatible packages.
    This can take several minutes.  Press CTRL-C to abort.
    failed

stderr:

    UnsatisfiableError:

desired or expected output
--
I want it to have a successful install instead of crashing

anything else
--
I tried downloading latexindent through Anaconda Navigator but it kept on giving me 'UnsatisfiableError' so I tried it through a command prompt which ended up giving me the same error (error message is pasted above)

**Comment by eZSnake** [comment]
A direct install attempt through the console results in this:
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError:

**Comment by cmhughes** [comment]
I'm finding your original post hard to read. Can you edit it so that it is formatted consistently?

**Comment by eZSnake** [comment]
It should now have more consistent formatting

**Comment by cmhughes** [comment]
Thanks for editing.

So this is about pre-commit and conda...? Is your pre-commit yaml file minimal? Please strip it down to the minimum possible.

**Comment by tdegeus** [comment]
@eZSnake I have a hard time understanding what might go wrong. The installation though pre-commit, and your second post "a direct install" seem to suggest that your conda is somehow unhappy of getting on of the dependencies of `latexindent.pl`. What is crucially missing in you post is therefore on which platform you are working. To debug, I would suggest that you try to install the dependencies of `latexindent.pl` one by one so see which one is the blocker (I would think that it is perl itself). So please try in an active environment:
```bash
conda install -c conda-forge perl
conda install -c conda-forge perl-file-homedir
conda install -c conda-forge perl-yaml-tiny
conda install -c conda-forge latexindent.pl
```

Furthermore, I would suggest the same as @cmhughes : make a `.pre-commit-config.yaml` with only `latexindent.pl` to try (and remove everything that is not needed from the post above).

As a work-around you could try to use `latexindent.pl` instead of `latexindent-conda` in your `.pre-commit-config.yaml`

**Comment by eZSnake** [comment]
I tried creating a new environment in Conda and just installing latexindent as the only package using the conda install commands and it installed perl just fine but I once again got the UnsatisfiableError when trying to install perl-file-homedir

conda install -c conda-forge perl-yaml-tiny
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError:

The same messages popped up when I tried to install perl-yaml-tiny

**Comment by cmhughes** [comment]
It seems that this is really a conda installation issue and not specific to latexindent....?

I came across the following which looks like it had some tips:
https://github.com/merenlab/anvio/issues/1145

**Comment by cmhughes** [comment]
Summary of things we need from you, @eZSnake 

1. minimal YAML
2. confirmation of the platform you're working on
3. confirmation of the output from following the steps that @tdegeus  has given

**Comment by cmhughes** [comment]
Closing for now, let us know if you can provide any further information.
