### ISSUE TITLE
Delimiters are misaligned after formatting when the tables contains Chinese character

### ISSUE THREAD

**Issue by dzx-dzx** [cmhughes/latexindent.pl#381]
original .tex code
--
```latex
\begin{table}[H]
    \centering
    \begin{tabular}{|c|c|c|}
        \hline 
        a & b & c    \\
        d & e & f    \\
        g & h & i    \\
        你& 我& 他    \\
        你你你&我我我&他他他
    \end{tabular}
\end{table}
```

yaml settings
--
None? 
The config should conform with https://github.com/James-Yu/LaTeX-Workshop/wiki/Format

actual/given output
--
```latex
\begin{table}[H]
    \centering
    \begin{tabular}{|c|c|c|}
        \hline 
        a   & b   & c    \\
        d   & e   & f    \\
        g   & h   & i    \\
        你   & 我   & 他    \\
        你你你 & 我我我 & 他他他
    \end{tabular}
\end{table}
```
desired or expected output
--
```latex
\begin{table}[H]
    \centering
    \begin{tabular}{|c|c|c|}
        \hline 
        a      & b     & c    \\
        d      & e     & f    \\
        g      & h     & i    \\
        你     & 我    & 他    \\
        你你你 & 我我我 & 他他他
    \end{tabular}
\end{table}
```

**Comment by cmhughes** [comment]
Thanks for this.

Can you try the GCString switch https://latexindentpl.readthedocs.io/en/latest/sec-appendices.html#the-gcstring-switch

**Comment by dzx-dzx** [comment]
Oh this flag surely alleviates the issue, but...strangely it still appears misaligned in vscode and other editors, but looks neat when I run `cat` in the command line.

**Comment by cmhughes** [comment]
Great,  glad it worked!

I don't have any control over any text editors.

Let me know if you need anything else from me :)

**Comment by dzx-dzx** [comment]
Yes, I'm aware this is beyond the topic. I shall close the issue.

**Comment by zousiyu1995** [comment]
I have a same problem. see https://github.com/cmhughes/latexindent.pl/issues/434

**Comment by cmhughes** [comment]
In both cases, this is a font/editor issue.

latexindent.pl is behaving as it should.
