### ISSUE TITLE
Thank you! Celebrating 10 years of latexindent.pl

### ISSUE THREAD

**Issue by cmhughes** [cmhughes/latexindent.pl#383]
Hi everyone,
Today marks 10 years since the [first commit](https://github.com/cmhughes/latexindent.pl/commit/ac8a07df62b87a4b663a64125c33bca51e48dffa) of `latexindent.pl`. The project has come a long way since then, and the community of contributors and users has been a big part of it. 

thank you to the contributors
-
Thank you to all of the [contributors](https://github.com/cmhughes/latexindent.pl/graphs/contributors) of the project, many of whom have added features that I hadn't heard of before their work! 

* @qiancy98 
* @XuehaiPan 
* @tdegeus 
* @jasjuang 
* @Holzhaus 
* @nzqo 
* @jeanlego 
* @msramalho 
* @newptcai 
* @alexreg 
* @jun-sheaf 
* @xu-cheng 
* @eggplants 
* @yzhang-gh 
* @musm 
* @KrappRamiro 

I really like that hosting the project here on GitHub encourages people to contribute, and that I can learn from these contributions.

thank you to the users
-
Thank you to all of the users of `latexindent.pl`. Your questions and interesting use cases, many of which I hadn't considered, have really helped me to try to improve the project. 

moving forward
-
I appreciate that the project isn't perfect, and that there is [some clear room for improvement](https://latexindentpl.readthedocs.io/en/latest/sec-conclusions-know-limitations.html). I will continue to try to drive the project forward, and do please keep the contributions and questions coming :)

All the best
Chris (cmhughes, project author)

**Comment by tdegeus** [comment]
Many thanks @cmhughes for the project, your strong commitment to it, but also you openness to changes.

**Comment by alexreg** [comment]
Thanks for the great work over the years!
