### ISSUE TITLE
Learning from biber

### ISSUE THREAD

**Issue by cmhughes** [cmhughes/latexindent.pl#388]
background
-
* The `biber` package (https://github.com/plk/biber) is based in `perl`
* It deploys standalone executables across *many* different operating systems, and users are *not* required to have a `perl` installation

I would like to have this model work for `latexindent.pl`

specific questions to answer
-
1. I need to ask the `biber` maintainer *"what is the specific folder structure that you upload to ctan so that it works with all of these distributions?"*
2. I need to ask the `MiKTeX` maintainer *"what is it that allows the standalone executable from `biber` to work, while the one provided by `latexindent.exe` does not work?"*
3. How do I expand https://github.com/cmhughes/latexindent.pl/blob/main/.github/workflows/build-documentation-and-windows-exe.yaml so that it can include all of the different options given by `biber` (see the `dist` folder: https://github.com/plk/biber/tree/dev/dist)? 

for reference
-
The `latexindent.zip` uploaded to `ctan` has the following structure:
```
latexindent
|-- latexindent.pl
|-- latexindent.exe
|-- defaultSettings.yaml
|-- LatexIndent
| |-- Verbatim.pm
| |-- Wrap.pm
| |-- Special.pm
| |-- Replacement.pm
| |-- Braces.pm
| |-- Sentence.pm
| |-- Version.pm
| |-- Else.pm
| |-- Tokens.pm
| |-- UnNamedGroupingBracesBrackets.pm
| |-- BackUpFileProcedure.pm
| |-- Heading.pm
| |-- FileContents.pm
| |-- DoubleBackSlash.pm
| |-- GetYamlSettings.pm
| |-- MandatoryArgument.pm
| |-- Command.pm
| |-- BlankLines.pm
| |-- Preamble.pm
| |-- HiddenChildren.pm
| |-- IfElseFi.pm
| |-- KeyEqualsValuesBraces.pm
| |-- Document.pm
| |-- FileExtension.pm
| |-- AlignmentAtAmpersand.pm
| |-- NamedGroupingBracesBrackets.pm
| |-- LogFile.pm
| |-- Indent.pm
| |-- ModifyLineBreaks.pm
| |-- Arguments.pm
| |-- Lines.pm
| |-- OptionalArgument.pm
| |-- Environment.pm
| |-- Logger.pm
| |-- RoundBrackets.pm
| |-- Switches.pm
| |-- TrailingComments.pm
| |-- Item.pm
| |-- Check.pm
| |-- HorizontalWhiteSpace.pm
|-- documentation
| |-- latexindent-yaml-schema.json
| |-- latexindent.pdf
|-- README
|-- latexindent-module-installer.pl
```

**Comment by cmhughes** [comment]
@plk I wondered if I could ask you:

> what is the specific folder structure that you upload to ctan so that it works with all of the distributions for which you provide an executable?

**Comment by cmhughes** [comment]
@edocevoli I wondered if I could ask you:

> what is it that allows the standalone executable from biber to work, while the one provided by latexindent.exe does not work?

**Comment by edocevoli** [comment]
If IIRC, there are no standalone executables for `latexindent`. MiKTeX just installs a `latexindent` stub which then calls `perl latexindent.pl`.

**Comment by cmhughes** [comment]
@edocevoli thanks for getting back to me.

There *is* a stand alone executable for latexindent,  but what I'd like to know is: how does MiKTeX pick up the executable of `biber`?

**Comment by plk** [comment]
@cmhughes  - for `biber`, we now have a separate package for each platform and the structure and packaging details for TL are all detailed here:

https://github.com/plk/biber/blob/dev/BUILDERS.README

**Comment by cmhughes** [comment]
@plk  many thanks, that's really helpful.

**Comment by cmhughes** [comment]
@edocevoli I wondered if you could let me know how MiKTeX interacts with `biber`; does it use a standalone executable?

**Comment by cmhughes** [comment]
update from texlive mailing list
-
I've heard back from the texlive mailing list in trying to understand how `biber` interacts with texlive. The maintainers say

> 
> Therefore the Biber maintainer and builders go to the trouble of
> building binaries with Par::Packer (not simple), and TL goes to the
> trouble of distributing them (also not simple). It is a nontrivial
> special case at every level.  Let's not go there for any other program.

So, it looks like even if I can build more binaries, it won't change anything from the distribution point of view....

**Comment by cmhughes** [comment]
As of https://github.com/cmhughes/latexindent.pl/commit/a37c9605639c0b3bd48733be765083bae2fa8598, I've updated `github actions` so that it produces `Linux` and `macOS` executables, which are deployed with each release.

answers to questions posed above
-

>  1.   I need to ask the biber maintainer "what is the specific folder structure that you upload to ctan so that it works with all of these distributions?"

Folder structure detailed at https://github.com/plk/biber/blob/dev/BUILDERS.README. 

>   2.  I need to ask the MiKTeX maintainer "what is it that allows the standalone executable from biber to work, while the one provided by latexindent.exe does not work?"

I continue to not be able to obtain this answer.

>  3.   How do I expand https://github.com/cmhughes/latexindent.pl/blob/main/.github/workflows/build-documentation-and-windows-exe.yaml so that it can include all of the different options given by biber (see the dist folder: https://github.com/plk/biber/tree/dev/dist)?

I have expanded github actions as above; further additions with more executables are welcome.
