### ISSUE TITLE
Add other optional paths to the default configuration 

### ISSUE THREAD

**Issue by Nehctarg** [cmhughes/latexindent.pl#396]
# Linux
Reference to the XDG-specification: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
* Add  the directory `$XDG_CONFIG_DIR/latexindent` to the optional locations where the configuration files (i.e. `indentconfig.yaml`and `.indentconfig.yaml`) can be stored (e.g. use `$XDG_CONFIG_DIR/latexindent/indentconfig.yaml` instead of `$HOME/indentconfig.yaml`)
* Or give users a way to change the default config location (e.g. through an environment variable)

# Windows
Disclaimer: I don't use this platform so my information might be off, but as far as I know you should change the `$XDG_CONFIG_HOME` with  `%LOCALAPPDATA%`.

**Comment by cmhughes** [comment]
How does Perl know about the directory `$XDG_CONFIG_DIR/`? Please be encouraged to look at `GetYamlSettings.pm` which is the file that controls all of this: https://github.com/cmhughes/latexindent.pl/blob/main/LatexIndent/GetYamlSettings.pm, in particular https://github.com/cmhughes/latexindent.pl/blob/8234ea6f85c0e27ca7379740d68dbb88b2400554/LatexIndent/GetYamlSettings.pm#L123

**Comment by Nehctarg** [comment]
> Do you have anything specific in mind as to how this would work?

Considering other projects, I imagined something like an environment variable, named `LATEXINDENT_CONFIG` or so, which contains the path to the `indentconfig.yaml` file. This value would than be favored above the defaults. This makes it painless to change the config location to some arbitrary place, whilst also making implementation painless because one would just have to look at the `LATEXINDENT_CONFIG` environment variable. 

> How does Perl know about the directory $XDG_CONFIG_DIR/? 

As far as I know environment variable are accessible under the `%ENV` register, so to get the value stored in `XDG_CONFIG_HOME` one would use  `$ENV{XDG_CONFIG_HOME}`. 

After looking into this, I could properly come up with a pull request.

**Comment by cmhughes** [comment]
Great, many thanks, a pull request would be great.

Just in case it's relevant : it's really important that latexindent does
not require any further Perl modules, so please keep solutions based on
currently loaded modules.

**Comment by cmhughes** [comment]
Implemented as of https://github.com/cmhughes/latexindent.pl/pull/397

(Please leave this open until released).

Thanks again!

**Comment by cmhughes** [comment]
This is part of `V3.20` at https://github.com/cmhughes/latexindent.pl/releases/tag/V3.20. I've uploaded it to `ctan`. 

Many thanks for your contribution! :)
