### ISSUE TITLE
latexindent on texlive broken

### ISSUE THREAD

**Issue by tdegeus** [cmhughes/latexindent.pl#404]
Running 
```bash
$ latexindent --version
```
outputs 
```
Can't locate File/HomeDir.pm in @INC (you may need to install the File::HomeDir module) (@INC contains: /usr/local/texlive/2022/texmf-dist/scripts/latexindent /Library/Perl/5.30/darwin-thread-multi-2level /Library/Perl/5.30 /Network/Library/Perl/5.30/darwin-thread-multi-2level /Network/Library/Perl/5.30 /Library/Perl/Updates/5.30.3 /System/Library/Perl/5.30/darwin-thread-multi-2level /System/Library/Perl/5.30 /System/Library/Perl/Extras/5.30/darwin-thread-multi-2level /System/Library/Perl/Extras/5.30) at /usr/local/texlive/2022/texmf-dist/scripts/latexindent/LatexIndent/GetYamlSettings.pm line 24.
BEGIN failed--compilation aborted at /usr/local/texlive/2022/texmf-dist/scripts/latexindent/LatexIndent/GetYamlSettings.pm line 24.
Compilation failed in require at /usr/local/texlive/2022/texmf-dist/scripts/latexindent/LatexIndent/Verbatim.pm line 23.
BEGIN failed--compilation aborted at /usr/local/texlive/2022/texmf-dist/scripts/latexindent/LatexIndent/Verbatim.pm line 23.
Compilation failed in require at /usr/local/texlive/2022/texmf-dist/scripts/latexindent/LatexIndent/Lines.pm line 23.
BEGIN failed--compilation aborted at /usr/local/texlive/2022/texmf-dist/scripts/latexindent/LatexIndent/Lines.pm line 23.
Compilation failed in require at /usr/local/texlive/2022/texmf-dist/scripts/latexindent/LatexIndent/Document.pm line 30.
BEGIN failed--compilation aborted at /usr/local/texlive/2022/texmf-dist/scripts/latexindent/LatexIndent/Document.pm line 30.
Compilation failed in require at /Library/TeX/texbin/latexindent line 27.
BEGIN failed--compilation aborted at /Library/TeX/texbin/latexindent line 27.
```

Note that I am on macTeX and that according to the "TeX Live Utility" I am on 
```
latexindent.pl, version 3.19.1, 2022-12-04
```

**Comment by cmhughes** [comment]
Can you install the required perl modules?

https://latexindentpl.readthedocs.io/en/latest/sec-appendices.html#manually-installing-modules

**Comment by tdegeus** [comment]
That would be a work-around, though I wonder if it has be done with texlive's perl? Anyway, I just wanted to report this for the benefit of the library, as a 'work-around' I am using `pre-commit` and/or the conda-forge package, so I am good to go. 

The reason I reported is that I though that maybe the `Makefile.PL` is not properly used for the texlive package such that the dependency is indeed not included in the package

**Comment by cmhughes** [comment]
Many thanks.

I'd argue this is the *solution *, not a workaround.

I don't have any influence over texlive perl, and the communication I've
had with the team about dependency leads me to believe that I can't add
anything.

**Comment by sadid** [comment]
Resolved in Arch by adding the missing package `perl-yaml-tiny`. Despite having the latest texlive installed through pacman, the `latexindent.pl` was broken, mirroring the OP's issue. 

Shared the solution in this close issue for reference. Also PR #510 and Issue #342 seems to be relevant here.
