### ISSUE TITLE
latexindent changes characters with accents

### ISSUE THREAD

**Issue by raziel408** [cmhughes/latexindent.pl#411]
Please provide the following when posting an issue:

original .tex code
--
\documentclass[spanish]{report}

\usepackage[latin1]{inputenc}
\usepackage[spanish]{babel}
\usepackage[all]{xy}

\begin{document}

\chapter{Introducción}

\end{document}

yaml settings
--
*Please paste your YAML settings (if any) here*

actual/given output
--
\documentclass[spanish]{report}

\usepackage[latin1]{inputenc}
\usepackage[spanish]{babel}
\usepackage[all]{xy}

\begin{document}

\chapter{Introducci\xF3n}

\end{document}

desired or expected output
--
\documentclass[spanish]{report}

\usepackage[latin1]{inputenc}
\usepackage[spanish]{babel}
\usepackage[all]{xy}

\begin{document}

\chapter{Introducción}

\end{document}

anything else
--
It's changing the ó in Introducción for \xF3. I looked for a solution or a possible configuration that would solve it in the documentation. But didn't find any. Any help to solve this would be appreciated.

**Comment by cmhughes** [comment]
Many thanks for this, I'll look at it soon hopefully, no later than the weekend.

**Comment by cmhughes** [comment]
I'm unable to replicate your results. 

I'm on Linux Ubuntu, and I receive the output
```tex
\documentclass[spanish]{report}

\usepackage[latin1]{inputenc}
\usepackage[spanish]{babel}
\usepackage[all]{xy}

\begin{document}

\chapter{Introducción}

\end{document}
```
Can you let me know details of what your set up is?

**Comment by raziel408** [comment]
I'm on linux mint 21. I used emacs with apheleia mode. But I just tested it from the console and had the same result.

**Comment by cmhughes** [comment]
It sounds like this might be to do with your operating system

**Comment by cmhughes** [comment]
Here's a minimum script to try

```perl
Listing 572 helloworld.pl
#!/usr/bin/perl

use strict;                         #     |
use warnings;                       #     |
use Encode;                         #     |
use Getopt::Long;                   #     |
use Data::Dumper;                   #  these modules are
use List::Util qw(max);             #  generally part
use PerlIO::encoding;               #  of a default perl distribution
use open ':std', ':encoding(UTF-8)';#     |
use Text::Wrap;                     #     |
use Text::Tabs;                     #     |
use FindBin;                        #     |
use File::Copy;                     #     |
use File::Basename;                 #     |
use File::HomeDir;                  # <--- typically requires install via cpanm
use YAML::Tiny;                     # <--- typically requires install via cpanm

print "chapter{Introducción" ;
exit;
```

**Comment by raziel408** [comment]
The output of that script is:
chapter{IntroducciÃ³n
its very likely your right and it has to do with my system. Thanks a lot for the help. I let you know if I find a solution.

**Comment by cmhughes** [comment]
I wonder if this is a font issue.... Do you have a way of checking the font on your operating system?

**Comment by raziel408** [comment]
I think is not possible to be a font problem. My terminal is able to print uft-8 characters.
I've been doing some testing. I was able to run the script in a new file. And it produced the right output to the terminal:

```
cat test.tex # produces the rigth output
latexindent test.tex # produces the rigth output
```
But after that
`
pdflatex test.tex
`
Produced a pdf with ó printed as Ã³
My text editor also shows wrong encoding of the ó character.
I also tested the minimal script in other systems and the output is:
`
chapter{IntroducciÃ³n
`

**Comment by cmhughes** [comment]
I'm not sure what to do about this?

**Comment by cmhughes** [comment]
So do we think this is a problem with latexindent?

**Comment by raziel408** [comment]
I'm not sure. I'm not experienced in perl. I tried to look a little more into that and found this question:
[https://stackoverflow.com/questions/627661/how-can-i-output-utf-8-from-perl](https://stackoverflow.com/questions/627661/how-can-i-output-utf-8-from-perl)
But, I haven't had the time to look more into it. Sorry.

**Comment by raziel408** [comment]
Hi, I managed to make the minimal example to work on my machine. I added the line
`use utf8;`
I took it from the following question:
[https://stackoverflow.com/a/14658425](https://stackoverflow.com/a/14658425)
Hope that helps.

**Comment by cmhughes** [comment]
So perhaps the routine in Latexindent/Document.pm needs updating

sub output_indented_text

**Comment by cmhughes** [comment]
Do feel encouraged to take a look and submit a pull request if appropriate.

**Comment by raziel408** [comment]
ok, thanks a lot.

**Comment by cmhughes** [comment]
For reference, it'll be

https://github.com/cmhughes/latexindent.pl/blob/f69cbfff6b1d22f1a729c2830d5f91537756135f/LatexIndent/Document.pm#L222

and I think you'll want the top answer from the link you shared https://stackoverflow.com/a/627672/1091649
