### ISSUE TITLE
`modifyLineBreaks` with `when: after` breaks line too early & introduces huge unwanted indent

### ISSUE THREAD

**Issue by kwshi** [cmhughes/latexindent.pl#412]
Please provide the following when posting an issue:

Original TeX code:
```latex
\documentclass{article}
\begin{document}

the main idea behind trig integrals: pythagorean theorem identities. what is a triangle anyway?

\end{document}
```

YAML settings:
```yaml
modifyLineBreaks:
  textWrapOptions:
    columns: 80
    when: "after"
```

---

Actual/given output:
```latex
\documentclass{article}
\begin{document}

the main idea behind trig integrals: pythagorean theorem
                   identities. what is a triangle anyway?

\end{document}
```
(has weirdly, extra-super-indented second line; also line break occurs far too early, at a mere 56 columns long)

Expected/desired output:
```latex
\documentclass{article}
\begin{document}

the main idea behind trig integrals: pythagorean theorem identities. what is a
triangle anyway?

\end{document}
```

Running `latexindent -m` on this file (to enable line break modifying) introduces a really weird, super long indent on the second line of the paragraph. The issue isn't present when we use `when: "before"`, so the bug seems exclusive to the `when: "after"` algorithm.

I'm currently running latexindent version 3.20.1, 2023-01-07.

**Comment by cmhughes** [comment]
Man thanks, that's a really clear example.

I'll get to this soon, hopefully. Planning to look at it no later than the weekend.

**Comment by cmhughes** [comment]
Thanks for reporting this.

I've fixed it as of https://github.com/cmhughes/latexindent.pl/commit/dccf5a9f5eede645851f1152220d438ee2e34ec6, I'll get a release out soon.

**Comment by cmhughes** [comment]
Resolved at https://github.com/cmhughes/latexindent.pl/releases/tag/V3.20.2, and uploaded to ctan.

Thanks again!
