### ISSUE TITLE
Non-English (non-ASCII) paragraphs are not affected by the "modify linebreaks" action

### ISSUE THREAD

**Issue by Andrew15-5** [cmhughes/latexindent.pl#428]
original .tex code
--

```latex
\begin{enumerate}
  \item test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test
  \item тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест
  \item テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
\end{enumerate}
```

yaml settings
--

```yaml
defaultIndent: "  "
modifyLineBreaks:
  textWrapOptions:
    columns: 81
    when: after
```

actual/given output
--

```latex
\begin{enumerate}
  \item test test test test test test test test test test test test test test
        test test test test test test test test test test test test test test
        test test test test test test test test test test test test test test
  \item тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест
  \item テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
\end{enumerate}
```

desired or expected output
--

```latex
\begin{enumerate}
  \item test test test test test test test test test test test test test test
        test test test test test test test test test test test test test test
        test test test test test test test test test test test test test test
  \item тест тест тест тест тест тест тест тест тест тест тест тест тест тест
        тест тест тест тест тест тест тест тест тест тест тест тест тест тест
        тест тест тест тест тест тест тест тест тест тест тест тест тест тест
        тест
  \item テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
        テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
        テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
        テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
        テスト テスト テスト
\end{enumerate}
```

**Comment by cmhughes** [comment]
Can you try adjusting blocksBeginWith 

https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#text-wrap-blocksbeginwith-examples

**Comment by Andrew15-5** [comment]
How exactly I should adjust it? I literally discovered this project today, so I have no idea what I'm working with and I need guidance.

I tried any of the 3:

```yaml
...
modifyLineBreaks:
  textWrapOptions:
    blocksBeginWith:
      0-9: 1
      other: '\\item'
      other: '  \\item'
...
```

It doesn't help. It only makes it worse (kind of like removing **all** the linefeed characters).

**Comment by cmhughes** [comment]
Try
```yaml
modifyLineBreaks:
  textWrapOptions:
    blocksBeginWith:
      other: (?:тест|テスト) 
```

**Comment by Andrew15-5** [comment]
Nice, at least for single width characters it now works. I successfully applied regex for all letters:

```yaml
modifyLineBreaks:
  textWrapOptions:
    blocksBeginWith:
      other: '\w'
```

Output:

```latex
\begin{enumerate}
  \item test test test test test test test test test test test test test test
        test test test test test test test test test test test test test test
        test test test test test test test test test test test test test test
  \item тест тест тест тест тест тест тест тест тест тест тест тест тест тест
        тест тест тест тест тест тест тест тест тест тест тест тест тест тест
        тест тест тест тест тест тест тест тест тест тест тест тест тест тест
        тест
  \item テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
        テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト テスト
        テスト テスト テスト テスト テスト テスト テスト
\end{enumerate}
```

I'm afraid because of Unicode nature, the program can't be changed to treat single-width and double-width (wide) characters differently, right?.

In some languages, like Japanese, there is traditionally no spaces between words. But there could be a sentence ending character like `。`. So I was thinking that _if_ there are no spaces between words, then at least maybe there is a way of splitting (breaking lines) Japanese text/string by special characters like `。`.

**Comment by cmhughes** [comment]
Yes, indeed, and this has come up before.

Text wrapping in latexindent.pl is handled by the text wrap module.

See

https://github.com/cmhughes/latexindent.pl/issues/287#issuecomment-1317785446

**Comment by Andrew15-5** [comment]
Ok. Thankfully, I don't normally use Japanese in my documents, so this is not a huge problem for me. But in this kind of cases when formatter will do something undesired (including nothing at all) there should be an on/off lines which formatter will recognize and won't format a specified block of code/document (e.g., `prettier`, `black`).

https://prettier.io/docs/en/ignore.html
https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#code-style

After a quick search for `ignore` in documentation, I found this: https://latexindentpl.readthedocs.io/en/latest/sec-the-line-switch.html#id6

Which is basically the same but not attached/hard coded into the code. Which is a pain if text file will be edited a lot in different places (formatting config have to be changed too). Is there in-code switches for ignoring block of code in latexindent.pl? If not, can this be a new feature?

**Comment by cmhughes** [comment]
Yes, see:

https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html#lst-noindentblock

https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html#lst-special-verb1-yaml

**Comment by Andrew15-5** [comment]
That's great! See issue #429 as this discussion is slowly changing to a different topic.
