### ISSUE TITLE
Square brackets in maths mode

### ISSUE THREAD

**Issue by Focus** [cmhughes/latexindent.pl#43]
This might be related to #35. When I run latexindent with the option `alwaysLookforSplitBrackets: 1` I get that

``` latex
\[
    x \in (0,1] \cup [2,3]
    \]
    This indents incorrectly
```

This indents as normal when `alwaysLookforSplitBrackets: 0` . Is this behaviour intensional? It seems weird to keep track of the square brackets inside of math environments.

**Comment by Focus** [comment]
Sorry found the answer in the manual.

**Comment by cmhughes** [comment]
Glad you found the answer :) I'm hopeful to fix this issue one day!

**Comment by cmhughes** [comment]
I'm actually going to reopen this issue, as it is a bug and is not intended behaviour (although a work around is provide in the manual). My new approach in https://github.com/cmhughes/latexindent.pl/tree/object-oriented-approach should help to resolve this one day. Watch this space!

**Comment by cmhughes** [comment]
As of https://github.com/cmhughes/latexindent.pl/commit/482c6cf0447ba4263498e2cbc60af7c4b3effa3c, this is fixed; this file is a test case in https://github.com/cmhughes/latexindent.pl/blob/object-oriented-approach/test-cases/specials/Focus-default.tex

**Comment by cmhughes** [comment]
Resolved at https://github.com/cmhughes/latexindent.pl/pull/56
