### ISSUE TITLE
Use `$homeDir`/`$HOME` in `$LATEXINDENT_CONFIG` file

### ISSUE THREAD

**Issue by Andrew15-5** [cmhughes/latexindent.pl#430]
I've found that `$LATEXINDENT_CONFIG` file only contains the paths to configuration files.

https://github.com/cmhughes/latexindent.pl/issues/291#issuecomment-933381735
I would also like to know why this approach has been chosen.

But most importantly, I would like to use any variable that will make `$LATEXINDENT_CONFIG` file reusable between different users. Right now, you have to hard code your username, which is almost always should be avoided (for portability/reusability and security reasons).

---

For example, in the documentation: https://latexindentpl.readthedocs.io/en/latest/sec-appendices.html?highlight=config#linux-1
it should say:

```sh
echo 'export LATEXINDENT_CONFIG="$HOME/latexindent-config.yaml"' >> ~/.profile
```

or even better (to keep user's home directory tidy):

```sh
echo 'export LATEXINDENT_CONFIG="$HOME/.config/latexindent/latexconfig.yaml"' >> ~/.profile
# or this (I don't personally have this variable set):
echo 'export LATEXINDENT_CONFIG="$XDG_CONFIG_DIR/latexindent/latexconfig.yaml"' >> ~/.profile
```

(Different file name was taken from https://latexindentpl.readthedocs.io/en/latest/sec-appendices.html?highlight=config#indentconfig-options.)

instead of:

```sh
echo 'export LATEXINDENT_CONFIG="/home/username/latexindent-config.yaml"' >> ~/.profile
```

---

I want to have the following in my `$LATEXINDENT_CONFIG` file:

```yaml
paths:
- "$homeDir/.config/latexindent/latexindent.yaml"
# or
paths:
- "$HOME/.config/latexindent/latexindent.yaml"
```

Is this possible to do now or in the future?

**Comment by cmhughes** [comment]
You can out whatever path you want in `indentconfig.yaml` including itself, so for example

```
paths:
- /home/cmhughes/indentconfig.yaml
```

And then you should be able to put your settings in `indentconfig.yaml `.

**Comment by Andrew15-5** [comment]
Thanks for the tip, it works. But what about using home dir variable in paths in YAML config file?

**Comment by cmhughes** [comment]
I have no idea how/if that can work, but feel free to take it on if you
like.

I don't have any capacity to do so.

**Comment by Andrew15-5** [comment]
Ok, hopefully soon I will have time to tinkle with this problem.
