### ISSUE TITLE
Text wrapping doesn't work inside an environment

### ISSUE THREAD

**Issue by Andrew15-5** [cmhughes/latexindent.pl#432]
original .tex code
--

```latex
\begin{anyenv}
  text text text text text text text text text text text text text text text text text text
\end{anyenv}
```

yaml settings
--

```yaml
defaultIndent: "  "
modifyLineBreaks:
  textWrapOptions:
    columns: 81
```

actual/given output
--

```latex
\begin{anyenv}
  text text text text text text text text text text text text text text text text text text
\end{anyenv}
```

desired or expected output
--

```latex
\begin{anyenv}
  text text text text text text text text text text text text text text text
  text text text
\end{anyenv}
```

anything else
--

I'm sorry but the regex https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html?highlight=brackets#lst-tw-bf-myenv-yaml looks very confusing (aside from a massive size) and hard to understand (if I'm even referencing the right thing for the issue). Hence, I need help with the problem. I also don't understand if I have to do this long regex for each environment name (it will become even bigger).

I need to format paragraphs inside any environment (`center`, `minipage`, `flushright` etc.) — add linebreaks at 81st column. Well, not exactly any environment (exceptions are any verbatim environments and similar) but you know what I mean.

<details><summary>P.S.</summary>
Sorry for so many issues, I hope I'm not irritating you or anything. :P
</details>

**Comment by cmhughes** [comment]
Yes, that's the one to start from.

```yaml
modifyLineBreaks:
    textWrapOptions:
        blocksFollow:
           other: |-
             (?x)
                \\\]
                |
                \\item(?:\h|\[)
                |
                \\begin\{(?:minipage|flushright|myenv)\} # <--- new bit
```

**Comment by Andrew15-5** [comment]
Could you please describe what this regex actually does/consists of? I know, for example, what `\\item(?:\h|\[)` or `\\begin\{(?:minipage|flushright|myenv)\}` mean (I think `\\\]` refers to `\item[...]`). But all the other bits (i.e., `|-`, `(?x)`, `|`, linefeed `\n`, long indentations) I don't really understand. I'm guessing that `|` is the same as in `(a|b|c)` but there is no parenthesis and there are big indentations + new lines. Maybe it is something that is ignored and simply done for distinguishing between different bits of regex that are actually used by the formatter.

**Comment by Andrew15-5** [comment]
Thank you. Now I more understand than not understand.

I found a new issue where I can't wrap text inside `\caption{...}` and then changed `blocksBeginWith:other:` from `"[а-яёА-ЯЁ]"` to:

```yaml
modifyLineBreaks:
  textWrapOptions:
    blocksBeginWith:
      other: |-
        (?x)
        [а-яёА-ЯЁ]
        |
        \\caption\{
```

And it works. But only outside any environment. If I have a simple:

```latex
\begin{table}
  \caption{text text text text text text text text text text text text text text text text}
\end{table}
```

It doesn't work. But then I added this:

```yaml
modifyLineBreaks:
  textWrapOptions:
    blocksFollow:
      other: |-
        (?x)
        \\\]
        |
        \\item(?:\h|\[)
        |
        \\begin\{(?:table)\}(?:\[.*?\])?
```

And now it works, good. But it doesn't add the indent:

```latex
\begin{table}
  \caption{text text text text text text text text text text text text text text
  text text}
\end{table}
```

If I remove `\\caption\{` then it will add the indent:

```latex
\begin{table}
  \caption{text text text text text text text text text text text text text text
    text text}
\end{table}
```

But if I straighten up the `\caption{...}` line (back into a single line), then it again wouldn't wrap the text.

So I have to

1. add `\\caption\{`
2. format
3. remove `\\caption\{`
4. format

to get the desirable formatting. Is there a way without modifying the config back and forth?

**Comment by cmhughes** [comment]
It looks like you want
```yaml
modifyLineBreaks:
  textWrapOptions:
    blocksFollow:
      other: |-
        (?x)
        \\\]
        |
        \\item(?:\h|\[)
        |
        \\begin\{(?:table)\}(?:\[.*?\])
        |
        \\caption\{
```

**Comment by Andrew15-5** [comment]
Almost. This is an output:

```latex
\begin{table}
  \caption{text text text text text text text text text text text text text text
         text text}
\end{table}
```

So it's not 2 spaces, and it's not after the `\caption{` (9 spaces). Maybe the latter is better.

**Comment by Andrew15-5** [comment]
If I change `\\begin\{(?:table)\}(?:\[.*?\])?` to `\\begin\{(?:table)\}(?:\[.*?\])?\h` then it works:

```latex
\begin{table}
  \caption{text text text text text text text text text text text text text text
           text text}
\end{table}
```

But I added `\h` in the "wrong" place. What if I don't want to add the same formatting for a different macro (e.g., `\notACaption{...}`)? In other words, I want low coupling between `table` environment and `caption` macro (i.e., add `\h` to `\caption` instead of `table`). Maybe I don't something (maybe it is the right way).

**Comment by cmhughes** [comment]
You need to specify `blocksBeginWith` and `blocksFollow` to suit your needs.

**Comment by Andrew15-5** [comment]
I admit I'm so lost I don't even really know the difference sometime, but in the end I think I found a solution (I don't know if it is a correct one):

```yaml
modifyLineBreaks:
  textWrapOptions:
    blocksBeginWith:
      other: |-
        (?x)
        [а-яёА-ЯЁ]
        |
        \\begin\{(?:table)\}(?:\[.*?\])?
    blocksFollow:
      other: |-
        (?x)
        \\\]
        |
        \\item(?:\h|\[)
        |
        \\begin\{(?:center|flushleft|flushright|minipage)\}
        |
        \\(?:caption)\{
```
