### ISSUE TITLE
latexindent.pl is uninstallable on Windows using conda because of missing dependency (perl5)

### ISSUE THREAD

**Issue by junoslukan** [cmhughes/latexindent.pl#446]
On Windows 64-bit, installing `latexindent.pl` by using `mamba install latexindent.pl -c conda-forge` fails with the following error:

```
Could not solve for environment specs
The following package could not be installed
└─ latexindent.pl   is uninstallable because it requires
   └─ perl >=5.32.1,<6.0a0 *_perl5, which does not exist (perhaps a missing channel).
```

Installing `perl` itself with  `mamba install perl` works, however, and `mamba list` shows:

```shell
# Name                    Version                   Build              Channel
perl                      5.32.1.1        2_h57928b3_strawberry    conda-forge
```
Is it possible that this is because the dependency specifies that the version should end with `_perl5`? I notice that some Windows releases end with `_strawberry` (such as version above), while others are missing the `_perl5` suffix.

**Comment by cmhughes** [comment]
@tdegeus can you assist?

**Comment by cmhughes** [comment]
Thanks for this.

Which specific file in this repository would you change?

**Comment by cmhughes** [comment]
Is this query more suited for

https://github.com/conda-forge/latexindent.pl-feedstock

**Comment by cmhughes** [comment]
I think there's only one file in this repository which has anything to do with conda

https://github.com/cmhughes/latexindent.pl/blob/8fc083769259c198d8015d99056ba0976fd9271b/environment.yml

**Comment by cmhughes** [comment]
Thank you very much @tdegeus, that's helpful.

@junoslukan I'm going to close this on this repository, as it seems more suited to the repository linked above. 

Perhaps you can contribute to that project?

**Comment by sjiang95** [comment]
I encountered the same problem on windows.

```shell
> conda install latexindent.pl -c conda-forge
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed
LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides perl >=5.32.1,<6.0a0 *_perl5 needed by latexindent.pl-3.13.2-pl5321hd8ed1ab_0

Could not solve for environment specs
The following package could not be installed
└─ latexindent.pl is not installable because it requires
   └─ perl >=5.32.1,<6.0a0 *_perl5, which does not exist (perhaps a missing channel).
```

However,

```shell
> conda list perl
# packages in environment at D:\ProgramData\miniconda3\envs\latex:
#
# Name                    Version                   Build  Channel
perl                      5.32.1.1        0_haa95532_strawberry
```

Should the dependency of `latexindent.pl` be modified to something like `perl >=5.32.1,<6.0a0 *_perl5 *_strawberry`? But don't know how.
