### ISSUE TITLE
feature request: create cruft directory if it does not exist

### ISSUE THREAD

**Issue by jessestricker** [cmhughes/latexindent.pl#452]
First off, thank you for this awesome tool! ❤️ 

```
latexindent --silent --cruft='./.aux/_latexindent' --overwrite ./root.tex
```

When I invoke latexindent as above, and the cruft directory does not exist yet, 
latexindent fails to format the file and prints this error message:

```
FATAL Could not find directory ./.aux/_latexindent
      Exiting, no indentation done.
```

I usually keep my LaTeX projects in Git and do not commit the `.aux` directory, so when somebody clones the repo they need to manually create the cruft directory before they can start formatting files.

Would it be possible to create the cruft directory and any missing parents when running latexindent?

**Comment by cmhughes** [comment]
Implemented as of https://github.com/cmhughes/latexindent.pl/pull/453

Please leave this open, I'll close it once released (hopefully soon) :)

**Comment by cmhughes** [comment]
This is implemented as of https://github.com/cmhughes/latexindent.pl/releases/tag/V3.22.2, I'll get it uploaded to ctan next.

Thanks so much for your contribution!
