### ISSUE TITLE
Configuring defaultSettings using null-ls

### ISSUE THREAD

**Issue by 777uliahshafar** [cmhughes/latexindent.pl#457]
Hello, I am using your plugin with null-ls for formatting my latex file. However, I'd like to modify configuration such as don't line break a paragraph. Could you address this out, Mr. Thank you.

**Comment by cmhughes** [comment]
Please use the issue template and I'll try to help.

**Comment by cmhughes** [comment]
Duplicate of https://github.com/cmhughes/latexindent.pl/issues/458
