### ISSUE TITLE
Configuring latexindent.pl settings with Null-LS

### ISSUE THREAD

**Issue by 777uliahshafar** [cmhughes/latexindent.pl#458]
Hello,? I am neovim windows 11 user. I'd like to know, how to configure setting latexindent with null-ls. I am using null-ls and mason plugin for source the formatter.  I have never been installed latexindent in my system, just using mason plugin to source it and it works. But I want to modify line brake that wrap each line of my tex file every certain character. I used to write in paragraph without wrap it to second line.  It is weird to see a paragraph in line brake before period.

For lua formatter, I can just put stylua.toml configuration in nvim config directory and it works, however, I could not do the same for latexindent Mr. Hughes.

Please provide the following when posting an issue:

original .tex code
--
\documentclass{article}

\usepackage{fontspec}

\begin{document}

Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur
**cupidatat**. Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.

\end{document}

yaml settings 
--
I tried to create yaml setting, but I think it would not be detected by null-ls. My neovim config was in local app data so I put yaml settings in ~/Users/<username>/AppData/Local/nvim/defaultSettings.yaml. Hopefully null-ls could detect it but it did not. 

desired or expected output
--
I'd like to settings yaml file can be detected by null-ls for formatter. Specifically, disable line break when line hit certain characters. You see cupidatat in the latex file Mr. Hughes, it is the word that went to second line. My simple issue here is how can I configure defaultSettings.yaml for null-ls in neovim. Thank, Cheers.

**Comment by cmhughes** [comment]
It sounds like you want indentconfig.yaml in your home directory, see details at

https://latexindentpl.readthedocs.io/en/latest/sec-indent-config-and-settings.html#indentconfig-yaml-and-indentconfig-yaml

**Comment by cmhughes** [comment]
Can you try creating `~/indentconfig.yaml` that contains the following

```yaml

paths:
- ~/Users//AppData/Local/nvim/defaultSettings.yaml
```

**Comment by 777uliahshafar** [comment]
I believe the defaultSettings  has already been detected. However, I found difficult to determine which script that stop the wrap every certain characters. Could  you help,

**Comment by cmhughes** [comment]
If you show exactly what your desired /expected output is, I'll try to help

**Comment by 777uliahshafar** [comment]
Alright,  I have tex file that has been formatted through null-ls which break the the line in the _cupidatat_ word. My expectation was keep it in the same line. Can I get the paragraph only prevent line break with unlimited word.

original .tex code
--
\documentclass{article}

\usepackage{fontspec}

\begin{document}

Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur
**cupidatat**. Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.

\end{document}

desired or expected output
--
\documentclass{article}

\usepackage{fontspec}

\begin{document}

Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur **cupidatat**. Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.  **...**

\end{document}

Is there a script that prevent the line break only for paragraph type like above.

**Comment by 777uliahshafar** [comment]
I am sorry, my bad. It is not the script and plugin issue. My fault is that I have enabled the textwidth to 300. Later, I will try to figure it out before raise the issue. Thank you very much by the way for the knowledge of configuring latexindent default settings. Cheers Mr. Hughes.

**Comment by cmhughes** [comment]
Do you need any further information from me?

**Comment by 777uliahshafar** [comment]
All good Mr. Hughes, Thank you for indentconfig, at least I have more options now.
