### ISSUE TITLE
Comment after \item affects its alignment

### ISSUE THREAD

**Issue by dpo** [cmhughes/latexindent.pl#467]
Please provide the following when posting an issue:

original .tex code
--
```latex
\begin{enumerate}
  \item One
  \item
    Two.
\end{enumerate}

\begin{enumerate}
  \item One
  \item%
    Two.
\end{enumerate}
```

yaml settings
--
All defaults.

actual/given output
--
```latex
\begin{enumerate}
        \item One
        \item
              Two.
\end{enumerate}

\begin{enumerate}
        \item One
              \item%
              Two.
\end{enumerate}
```

desired or expected output
--
```latex
\begin{enumerate}
        \item One
        \item
              Two.
\end{enumerate}

\begin{enumerate}
        \item One
        \item%
        Two.
\end{enumerate}
```

anything else
--
Why does the comment after `\item` affect its alignment? It looks as though the second `\item` is being mistaken as part of the contents of the first.

**Comment by cmhughes** [comment]
Many thanks, this is a bug. I hope to get to it soon.

**Comment by cmhughes** [comment]
Fixed as of https://github.com/cmhughes/latexindent.pl/commit/682d46494cc35144c123d51ec57f55c5c3e29771, a release to follow soon, hopefully.

**Comment by cmhughes** [comment]
Implemented at https://github.com/cmhughes/latexindent.pl/releases/tag/V3.23

**Comment by dpo** [comment]
Thank you!
