### ISSUE TITLE
About 3.23 release

### ISSUE THREAD

**Issue by chenrui333** [cmhughes/latexindent.pl#468]
👋  it looks like [3.23 release build was not completed](https://github.com/cmhughes/latexindent.pl/actions/runs/6132551809/job/16643651399), raise this issue for awareness. Thanks!

```
#9 0.051 fatal: not a git repository (or any of the parent directories): .git
#9 ERROR: process "/bin/sh -c git checkout \"${LATEXINDENT_VERSION}\" && echo \"Y\" | perl latexindent-module-installer.pl" did not complete successfully: exit code: 128
------
 > [5/8] RUN git checkout "V3.23" && echo "Y" | perl latexindent-module-installer.pl:
0.051 fatal: not a git repository (or any of the parent directories): .git
------
Dockerfile:37
--------------------
  35 |     WORKDIR /latexindent.pl/helper-scripts
  36 |     
  37 | >>> RUN git checkout "${LATEXINDENT_VERSION}" && echo "Y" | perl latexindent-module-installer.pl
  38 |     
  39 |     WORKDIR /latexindent.pl/build
--------------------
ERROR: failed to solve: process "/bin/sh -c git checkout \"${LATEXINDENT_VERSION}\" && echo \"Y\" | perl latexindent-module-installer.pl" did not complete successfully: exit code: 128
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c git checkout \"${LATEXINDENT_VERSION}\" && echo \"Y\" | perl latexindent-module-installer.pl" did not complete successfully: exit code: 128
```

relates to https://github.com/Homebrew/homebrew-core/pull/141875

**Comment by cmhughes** [comment]
Yes, thank you, I am aware of this but am unsure how to fix it.

@eggplants any ideas?

**Comment by chenrui333** [comment]
@cmhughes should be covered by #469

**Comment by eggplants** [comment]
@cmhughes The retried workflow was running on `V3.23` (6b8a4cc80d0a5fb877f88c3f8b82d97d3bb28507) branch. You should remove and recreate `V3.23` tag for 4fc7e7e8308f5b8d0e87ee0b30a8106402bf5090.

https://github.com/cmhughes/latexindent.pl/actions/runs/6132551809/job/16656958201

**Comment by eggplants** [comment]
```
git checkout main  # HEAD is 4fc7e7e...
git tag -d V3.23
git push origin :V3.23
git tag V3.23
git push --tags

**Comment by cmhughes** [comment]
@eggplants  @chenrui333  many thanks both, I've done as @eggplants suggested, re-run the workflow, and it has passed.

So, this issue should now be resolved.

Thanks again to you both.

**Comment by chenrui333** [comment]
💯
