### ISSUE TITLE
Output of `latexindent` isn't stable (specialBeginEnd) 

### ISSUE THREAD

**Issue by arodomanov** [cmhughes/latexindent.pl#477]
Hi,

I'm trying to make `latexindent` automatically indent the text inside any (round) parentheses (in other words, to treat `(` and `)` as the beginning and end, respectively, of a certain environment).

To achieve this, I've tried to declare a `specialBeginEnd` block (see the `latexindent.yaml` file below).

At first, this seemed to work fine and produced the result I wanted. However, I then noticed that **the result isn't stable**.  Specifically, the output changes if you run `latexindent` again (one or several times) without changing anything. In particular, I managed to obtain two different outputs after running `latexindent` several times on the same file with the same settings and by using the same command (see below).

From my limited understanding (after inspecting the log file), it looks as if the problem is that each run of `latexindent` joins the settings from `specialBeginEnd` in an arbitrary order which results in different internal regular expressions.

Please confirm if it's a bug, or if I'm misusing the `specialBeginEnd` feature.  

Original .tex code (`source.tex`)
--
```latex
$
  a
  +
  (
    b + c
  )
  =
  d
$
and
$
  e + f = g
$
```

yaml settings (`latexindent.yaml`)
--
```yaml
defaultIndent: "  "

specialBeginEnd:
  specialBeforeCommand: 1

  parentheses:
    begin: \(
    end: \)
    lookForThis: 1
```

The command used to run `latexindent`
--
```shell
latexindent -l latexindent.yaml -o=+-mod.tex source.tex
```

Actual output 1 [good] (`source-mod.tex`)
--
```latex
$
  a
  +
  (
    b + c
  )
  =
  d
$
and
$
  e + f = g
$
```

Actual output 2 [bad] (`source-mod.tex`)
--
```latex
$
  a
  +
  (
    b + c
  )
  =
  d
  $
    and
  $
  e + f = g
$
```

Desired or expected output
--
The desired output is output 1 [good] presented above.

Version of `latexindent`
--
```
3.23.1, 2023-09-13
```

**Comment by cmhughes** [comment]
Many thanks, that's a helpful example. 

Certainly not expected behaviour, and definitely a bug. I'll look into it.

**Comment by cmhughes** [comment]
> Note to self, maybe try removing the g switch from the find and replace in
> 
> https://github.com/cmhughes/latexindent.pl/blob/main/LatexIndent/Special.pm

This didn't work

**Comment by cmhughes** [comment]
Implemented and released at https://github.com/cmhughes/latexindent.pl/releases/tag/V3.23.2

thanks again!

**Comment by arodomanov** [comment]
Thanks a lot for such a quick fix!

**Comment by cmhughes** [comment]
You're welcome, and thank you for such a clear, concise example. Happy
indenting!
