### ISSUE TITLE
Perl regex warnings

### ISSUE THREAD

**Issue by pat-s** [cmhughes/latexindent.pl#48]
I get a bunch (like 50+) of Perl related regex warnings of unescaped braces when executing latexindent from command line.

System: macOS 10.12, TexLive2016, latexindent version 2.1R

```
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/^\s*%\*\s*\\begin{ <-- HERE (.*?)}/ at /Library/TeX/texbin/latexindent line 1047.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/^\s*%\*\s*\\end{ <-- HERE (.*?)}/ at /Library/TeX/texbin/latexindent line 1073.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/^%\s*\\end{ <-- HERE (.*?)}/ at /Library/TeX/texbin/latexindent line 1199.
```

Seems to be related to this Perl core update: http://unix.stackexchange.com/questions/238539/automake-error-unescaped-left-brace-in-regex-is-deprecated

**Comment by cmhughes** [comment]
Yes, indeed :) Many thanks for reporting it; see https://github.com/cmhughes/latexindent.pl/issues/21#issue-52050472

The develop version has it fixed -- I'm currently working on a new approach (which also has this fixed).

**Comment by pat-s** [comment]
Ahh yes, browsing old issues is something I should do more often. 

Is there a guide how to install the dev version from Github? Checked the manual and readme but found none. Would really like to get rid of these messages! 
macOS, so some "make install" hint would be sufficient.

I really like your tool and it's arar integration, thanks for your work and keep it up!

**Comment by cmhughes** [comment]
Thanks very much for your kind words and encouragement :)

You can grab the `develop` version from here: https://raw.githubusercontent.com/cmhughes/latexindent.pl/develop/latexindent.pl

I'm currently working on v3.0; I'll see if it might be possible to release a v2.2 in the mean time so that this issue is taken care of.

**Comment by pat-s** [comment]
Thanks for the link!

I guess at least a note in the README with the link to the dev version would be sufficient for must users until version v3.0 is finished. 

A v2.2 release would be highly appreciated of course!
