### ISSUE TITLE
textwrap not working correctly

### ISSUE THREAD

**Issue by RitschAlex** [cmhughes/latexindent.pl#487]
Please provide the following when posting an issue:

original .tex code
--
```
\section{Einleitung}
Seit 2010 hat sich die Anzahl der psychischen Erkrankungen und die damit verbundenen Fehltage um 56\% erhöht. Laut dem Fehlzeiten-Report 2022 des wissenschaftlicehn Instituts der AOK (WIdO) stellen dars
\subsection{Problemstellung}
\subsection{Zielsetzung}
\subsection{Aufbau der Arbeit}
```

yaml settings
--
    textWrapOptions:
        columns: 20
        multipleSpacesToSingle: 1              
        removeBlockLineBreaks: 1
        when: before                        # before/after
        comments: 
           wrap: 0                          # 0/1
           inheritLeadingSpace: 0           # 0/1
        blocksFollow:
           headings: 1                      # 0/1
           commentOnPreviousLine: 1         # 0/1
           par: 1                           # 0/1
           blankLine: 1                     # 0/1
           verbatim: 1                      # 0/1
           filecontents: 1                  # 0/1
           other: \\\]|\\item(?:\h|\[)      # regex
        blocksBeginWith:
           A-Z: 1                           # 0/1
           a-z: 1                           # 0/1
           0-9: 0                           # 0/1
           other: 0                         # regex
        blocksEndBefore:
           commentOnOwnLine: 1              # 0/1
           verbatim: 1                      # 0/1
           filecontents: 1                  # 0/1
           other: \\begin\{|\\\[|\\end\{    # regex
        huge: overflow                      # forbid mid-word line breaks
        separator: ""

actual/given output
--
INFO:  latexindent.pl version 3.23.2, 2023-09-23, a script to indent .tex files
       latexindent.pl lives here: C:/Users/ritsc/AppData/Local/Programs/MiKTeX/scripts/latexindent/
       Sun Oct  8 01:44:15 2023
       Filename: .\Datenanalyse\Chapters\Einleitung.tex
INFO:  Processing switches:
       -m|--modifylinebreaks: modify line breaks
INFO:  Directory for backup files and indent.log:
       .\Datenanalyse\Chapters
INFO:  Perl modules are being loaded from the following directories:
       C:/Strawberry/perl/lib/FindBin.pm
       C:/Strawberry/perl/vendor/lib/YAML/Tiny.pm
       C:/Strawberry/perl/lib/File/Copy.pm
       C:/Strawberry/perl/lib/File/Basename.pm
       C:/Strawberry/perl/lib/Getopt/Long.pm
       C:/Strawberry/perl/vendor/lib/File/HomeDir.pm
INFO:  LatexIndent perl modules are being loaded from, for example:
       C:/Users/ritsc/AppData/Local/Programs/MiKTeX/scripts/latexindent/LatexIndent/Document.pm
INFO:  YAML settings read: defaultSettings.yaml
       Reading defaultSettings.yaml from C:/Users/ritsc/AppData/Local/Programs/MiKTeX/scripts/latexindent/defaultSettings.yaml
INFO:  YAML reading settings
       Home directory is C:\Users\ritsc
       latexindent.pl didn't find indentconfig.yaml or .indentconfig.yaml
       see all possible locations: https://latexindentpl.readthedocs.io/en/latest/sec-appendices.html#indentconfig-options)
INFO:  Phase 1: searching for objects
INFO:  Phase 2: finding surrounding indentation
INFO:  Phase 3: indenting objects
INFO:  Phase 4: final indentation check
INFO:  Output routine:
       Not outputting to file; see -w and -o switches for more options.
       --------------
INFO:  Please direct all communication/issues to:
        https://github.com/cmhughes/latexindent.pl

```
\section{Einleitung}
Seit 2010
hat sich
die
Anzahl
der
psychischen
Erkrankungen
und die
damit
verbundenen
Fehltage
um 56\%
erhöht.
Laut dem
Fehlzeiten-Report
2022 des
wissenschaftlicehn
Instituts
der AOK
(WIdO)
stellen
\subsection{Problemstellung}
\subsection{Zielsetzung}
\subsection{Aufbau der Arbeit}
```

desired or expected output
--
```
\section{Einleitung}
Seit 2010 hat sich die Anzahl der psychischen Erkrankungen und 
die damit verbundenen Fehltage um 56\% erhöht. 
Laut dem Fehlzeiten Report 2022 des wissenschaftlicehn Instituts der AOK (WIdO) stellen
\subsection{Problemstellung}
\subsection{Zielsetzung}
\subsection{Aufbau der Arbeit}
```

anything else
--
I would like the text wrapping behave like the Example 78 in the [documentation](https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#text-wrap-simple-examples). I'm using neovim with null-ls and with the standard defaultSettings.yaml the text gets always formatted like shown above.

**Comment by cmhughes** [comment]
Can you show the actual output? (not the log file)

**Comment by cmhughes** [comment]
Using the settings
```yaml
modifyLineBreaks:
   textWrapOptions:
       columns: 20
```
gives the following
```tex
\section{Einleitung}
Seit 2010 hat sich
die Anzahl der
psychischen
Erkrankungen und
die damit
verbundenen
Fehltage um 56\%
erhöht. Laut dem
Fehlzeiten-Report
2022 des
wissenschaftlicehn
Instituts der AOK
(WIdO) stellen dars
\subsection{Problemstellung}
\subsection{Zielsetzung}
\subsection{Aufbau der Arbeit}
```

**Comment by cmhughes** [comment]
The above YAML settings are given in https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html#lst-textwrap1-yaml
