### ISSUE TITLE
Overwriting file when there has been no change. 

### ISSUE THREAD

**Issue by Tchiller** [cmhughes/latexindent.pl#5]
Hello,

% arara: indent: { overwrite : yes } will allways save/overwrite the file, even if there has been no change at all. In TeXnicCenter, after each run the editor will tell me, that the file has been changed outside the editor. This is annoying if just small changes are made or several runs with no changes at all. 
I will report this issue to TeXnicCenter as well, as they could do a real diff before throwing this message. But maybe it would be able to latexindent to differ between changed and non changed files. In second case, a new output.tex, overwritten input.tex or BackUp-file is needed. 

Thanks a lot for such a great tool.

**Comment by cmhughes** [comment]
For reference, see also the `-wd` switch https://github.com/cmhughes/latexindent.pl/blob/main/documentation/changelog.md#v317-march-25-2022
