### ISSUE TITLE
Unexpected indent of curly braces block

### ISSUE THREAD

**Issue by MrConnorKenway** [cmhughes/latexindent.pl#501]
original .tex code
--
```tex
\section { hi }
abc
{ xyz }
```

actual/given output
--
```tex
\section { hi }
abc
    { xyz }
```

desired or expected output
--
```tex
\section { hi }
abc
{ xyz }
```

anything else
--
I'm sorry I didn't use a template. Could you help me understand why latexindent adds a tab before `{ xyz }`?

**Comment by cmhughes** [comment]
Please use the issue template and I'll try to help.

**Comment by MrConnorKenway** [comment]
Hi, I've updated the issue. Sorry for the trouble : (

**Comment by cmhughes** [comment]
Thanks, that's great.

If we use
```yaml
noAdditionalIndentGlobal:
  namedGroupingBracesBrackets: 1    # 0/1
```
then we receive
```tex
\section { hi }
abc
{ xyz }
```

**Comment by MrConnorKenway** [comment]
Thank you for your help! It indeed works, but when combining with other configs, it doesn't work again.

The original tex
--
```tex
\section { hi }
abc abc abc abc abc abc
{ xyz }
```

The command
--
`latexindent -m -y "modifyLineBreaks:textWrapOptions:columns:25,modifyLineBreaks:textWrapOptions:blocksBeginWith:other:\\\\,noAdditionalIndentGlobal:namedGroupingBracesBrackets:1"`

Actual output
--
```
\section { hi }
abc abc abc abc abc abc
        { xyz }
```

**Comment by cmhughes** [comment]
I'll happily look at this again, but before I do, can you provide your complete configuration.

**Comment by MrConnorKenway** [comment]
That's all the config, I'm using the command line and I don't have any local config.
![image](https://github.com/cmhughes/latexindent.pl/assets/32333772/058e503d-b35b-4ec6-9f20-c18f3c10322e)

**Comment by cmhughes** [comment]
You need to use non-capturing parenthesis `(?:\\\\)` in your call, as in the following:
```
latexindent -m -y "modifyLineBreaks:textWrapOptions:columns:25,modifyLineBreaks:textWrapOptions:blocksBeginWith:other:(?:\\\\),noAdditionalIndentGlobal:namedGroupingBracesBrackets:1" issue-501a.tex
```

**Comment by MrConnorKenway** [comment]
Thank you so much for answering my dumb question!
