### ISSUE TITLE
/usr/local/lib , not /usr/local/bin

### ISSUE THREAD

**Issue by hymie0** [cmhughes/latexindent.pl#509]
defaultSettings.yaml and the LatexIndent directory belong in /usr/local/lib , not /usr/local/bin

**Comment by hymie0** [comment]
The file `path-helper-files/CMakeLists.txt` defines the following installation locations as being in/under `/usr/local/bin/`

```
install(FILES ../defaultSettings.yaml
        DESTINATION bin)

install(DIRECTORY ../LatexIndent
        DESTINATION bin)
```

The program `latexindent.pl` specifies the location of the `LatexIndent` directory as `/usr/local/bin/LatexIndent/`

```
use lib $FindBin::RealBin;
use LatexIndent::Document;
```

The file `LatexIndent/GetYamlSettings.pm` specifies the location of the `defaultSettings.yaml` file as `/usr/local/bin/defaultSettings.yaml`

```
    $defaultSettings = YAML::Tiny->read("$FindBin::RealBin/defaultSettings.yaml")
```

`/usr/local/bin` is not the proper location for auxiliary files such as these.

**Comment by cmhughes** [comment]
Do you have a reference for this?

**Comment by hymie0** [comment]
I'm not interested in debating basic Unix with you.
