### ISSUE TITLE
Formatting of listings

### ISSUE THREAD

**Issue by mnsgs** [cmhughes/latexindent.pl#515]
Please provide the following when posting an issue:

original .tex code
--
```
\documentclass{article}

\usepackage{listings}

\begin{document}

Listing test
  \begin{lstlisting}
Important listing
            \end{lstlisting}

Itemize test
  \begin{itemize}
\item test item
            \end{itemize}

\end{document}
```

yaml settings
--
None

actual/given output
--
```
\documentclass{article}

\usepackage{listings}

\begin{document}

Listing test
\begin{lstlisting}
Important listing
            \end{lstlisting}

Itemize test
\begin{itemize}
        \item test item
\end{itemize}

\end{document}
```

desired or expected output
--
```
\documentclass{article}

\usepackage{listings}

\begin{document}

Listing test
\begin{lstlisting}
Important listing
\end{lstlisting}

Itemize test
\begin{itemize}
        \item test item
\end{itemize}

\end{document}
```

anything else
--
Formatting applied using the logic

`latexindent test.tex`

I would expect `\end{lstlisting}` to be indented to the same level as of the `\begin{lstlisting}` as is the case for the `itemize` environment which is added for illustration purpose

--
Context

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

```
$ latexindent -v
3.23.6, 2024-01-17
```

**Comment by cmhughes** [comment]
This is a verbatim environment, if you don't want it to be verbatim then you can use
```
verbatimEnvironments:
  lstlisting: 0
```

**Comment by cmhughes** [comment]
Thanks for the follow up.

Verbatim blocks are deliberately left alone, this is not a bug.

Perhaps you might like noAdditionalIndent?

**Comment by mnsgs** [comment]
Thanks for clarifying
