### ISSUE TITLE
Option for local `indentconfig.yaml` or `paths:` in `latexindent.yaml`

### ISSUE THREAD

**Issue by torik42** [cmhughes/latexindent.pl#516]
I would like to have an option to specify local `indentconfig.yaml` files, or even better, include the `paths:` functionality in all the yaml configuration files.

Please correct me, if this is already possible. I couldn’t find anything in the documentation and couldn’t make it work. I tried to use
```yaml
# latexindent.yaml
paths:
- /absolute/path/to/config.yaml
```
in the local directory and call latexindent with `-l` switch. The `indent.log` shows
```
INFO:  YAML settings read: -l switch
       Multiple localSettings found, separated by commas:
       localSettings.yaml, latexindent.yaml, .localSettings.yaml, .latexindent.yaml
       Adding latexindent.yaml to YAML read paths
INFO:  YAML settings, reading from the following files:
       Reading USER settings from latexindent.yaml
       ---
       paths:
         - /absolute/path/to/config.yaml

INFO:  Backup procedure (-w flag active):
```
So the `/absolute/path/to/config.yaml` was never read.

The idea is to have several configuration files with different replacements/configurations (the focus is on replacements, I think) and then choose the correct one according to the project. If the `paths:` entry would be parsed for every configuration file, one could even nest configuration files. This would be useful to allow for fine-grained selection and still providing a preselection in a single file which just loads multiple paths.

**Comment by cmhughes** [comment]
Many thanks, this sounds reasonable and, I hope, fairly straight forward to implement.

**Comment by cmhughes** [comment]
For my reference, it'll be this loop that needs updating

https://github.com/cmhughes/latexindent.pl/blob/90523104cfa824d7642acae9d6f47664373d8694/LatexIndent/GetYamlSettings.pm#L373

Note that it'll need to be documented that paths can not be specified using the y switch.

**Comment by torik42** [comment]
If anyone else is interested, as a workaround, I currently use
```bash
export LATEXINDENT_CONFIG=$(pwd)/indentconfig.yaml
```
to load a specific subset of additional rules with
```yaml
# indentconfig.yaml
paths:
- path/to/default.yaml
- path/to/other-config-1.yaml
- path/to/other-config-2.yaml
```

It’s still not possible to nest them, but one can have multiple lists for different purposes.

**Comment by cmhughes** [comment]
This is implemented as of https://github.com/cmhughes/latexindent.pl/commit/1a629f2c9972bff270f459dee5104f188f0b6c61

It'll be part of the next release. Please leave this issue open until I've made the release, hopefully coming soon...

**Comment by cmhughes** [comment]
implemented and released at https://github.com/cmhughes/latexindent.pl/releases/tag/V3.24

**Comment by cmhughes** [comment]
https://latexindentpl.readthedocs.io/en/latest/sec-appendices.html#paths-demonstration
