### ISSUE TITLE
noindent not working for file

### ISSUE THREAD

**Issue by maetra** [cmhughes/latexindent.pl#52]
I try to use an noident-environment for table as `latexindent ` has issues with a custom table (using a rotatebox and manual line break inside a cell). After running latexindent on this file `some text` gets indented, even though the `%\begin{noindent}` command should avoid this.

```
\documentclass[]{beamer}

\begin{document}

\begin{frame}
		
	%\begin{noindent}
sasf asf 
	%\end{noindent}
		
\end{frame}

\end{document}
```

I am running the latest version from the repository.

**Comment by cmhughes** [comment]
I think this is because the lines that have `%\begin{noindent}` and `%\end{noindent}` should not have any leading space, i.e, you'd need to use:

```
\begin{frame}
		
%\begin{noindent}
sasf asf 
%\end{noindent}
		
\end{frame}
```

Does this fix the issue? :)

As an aside, in version 3.0 (https://github.com/cmhughes/latexindent.pl/tree/object-oriented-approach), spaces are allowed ahead of each of these; in fact, v3.0 both `%\begin{noindent}` and `\end{noindent}` don't need to be on their own lines.

**Comment by cmhughes** [comment]
PS: I must apologise for not specifying this explicitly in the manual.

Depending on how development goes with V3.0, I might release a V2.2.1 at Christmas that fixes this issue, or at least, documents it more clearly.

**Comment by maetra** [comment]
Thanks for the quick reply, but this does not seem to work. Also `%\begin{noindent}` is indented after running the `latexindent` script. 

Getting rid of `\begin{frame} \end{frame}` however solves the problem, but this is of course no real solution.

**Comment by cmhughes** [comment]
I think, for the moment, if you put the `%\begin{noindent}` *outside* of the `\begin{frame}`:

```
%\begin{noindent}
\begin{frame}
....
\end{frame}
%\end{noindent}```

V2.* assumes that you would put the `noindent` block at the outer-most place -- as you've shown, this is clearly not ideal.  

I'll do the following: label this as a bug, and get a patch together for v2.2.1 and get that uploaded asap, Christmas at the latest. Apologies, and thanks very much for reporting this :)

**Comment by cmhughes** [comment]
Resolved at https://github.com/cmhughes/latexindent.pl/pull/56
