### ISSUE TITLE
Indentation in tabular*

### ISSUE THREAD

**Issue by Pberg22** [cmhughes/latexindent.pl#526]
Please provide the following when posting an issue:

original .tex code
--
*Please paste your .tex code here. Please note in answering your issue, I may add the code you provide to the test-cases directory. Please detail explicitly if you would prefer me not to do so.*.

```
\documentclass{article}
\begin{document}
\begin{center}
  \begin{tabular*}{\linewidth}{ll}
    1&2\\
    32 &4\\
  \end{tabular*}
\end{center}
\end{document}
```

yaml settings
--
*Please paste your YAML settings (if any) here*

actual/given output
--
*Please paste the output you receive here*

```
\begin{center}
  \begin{tabular*}{\linewidth}{ll}
    1&2\\
    32 &4\\
  \end{tabular*}
\end{center}
```

desired or expected output
--
*Please paste your desired/expected output here; that is, what do you want the output to look like*

```
\begin{center}
  \begin{tabular*}{\linewidth}{ll}
    1  & 2 \\
    32 & 4 \\
  \end{tabular*}
\end{center}
```

anything else
--
*Please put any comments or anything else here :)*

I'm using the LaTeX Workshop extension for Visual Studio Code. 
The formatting of my .tex text seem to work fine in all cases, except when I'm using tabular* environment, where nothing happens when I try to format the text. I'm new to both LaTeX and posting issues on GitHub - just tell me if I missed anything.

**Comment by cmhughes** [comment]
Thanks for this. Can you try the following settings

latexindent.yaml
-
```yaml
lookForAlignDelims:
        tabular*: 1
```

You call it with
```
latexindent.pl -l my file.tex
```

**Comment by Pberg22** [comment]
Ohh now it works!
I was missing the line `tabular*: 1` in my `defaultSettings.yaml` file.
Adding it directly after the options of `tabular:` fixed it when using the workshop short `Ctrl K + Ctrl F`

**Comment by cmhughes** [comment]
Many thanks.

I think I'll update defaultSettings to have this for the future.
