### ISSUE TITLE
[latexindent.exe] -GCString switch cannot run normally

### ISSUE THREAD

**Issue by saxyx** [cmhughes/latexindent.pl#531]
Please provide the following when posting an issue:

GCString.tex code
--
\begin{table}[H]
  \centering
  \begin{tblr}{
      hlines,
      vlines,
      cells = {c,m}}
    5:30        & 起床 & 12:30～14:00 & 午休  \\
    6:00～7:00   & 早操 & 14:00～17:30 & 集训  \\
    7:00～7:50   & 早餐 & 17:30～18:30 & 晚餐  \\
    7:50～11:00  & 集训 & 19:00～21:00 & 晚自习 \\
    11:00～12:30 & 午餐 & 23:00       & 熄灯  \\
  \end{tblr}
\end{table} 

---

If I run `latexindent.exe "GCString.tex" -y="defaultIndent: '    '" -GCString  -o=++` in cmd, the error message is
```
Can't locate object method "new" via package "Unicode::GCString" at E:\Personal\Temp\par-6c656e6f766f\cache-915a8c0064c09de5b911dab5529ae5b236f00de7\inc\lib/LatexIndent/AlignmentAtAmpersand.pm line 1789.
``` 

You can see [https://github.com/rschupp/PAR-Packer/issues/87](https://github.com/rschupp/PAR-Packer/issues/87)  for more details.

### Solution: 

When using `pp` to package the program in cmd, use `set PAR_VERBATIM=1`, that is
```
set PAR_VERBATIM=1 && pp -M Win32::Unicode --addfile="defaultSettings.yaml;lib/LatexIndent/defaultSettings.yaml" --cachedeps=scancache --output latexindent.exe latexindent.pl
```

**Comment by cmhughes** [comment]
Great, thanks. Can you submit a pull request?

**Comment by cmhughes** [comment]
resolved at https://github.com/cmhughes/latexindent.pl/releases/tag/V3.23.8

thanks to @saxyx  for fixing!
