### ISSUE TITLE
Feature Request: Support spreadtab block

### ISSUE THREAD

**Issue by Hzbeta** [cmhughes/latexindent.pl#535]
Spreadtab  allows us to construct tables in a manner similar to a spreadsheet. The cells of a table have row and column indices and these can be used in formulas to generate values in other cells. Detailed instructions can be found [here](https://mirror.las.iastate.edu/tex-archive/macros/latex/contrib/spreadtab/spreadtab-en.pdf).

![image](https://github.com/cmhughes/latexindent.pl/assets/6748577/f89bd12e-970e-481b-a95a-6036e97cc146)

I hope latexindent.pl can support formatting of the table content in `spreadtab` block, just like normal `tabular` block!

For example, no yaml setting, original .tex code
--
```tex
\begin{spreadtab}{{tabular}{r*6c}} % or \spreadtab{{tabular}{r*6c}}
@Ages & 10 & 11 & 12 & 13 & 14 & 15\\
@Number & 5 & 8 & 20 & 55 & 9 & 3\\\hline
@Average&\multicolumn{6}{l}{:={sumprod(b1:g1;b2:g2)/sum(b2:g2)}}
\end{spreadtab} % or \endspreadtab
```

actual/given output
--
```tex
\begin{spreadtab}{{tabular}{r*6c}} % or \spreadtab{{tabular}{r*6c}}
    @Ages & 10 & 11 & 12 & 13 & 14 & 15\\
    @Number & 5 & 8 & 20 & 55 & 9 & 3\\\hline
    @Average&\multicolumn{6}{l}{:={sumprod(b1:g1;b2:g2)/sum(b2:g2)}}
\end{spreadtab} % or \endspreadtab 
```

desired or expected output
--
```tex
\begin{spreadtab}{{tabular}{r*6c}} % or \spreadtab{{tabular}{r*6c}}
    @Ages    & 10                                                      & 11 & 12 & 13 & 14 & 15 \\
    @Number  & 5                                                       & 8  & 20 & 55 & 9  & 3  \\\hline
    @Average & \multicolumn{6}{l}{:={sumprod(b1:g1;b2:g2)/sum(b2:g2)}}
\end{spreadtab} % or \endspreadtab 
```

anything else
--
Thanks for such a great LaTeX formatting tool! :)

**Comment by cmhughes** [comment]
Great, thanks, will do :)

**Comment by cmhughes** [comment]
If anyone wants to take this on, it should just be adding `spreadtab` to the `lookForAlignDelims` field. Should be a nice way to get started on contributing.

**Comment by cmhughes** [comment]
This is implemented as of https://github.com/cmhughes/latexindent.pl/commit/8e089c530e08235655e9d7ee67b9c3cdd7635851

It'll be part of the next release. Please leave this issue open until I've made the release, hopefully coming soon...

**Comment by cmhughes** [comment]
implemented and released at https://github.com/cmhughes/latexindent.pl/releases/tag/V3.24
