### ISSUE TITLE
Error "Can't open file" when using `-g` key with nontrivial path

### ISSUE THREAD

**Issue by arodomanov** [cmhughes/latexindent.pl#537]
Hi,

After the recent update of `latexindent`, I started receiving a new error every time I try to run the script with the `-g /dev/null` flag (on Linux).

## Problem description

Here is a concrete example. I have the following very simple `.tex` file:
```latex
% main.tex
Just some text.
```

I run the following command in the terminal:
```shell
latexindent -g /dev/null main.tex
```
and receive the error code 2 with the following output:
```
% main.tex
Just some text.
Can't open file: No such file or directory at /usr/local/texlive/2024/texmf-dist/scripts/latexindent/LatexIndent/UTF8CmdLineArgsFileOperation.pm line 73.
```

It seems that there is nothing special about `/dev/null` as the command fails in the exact same way if I run, for example,
```shell
latexindent -g /tmp/latexindent-log.txt main.tex
```
However, strangely enough, everything works fine once I run the above example without the `/tmp/` in the path:
```shell
latexindent -g latexindent-log.txt main.tex
```

## Version of latexindent

I'm using the most recent version `3.23.9, 2024-04-06` but the problem didn't appear in the version a few months back (I don't remember the exact number).

**Comment by cmhughes** [comment]
@fengzyf can you take a look at this?

**Comment by cmhughes** [comment]
implemented and released at https://github.com/cmhughes/latexindent.pl/releases/tag/V3.24
