### ISSUE TITLE
[windows] conda installation fail due to perl version

### ISSUE THREAD

**Issue by sjiang95** [cmhughes/latexindent.pl#539]
Cannot install on windows via conda

actual/given output
--

```shell
> conda install latexindent.pl -c conda-forge
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed
LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides perl >=5.32.1,<6.0a0 *_perl5 needed by latexindent.pl-3.13.2-pl5321hd8ed1ab_0

Could not solve for environment specs
The following package could not be installed
└─ latexindent.pl is not installable because it requires
   └─ perl >=5.32.1,<6.0a0 *_perl5, which does not exist (perhaps a missing channel).
```

However,

```shell
> conda list perl
# packages in environment at D:\ProgramData\miniconda3\envs\latex:
#
# Name                    Version                   Build  Channel
perl                      5.32.1.1        0_haa95532_strawberry
```

desired or expected output
--
Successful installation.

anything else
--
I have searched and found the same issue is remained unsolved: #446

Should the dependency of `latexindent.pl` be modified to something like `perl >=5.32.1,<6.0a0 *_perl5 *_strawberry`? But don't know how.

**Comment by cmhughes** [comment]
@tdegeus can you assist?

**Comment by cmhughes** [comment]
I'll look into this. In the mean time, there's a standalone executable latexindent.exe

**Comment by cmhughes** [comment]
Is this more suited to https://github.com/conda-forge/latexindent.pl-feedstock

**Comment by sjiang95** [comment]
Hello @cmhughes , could you please transfer this issue to https://github.com/conda-forge/latexindent.pl-feedstock ?

**Comment by cmhughes** [comment]
I don't maintain that repository.

Can you copy and paste it there?
