### ISSUE TITLE
Format tabular for fullwidth fonts

### ISSUE THREAD

**Issue by rikutons** [cmhughes/latexindent.pl#540]
Some characters have larger width than other characters. For example, all CJK characters are fullwidth font. But now latexindent treats these characters as 1-width , that makes shifted \\ and & on tabular environment.

Can you add an option to treat fullwidth characters as 2-width characters?

original .tex code
--
```
\begin{tabular}{cc}
  a   & aaa \\
  abc & aaaaaa \\
  a   & あああ \\
\end{tabular}
```
yaml settings
--
`none`

actual/given output
--
```
\begin{tabular}{cc}
  a   & aaa    \\
  abc & aaaaaa \\
  a   & あああ    \\
\end{tabular}
```
desired or expected output
--
```
\begin{tabular}{cc}
  a   & aaa    \\
  abc & aaaaaa \\
  a   & あああ \\
\end{tabular}
```
(Seems like Github is not using monospace font on codeblock for fullwidth char,  
so I add screenshot with [proper monospace font](https://github.com/miiton/Cica))
![image](https://github.com/cmhughes/latexindent.pl/assets/27684488/8fa87882-5844-4fc1-9dae-ab6875d6a8e5)

anything else
--
https://metacpan.org/pod/Text::CharWidth can detect char's width. But idk how to use with that algorithm. So need help to implement if this feature got accepted.
https://github.com/cmhughes/latexindent.pl/blob/9cc2d864322c3edf8780d49aa27ba2eb3948e3af/LatexIndent/AlignmentAtAmpersand.pm#L1781

Long fullwidth string makes table broken(It's already formatted).
![image](https://github.com/cmhughes/latexindent.pl/assets/27684488/0fd2b5eb-0515-4302-8a57-064fceab0656)

**Comment by cmhughes** [comment]
Can you try the GCString switch

https://latexindentpl.readthedocs.io/en/latest/sec-appendices.html#the-gcstring-switch

**Comment by rikutons** [comment]
> Can you try the GCString switch
> 
> https://latexindentpl.readthedocs.io/en/latest/sec-appendices.html#the-gcstring-switch

I can't find `cpanm` in my system so I did `cpan` and `m Unicode::GCString ` then switch, but got error.

```
$ cpan
cpan[1]> m Unicode::GCString 
Reading '/home/zkn/.local/share/.cpan/sources/authors/01mailrc.txt.gz'
............................................................................DONE
Fetching with HTTP::Tiny:
https://cpan.org/modules/02packages.details.txt.gz
Reading '/home/zkn/.local/share/.cpan/sources/modules/02packages.details.txt.gz'
  Database was generated on Thu, 25 Apr 2024 11:29:01 GMT
............................................................................DONE
Fetching with HTTP::Tiny:
https://cpan.org/modules/03modlist.data.gz
Reading '/home/zkn/.local/share/.cpan/sources/modules/03modlist.data.gz'
DONE
Writing /home/zkn/.local/share/.cpan/Metadata
Module id = Unicode::GCString
    CPAN_USERID  NEZUMI (Hatuka*nezumi - IKEDA Soji <nezumi@cpan.org>)
    CPAN_VERSION 2013.10
    CPAN_FILE    N/NE/NEZUMI/Unicode-LineBreak-2019.001.tar.gz
    INST_FILE    /usr/lib/perl5/5.38/vendor_perl/Unicode/GCString.pm
    INST_VERSION 2013.10

$ latexindent --GCString t.tex                    
Can't locate object method "new" via package "Unicode::GCString" at /tmp/par-7a6b6e/cache-df055638f838a8ef307c854dc173fed1bba312a0/inc/lib/LatexIndent/AlignmentAtAmpersand.pm line 1789.
```

**Comment by rikutons** [comment]
> Can you try the GCString switch
> 
> https://latexindentpl.readthedocs.io/en/latest/sec-appendices.html#the-gcstring-switch

It worked correctly! I should have read docs more deeply, thanks for advise.
