### ISSUE TITLE
Error when specifiying `lookForAlignDelims` in command line

### ISSUE THREAD

**Issue by plutonium-94** [cmhughes/latexindent.pl#551]
There is an error when specifiying `lookForAlignDelims` in command line:

original .tex code
--
```tex
\documentclass{standalone}

\usepackage{tabularray}

\begin{document}

\begin{tblr}{colspec={*{2}{c}},cell{1}{1}={r=2}{c}}
    {1   \\2}&3\\
     & 4 \\
\end{tblr}

\end{document}
```

command
--
```bash
latexindent test.tex -y="lookForAlignDelims:tblr:alignFinalDoubleBackSlash:1"
```

actual/given output
--
```text
Can't use string ("1") as a HASH ref while "strict refs" in use at C:\Users\User\AppData\Local\Temp\par-55736572\cache-84e8e21fc7334f25e00d5eeab31d6b5c00d22c77\inc\lib/LatexIndent/GetYamlSettings.pm line 753.
```

desired or expected output
--
```tex
\documentclass{standalone}

\usepackage{tabularray}

\begin{document}

\begin{tblr}{colspec={*{2}{c}},cell{1}{1}={r=2}{c}}
        {1   \\2} & 3 \\
                  & 4 \\
\end{tblr}

\end{document}
```

anything else
--
When I change the environment from `tblr` to `tabular` or use yaml settings, it works correctly and produces desired output.

**Comment by cmhughes** [comment]
Many thanks. 

So this is specific to the y switch?

**Comment by plutonium-94** [comment]
> Many thanks.
> 
> So this is specific to the y switch?

Yes, at least I think so.

**Comment by cmhughes** [comment]
Thanks again. This is fixed and released at https://github.com/cmhughes/latexindent.pl/releases/tag/V3.24.3
