### ISSUE TITLE
EndFinishesWithLineBreak breaks before comment

### ISSUE THREAD

**Issue by aronovgj** [cmhughes/latexindent.pl#58]
This example is broken if the switch `EndFinishesWithLineBreak` is set.

```
\documentclass{beamer}

\begin{document}

\begin{frame}
	\begin{minipage}{0.5\textwidth}
		blah
	\end{minipage}% 
	\begin{minipage}{0.5\textwidth}
		blah
	\end{minipage}
\end{frame}

\end{document}
```
Results in: [presentation.pdf](https://github.com/cmhughes/latexindent.pl/files/950034/presentation.pdf)

After latexindent:

```
\documentclass{beamer}

\begin{document}

\begin{frame}
	\begin{minipage}{0.5\textwidth}
		blah
	\end{minipage}
	% 
	\begin{minipage}{0.5\textwidth}
		blah
	\end{minipage}
\end{frame}

\end{document}
```
Results in: [presentation.pdf](https://github.com/cmhughes/latexindent.pl/files/950033/presentation.pdf)

Is that intended? I think latexindent should do the linebreak after the comment, not before.

**Comment by cmhughes** [comment]
Have you tried setting the switch to 2?

**Comment by cmhughes** [comment]
Using `minipage.yaml` as follows

```
modifyLineBreaks:
    environments:
        EndFinishesWithLineBreak: 2
```

and running 

```
latexindent.pl myfile.tex -m -l minipage.yaml
```

then `myfile.tex` is unchanged.

See listings 184, 185 and 186 of the documentation for reference. 

Does this answer this question?

**Comment by aronovgj** [comment]
Yes, that solves the problem. Thank you.
