### ISSUE TITLE
Erroneous indentation

### ISSUE THREAD

**Issue by maetra** [cmhughes/latexindent.pl#59]
I attached a small [file](https://github.com/cmhughes/latexindent.pl/files/951413/test.txt) where latexindent 3.0 is unable to provide a useful indentation. The file is already formatted by latexindent but the \newifs or \newcommands seem to be causing issues.

**Comment by cmhughes** [comment]
Hello!
Using the file `maetra.yaml`:
```
indentPreamble: 1
```

and running
```
latexindent.pl myfile.tex -l maetra.yaml
```
then I get the following, expected, output:
```
\documentclass[]{scrbook}

\newif\ifmake\maketrue
\newif\ifsomefont\somefonttrue

\usepackage[
	acronym]{glossaries-extra}

% Some text
\newcommand{
	\figsmall}{\small}
\newcommand{\figfootnote}{\footnotesize}
\newcommand{\figscript}{\scriptsize}


\begin{document}

\end{document}
```

Is this different from what you get?

**Comment by maetra** [comment]
It definitely is. The output looks like this 

[test.txt](https://github.com/cmhughes/latexindent.pl/files/955103/test.txt)

and this the log file. 

[indent.txt](https://github.com/cmhughes/latexindent.pl/files/955105/indent.txt)

Are you using a different/newer version?

**Comment by cmhughes** [comment]
Thanks a lot for the files, they are very helpful!

I believe that you are working on an earlier version -- did you fork this yourself? The released version (3.0) is slightly different from yours; I can tell, by reviewing your log file, which contains a few things that are not in the released version. 

Could you try updating your distribution and let me know? If you want to update your distribution manually, you'll simply need to copy across the Perl modules from the LatexIndent directory.

**Comment by maetra** [comment]
I believe I downloaded a version from this repository and mistakenly assumed I had an up-to-date version. Sorry for the trouble. I now updated to the latest MiKTeX version and the file has the correct indentation. However, I running into new troubles, I create a new issue for that.

**Comment by maetra** [comment]
These issues only occur with version 2.2. (last version in MikTeX) but not with your current repository. So I dont think the reation on an additional issue is needed.
