### ISSUE TITLE
No output on windows

### ISSUE THREAD

**Issue by musm** [cmhughes/latexindent.pl#60]
texlive 2016, I just updated all the packages and have
latexindent.exe ver 43326
on windows 10 creators update

running `latexindent.exe -h` produces *no* result (i.e. terminal blank)

a while back this used to work so I'm not sure what changed (bummer since I really like this package)

**Comment by cmhughes** [comment]
Thanks for reporting this.

Could you check if latexindent is part of  your distribution? It'll be in
something like texlive/texmf/scripts/latexindent

If it's not, you could try downloading latexindent.exe from here on GitHub?

**Comment by musm** [comment]
![image](https://cloud.githubusercontent.com/assets/4319522/25441527/7cade454-2a70-11e7-8d01-9ffab557c107.png)

yes it does not start with version 3.0 downloaded from github

**Comment by cmhughes** [comment]
I'm running that version on my Windows machine, and it works fine. 

I put the error message you posted into google, and it looks like there are a few tools that you could use to investigate the problem. 

Could you try that and post an update?

**Comment by musm** [comment]
Well some suggest to clean boot, something I will *not* do. This is the first time I have seen this error. 
Which suggestions have you seen that I should try?
I have tried running in compatibility mode, with no  luck.

**Comment by musm** [comment]
Ok so I got it working but I had to install  Strawberry perl and had to do
`
cpan PAR::Packer
cpan YAML::Tiny
pp -o latexindent.exe latexindent.pl
`

**Comment by musm** [comment]
I then moved latexindent.exe to  C:\texlive\2016\bin\win32
and also defaultSettings.yaml to C:\texlive\2016\bin\win32 otherwise I get File 'C:/texlive/2016/bin/win32/defaultSettings.yaml' does not exist at LatexIndent/GetYamlSettings.pm line 40.

**Comment by cmhughes** [comment]
This sounds good, and I'm sorry that you had this issue.

Would you say this is now resolved?

**Comment by musm** [comment]
Yes however, 
The `defaultSettings.yaml` that resides in `C:\texlive\2016\texmf-dist\scripts\latexindent` is not recognized from a source build.  I have to move the defaultSettings.yaml to C:\texlive\2016\bin\win32
is there a reason why the detection code does not recognize the defaultSettings.yaml in  `C:\texlive\2016\texmf-dist\scripts\latexindent`

**Comment by cmhughes** [comment]
When you build the latexindent.exe from source then defaultSettings.yaml
must be in the same directory.

**Comment by cmhughes** [comment]
I'm wondering if your machine is 64 bit? The released version of latexindent.exe is 32 bit.

**Comment by musm** [comment]
Yes it's 64bit.

**Comment by musm** [comment]
is there a script that I can invoke to built it assuming it's going to be for texlive

**Comment by cmhughes** [comment]
There's not a script at the moment. Your issue has highlighted that we do
need a 64 bit version (I don't have a way to generate one at present).

Let me get in touch with the texlive maintainers to see if there's any
conventions that they'd prefer. Once I have an answer on that, I might ask
you to contribute your executable to the project, if you're up for it?

**Comment by cmhughes** [comment]
I contacted the texlive maintainers, and they don't support 64 but windows, so it doesn't seem likely that a 64 bit version will make it there.

I'm wondering how to proceed; on the one hand, I think it would be useful to host a 64 bit version here on GitHub, but I don't have any way to test it as I don't have a 32 bit machine. So, for example, if you were to submit one, I'd have no idea if it worked, or if it were malicious or anything else; do you have any thoughts on this?

**Comment by musm** [comment]
Fair point. Yeah I'm not sure what's the best course of action in this case.  I find it odd that the 32bit binaries don't work on 64bit systems I feel like they should, windows supports running 32bit exe's from a 64bit OS...

**Comment by cmhughes** [comment]
I had my first opportunity to test this today, as I was at a 64 bit Windows machine. The 32 bit binary worked fine on the machine that I was at, so I don't think that there is inherently anything wrong with `latexindent.exe`.

As such, I'd like to apologise again that it didn't work in your case, but I will close this issue for the moment. 

As you said above, if the executable does not work, the best solution is to recreate it yourself using the command that detailed above:
```
cpan PAR::Packer
cpan YAML::Tiny
pp -o latexindent.exe latexindent.pl
```
