### ISSUE TITLE
Q: Does it work for Bibtex.bib files?

### ISSUE THREAD

**Issue by thorade** [cmhughes/latexindent.pl#65]
Just to be sure, does this script also indent Bibtex files?
Also see https://github.com/Glavin001/atom-beautify/issues/291

**Comment by cmhughes** [comment]
Hello!
Yes, by default, 'latexindent' does operate on .bib files :) for example, see 'documentation/contributors.bib' which has been operated upon by 'latexindent'.

Have you tried it?
Best
Chris

**Comment by thorade** [comment]
Right, I should have just tried it...
Tried it now and it does something, not yet what I expected, but I guess I'll have to look at the configuration options (e.g. use two spaces for indentation instead of tabs etc).
Thanks!

**Comment by cmhughes** [comment]
You're welcome :) let me know if you have any issues with it, I'm always trying to improve the project.

**Comment by Pablorg99** [comment]
I have the file:
```
@misc{ wikilatex,
    author = "{Wikipedia contributors}",
    title = "LaTeX --- {Wikipedia}{,} The Free Encyclopedia",
    year = "2020",
    howpublished = "\url{https://en.wikipedia.org/w/index.php?title=LaTeX&oldid=943687862}",
    note = "[Online; accessed 3-March-2020]"
}
```
with 4 spaces as indentation. When I execute `latexindent bibliography.bib` I get this output 
```
@misc{ wikilatex,
author = "{Wikipedia contributors}",
title = "LaTeX --- {Wikipedia}{,} The Free Encyclopedia",
year = "2020",
howpublished = "\url{https://en.wikipedia.org/w/index.php?title=LaTeX&oldid=943687862}",
note = "[Online; accessed 3-March-2020]"
}
```
So latexindent is eliminating my indentation. Am I doing something wrong?
Thanks in advance

**Comment by cmhughes** [comment]
@Pablorg99 thanks for this.

Yes, I confirm that your example above is not indented correctly by default.

You'll need the following YAML file:

Pablorg99.yaml
-
```
fineTuning:
    NamedGroupingBracesBrackets:
      follow: '\h|\R|\{|\[|\$|\)|\(|"'
    UnNamedGroupingBracesBrackets: 
      follow: '\{|\[|,|&|\)|\(|\$|"'
    arguments:
      between: '_|\^|\*|---'
```
This file says that `NamedGroupingBracesBrackets` and `UnNamedGroupingBracesBrackets` can follow `"` and that you allow `---` between arguments. 

When you run
```
latexindent.pl myfile.tex -l=Pablorg99.yaml
```
then you receive:
```
@misc{ wikilatex,
	author = "{Wikipedia contributors}",
	title = "LaTeX --- {Wikipedia}{,} The Free Encyclopedia",
	year = "2020",
	howpublished = "\url{https://en.wikipedia.org/w/index.php?title=LaTeX&oldid=943687862}",
	note = "[Online; accessed 3-March-2020]"
}
```

**Comment by cmhughes** [comment]
I've added the above example to the documentation, as of https://github.com/cmhughes/latexindent.pl/commit/695b23279f555dc3cd4af642c547e28e22f07b46. 

Thanks again :)
