### ISSUE TITLE
License format

### ISSUE THREAD

**Issue by thorade** [cmhughes/latexindent.pl#66]
Very minor improvement: If the license is in a certain format, it will be recognized & displayed by github.
https://github.com/blog/2252-license-now-displayed-on-repository-overview
https://help.github.com/articles/adding-a-license-to-a-repository/

The easiest way to have the right format is to delete the license file and then re-add it from the github web interface by clicking the "Create new file" button and then specifying as filename "License.txt". A dropdown menu will appear and ask what license template to use.

github also just introduced the community checklist:
https://github.com/cmhughes/latexindent.pl/community
https://github.com/blog/2380-new-community-tools

**Comment by cmhughes** [comment]
Thanks very much, this is very helpful! I'll work on resolving this soon :) Apologies for the delayed response, have had a manic week at work, I usually hope to respond more quickly.

**Comment by cmhughes** [comment]
Thanks again for this; as of https://github.com/cmhughes/latexindent.pl/pull/69, this has been implemented, as demonstrated in the following screenshot (see the link for GPL-3.0)

![screenshot from 2017-06-19 18 37 59](https://user-images.githubusercontent.com/2224480/27298023-fee6d966-551e-11e7-8bbd-80e0eb31e225.png)

Thanks for the link about the community; feature requests and code of conduct have, so far, been smooth. I'll continue to think about them, and may well review their necessity, but for the moment, I won't implement them.

Thanks again!
Chris
