### ISSUE TITLE
-y|--yaml switch

### ISSUE THREAD

**Issue by cmhughes** [cmhughes/latexindent.pl#79]
I'd like to explore the option of having a `-y` or `--yaml` switch in which users could pass `YAML` settings through this switch, rather than having to specify a file.

Possible implementation could use comma separated for each field, and if new lines are required, a semi-colon could be used; for example
```
latexindent.pl -y=defaultIndent="" myfile
latexindent.pl -y=defaultIndent:"",maxNumberOfBackUps:1 myfile
latexindent.pl -y=defaultIndent:"",logFilePreferences;;showEveryYamlRead:1 myfile
```

**Comment by cmhughes** [comment]
Figure 1 and the surrounding text will need updating

**Comment by cmhughes** [comment]
Implemented as of https://github.com/cmhughes/latexindent.pl/commit/08c4cdb68af3376a1972db7e99956b298362daa2

Note that there was no need for semi-colons:
```bash
latexindent.pl myfile.tex -y="defaultIndent: ' '"
latexindent.pl myfile.tex -y="indentRules: one: '\t\t\t\t'"
latexindent.pl myfile.tex -y='modifyLineBreaks:environments:EndStartsOnOwnLine:3' -m
latexindent.pl myfile.tex -y='modifyLineBreaks:environments:one:EndStartsOnOwnLine:3' -m
```

**Comment by cmhughes** [comment]
Resolved as of https://github.com/cmhughes/latexindent.pl/pull/83

**Comment by cmhughes** [comment]
@karlkoeller

This feature may be of interest to you :)

**Comment by karlkoeller** [comment]
Thanks Chris, very interesting feature 👍

**Comment by cmhughes** [comment]
Thought you might be interested for use with WinEdt :)


It would avoid the need to create a localSettings.yaml file.
