### ISSUE TITLE
path instead of file name for -l switch

### ISSUE THREAD

**Issue by seregaxvm** [cmhughes/latexindent.pl#82]
According to indent.log file, if I would issue a command `latexindent -l=mysettigns.yaml project/target.tex`, it searches for the `mysettigns.yaml` file in the `./project/` directory. I think it would be better if program would treat `-l` switch argument as a path to a file instead of a file name in target directory.

Desired behavior:
Command `latexindent -l=/tmp/mysettigns.yaml project/target.tex` would read settings from `/tmp/mysettigns.yaml` file and indent `./project/target.tex` accordingly.

**Comment by cmhughes** [comment]
Yep, this has been on my mind for a while, thanks for bringing it up here! :) I'll label this as an enhancement; there's a few issues to resolve ahead of this one, but consider it on the list :)

**Comment by cmhughes** [comment]
Thanks again, you've given me the impetuous to get this done; as of https://github.com/cmhughes/latexindent.pl/commit/bfb5d25fe135d6aa83cf2416fc0666b2fa2409d9 it is implemented. Feel free to clone the develop branch and you can test it. 

It'll be included as part of V3.3, coming soon!

**Comment by cmhughes** [comment]
Thanks again, this is resolved as of https://github.com/cmhughes/latexindent.pl/pull/83, which will be uploaded to ctan momentarily.
