### ISSUE TITLE
[Feature Request] Allow input from STDIN

### ISSUE THREAD

**Issue by gpanders** [cmhughes/latexindent.pl#88]
Allow input from stdin, i.e.

`cat file.tex | latexindent -`

This would allow `latexindent` to be used in editors that can allow programs to be run on a "selection" instead of the whole file (e.g. vim).

**Comment by cmhughes** [comment]
Nice idea! I'll look into this at some point soon (a few issues are ahead of this one). 

Alternatively, if you have any ideas of how to get it working, feel free to have a go and submit a pull request :)

**Comment by cmhughes** [comment]
As of https://github.com/cmhughes/latexindent.pl/commit/6f4ecd20a4a518b51bcb039f842069697a50eb40 I'd say that this is implemented. 

Would you like to clone the `develop` branch and test it? For example, 
```
cat myfile.tex|latexindent.pl
```

**Comment by whitecat** [comment]
Oh this will make my website more stream lined. I like this feature. I may not need to save latex as a file before using the app.

**Comment by whitecat** [comment]
I am having problems running `latexindent.pl` in development. What are the dependencies I need to install before running development?

**Comment by cmhughes** [comment]
Sorry to hear that! The develop version uses a new module for logging; take
a look at the module installer helper script:

https://github.com/cmhughes/latexindent.pl/blob/develop/helper-scripts/latexindent-module-installer.pl

Let me know how you get on with this, it would be good to know if I can
improve things.

**Comment by whitecat** [comment]
I tested out the input from stdin. Worked great!

**Comment by cmhughes** [comment]
That's excellent, thanks very much!

**Comment by cmhughes** [comment]
Does this have positive implications for your website?

**Comment by whitecat** [comment]
This does have postitive implications. I no longer have to save a file on my server and delete it. I can just echo the string into latexindet.pl and get the results.

**Comment by cmhughes** [comment]
Implemented in V3.4 as of https://github.com/cmhughes/latexindent.pl/pull/96 thanks for the suggestion!
