### ISSUE TITLE
issues with brackets such as $[a,b)$

### ISSUE THREAD

**Issue by anderstood** [cmhughes/latexindent.pl#89]
The line `should not be indented` gets indented when running `latexindent` with the following code:

````
\documentclass{standalone}

\begin{document}
symmetric brackets $[a,b]$
asymmetric brackets $[a,b)$
should not be indented!
\end{document}
````
Presumably, this is because the closing bracket `]` is expected.

`latexindent.pl version 2.1R
`

**Comment by cmhughes** [comment]
Thanks for this!

I'd believe that `V2.1R` would struggle with this. I'd highly recommend an update. As of writing, the current version is `V3.3` and is *significantly* improved and more robust than `V2.1R`. Indeed, with `V3.3`, the output is the following, which I believe is as intended:
```
\documentclass{standalone}

\begin{document}
symmetric brackets $[a,b]$
asymmetric brackets $[a,b)$
should not be indented!
\end{document}
```
Take a look at https://tex.stackexchange.com/questions/55437/how-do-i-update-my-tex-distribution for details of how to update your distribution. Let me know if you have any troubles with this!
