### ISSUE TITLE
"Not a HASH reference" error

### ISSUE THREAD

**Issue by lenis2000** [cmhughes/latexindent.pl#91]
When running latexindent (3.3) on a TeX file, there is an error
`Not a HASH reference at LatexIndent/GetYamlSettings.pm line 87.`

When commenting this line, the same error is about line 90. Commenting that line, too, seems to eliminate the errors. However, then the configs do not seem to be loaded properly.

My environment:
- Mac, High Sierra
- perl 5, version 26, subversion 0 (v5.26.0) built for darwin-thread-multi-2level
- latexindent 3.3, downloaded from GitHub

**Comment by cmhughes** [comment]
Thanks for reporting this. Line 87 of `GetYamlSettings.pm` is all to do with user configuration file `indentconfig.yaml` or `.indentconfig.yaml`.

Can you check that `indentconfig.yaml` contains valid YAML? A small sample is
```
paths:
  - /home/cmhughes/Documents/yamlfiles/mysettings.yaml
```
Feel free to post your `indentconfig.yaml` file here, if you like.

**Comment by lenis2000** [comment]
By the way, I recently reinstalled the system, and before it all worked well with latexindent 3.1

The file .indentconfig.yaml looks as

```
paths:
- /Users/leo/.vim/latexindent/latexindent.yaml
```

**Comment by cmhughes** [comment]
Yaml is very sensitive to spaces; could you try formatting your file to match the one that I gave?

I will install perl 5.26.0 over the weekend to see if that's an issue.

**Comment by cmhughes** [comment]
I tested on `Perl V5.26.0` and have received no error on my machine (Ubuntu Linux 16.04, perlbrew).  

Can you check your `.indentconfig`, possibly recreating it from scratch, and let me know?

**Comment by lenis2000** [comment]
Thank you! somehow after uncommenting the lines 87 and 90 back, it started working on my machine (I did not touch the YAML config). Next if I have similar issues I'll make sure the config is correctly formatted in YAML.
