### ISSUE TITLE
Consider adding CI

### ISSUE THREAD

**Issue by bvwells** [cmhughes/latexindent.pl#92]
Hey Chris,
Just wondering if it's worth adding continous integration to the project for automatic build and test running on each PR with something like Travis CI or Circle CI.

Have a look at:
 https://docs.travis-ci.com/user/languages/perl/

Cheers,
Ben

**Comment by cmhughes** [comment]
Many thanks indeed for this, Ben! This sounds a sensible addition to the project; I've labeled it as an enhancement and hope to get it to it soon. 

I tend to try to address user-issues in order, and there are a few ahead of this one; it may be a little while until I can get to this, but it is certainly on the list.

Thanks again!
Chris

----
For my reference: https://github.com/bvwells/go-patterns

**Comment by cmhughes** [comment]
Possible to get Appveyor to create the Windows executable and resubmit it back to the repo? poasible to not have executable tracked....? Create executables for each OS?

**Comment by koppor** [comment]
In case you need linux commands only to generate distributions files, CircleCI 2.0 works well. You can just execute normal commands. See https://github.com/gi-ev/LNI-proceedings/blob/master/.circleci/config.yml for an example. It is also possible to commit something back into the original repository: A private SSH key can be injected in the build environment.

**Comment by cmhughes** [comment]
@koppor thanks for this; I'm interested in exploring the idea of committing something back into the original repo -- have you got a reference or example?

**Comment by koppor** [comment]
Sure. Here the better deep link:

1. Script: https://github.com/latextemplates/LNCS/blob/master/.circleci/deploy-ghpages.sh
2. Script caller: https://github.com/latextemplates/LNCS/blob/master/.circleci/config.yml

The "deploy-ghpages.sh" is for deploying something on the gh-pages branch, but the script can be adapted.

Important settings at CircleCI:

![grafik](https://user-images.githubusercontent.com/1366654/35457730-37efb91c-02da-11e8-8b9c-907562e69a91.png)

![grafik](https://user-images.githubusercontent.com/1366654/35457814-7a0101c6-02da-11e8-9550-27c4c939d253.png)

![grafik](https://user-images.githubusercontent.com/1366654/35457845-96d5a1f8-02da-11e8-8135-f4fcfbb5fdc2.png)

Add the SSH key to GitHub:

![grafik](https://user-images.githubusercontent.com/1366654/35458234-de03df94-02db-11e8-92c3-9393f05d1931.png)

Maybe, it's that setting at the user settings:

![grafik](https://user-images.githubusercontent.com/1366654/35458327-2eabc948-02dc-11e8-9c05-544abd99415a.png)

**Comment by cmhughes** [comment]
@bvwells I'd say there's a first implementation of this as of https://github.com/cmhughes/latexindent.pl/commit/802ba717e4592d418e7749061153e45479275820 

Do you fancy taking a look? All feedback welcome :)

**Comment by bvwells** [comment]
Looks good to me! The only thing I'd consider changing is the position of the badge in the readme. It's nice to see the bage at the top of the readme so you can instantly see whether the build is good to fork. 

Good work!

**Comment by koppor** [comment]
Uploading via Travis is harder, because you need to encrypt the SSH private key there. Nevertheless, for another project, I have a tutorial there: https://github.com/ultimate-comparisons/ultimate-comparison-BASE/blob/master/docs/Travis_Build_Deploy.md

**Comment by cmhughes** [comment]
@bvwells  many thanks, good tip, all done!

@koppor thanks very much for the tips. I'll continue to look into this, it's helpful to have the references, thanks.

**Comment by cmhughes** [comment]
@bvwells AppVeyor integration implemented as of https://github.com/cmhughes/latexindent.pl/commit/4f2c3697cc181d4d0887c65c638491e413d3b5f0

**Comment by bvwells** [comment]
Good work @cmhughes!

**Comment by cmhughes** [comment]
Hi Ben :)
Thanks again for raising this, it was really helpful.

I thought you might like to see that as of https://github.com/cmhughes/latexindent.pl/commit/5f0641e72e29c44ae01c57e8561a81e4713515de I've implemented a github action to perform some checks.

The code that governs it is in https://github.com/cmhughes/latexindent.pl/blob/5f0641e72e29c44ae01c57e8561a81e4713515de/.github/workflows/batch-check.yaml

Also, the other github action in https://github.com/cmhughes/latexindent.pl/blob/5f0641e72e29c44ae01c57e8561a81e4713515de/.github/workflows/publish-windows-exe.yaml generates the Windows executable and uploads it to github on each release :)

All the best
Chris
