### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by Koltharius** [cmhughes/latexindent.pl#93]
Hello, I am unable to install latexindent in Ubuntu to use it with atom-beautify extension of atom, please consider including some instructions in the README for clumsy people :disappointed: :cry: 

Thank you

**Comment by cmhughes** [comment]
Hi @Koltharius 
Thanks for your message, and I'm very sorry to hear that you've had trouble installing `latexindent.pl`. 

I'm certainly open to making my `readme` clearer; do you have anything specific that you'd like to see in there? In case it's relevant to this issue, I created a helper script for the installation of the `perl` modules (https://github.com/cmhughes/latexindent.pl/blob/develop/helper-scripts/latexindent-module-installer.pl) which will be part of the next release.

Let me know what you think!
Best
Chris

**Comment by Koltharius** [comment]
Yay thanks a lot :smile:
