### ISSUE TITLE
Falsely inserted & character in table due to special command

### ISSUE THREAD

**Issue by pat-s** [cmhughes/latexindent.pl#95]
Hi @cmhughes,

consider the following table **input**. When compiled with `arara` 4.0 and the `latexindent` rule, it results in the falsely formatted **output**. This output cannot be compiled anymore because `latexindent` accidentally inserts two `&` because it tries to align the `\\` linebreak characters.

This behaviour is caused by the custom class `specialcell` that lets me insert linebreaks in table cells and looks as follows:

```latex
\newcommand{\specialcell}[2][l]{%
  \begin{tabular}[#1]{@{}l@{}}#2\end{tabular}}
```

Any idea how to handle that case? I've read quickly through the manual and have the impression that excluding certain parts/commands is certainly possible but wasn't able to figure out how to do so in detail that quickly.

**Input**
```latex
%% cv results
\begin{table}[b!]
	\centering
	\caption[]{Repetition mean \ac{AUROC} values (bold) and runtime (minutes) for each model and \ac{CV} setting for 200 random search iterations.}
	\begingroup\footnotesize
	\begin{tabular}{lllll}
		\\
		          & \specialcell{Non-Spatial/Non-Spatial \\ {(nsp/nsp)}} & \specialcell{Spatial/Non-Spatial \\ {(\emph{sp/nsp})}} & \specialcell{Spatial/Spatial \\ {(\emph{sp/sp})}} & \specialcell{Spatial/No Tuning \\ {(\emph{sp/not})}}       \\
		\hline
		\ac{SVM}  & \textbf{0.906}, 134.30               & \textbf{0.858}, 152.16  & \textbf{0.844}, 128.10  & \textbf{0.814}, 0.31 \\
		\ac{RF}   & \textbf{0.945}, 1697.41              & \textbf{0.872}, 1651.95 & \textbf{0.863}, 1594.90 & \textbf{0.872}, 0.28 \\
		\ac{BRT}  & \textbf{0.949}, 2923.66              & \textbf{0.873}, 2905.61 & \textbf{0.859}, 2895.17 & \textbf{0.771}, 0.20 \\
		\ac{WKNN} & \textbf{0.895}, 86.67                & \textbf{0.839}, 113.21  & \textbf{0.839}, 81.66   & \textbf{0.841}, 0.22 \\
		\bottomrule
	\end{tabular}
	\endgroup
	\label{tab:cv_results}
\end{table}
```

**Output**
```latex
%% cv results
\begin{table}[b!]
	\centering
	\caption[]{Repetition mean \ac{AUROC} values (bold) and runtime (minutes) for each model and \ac{CV} setting for 200 random search iterations.}
	\begingroup\footnotesize
	\begin{tabular}{lllll}
		\\
		          & \specialcell{Non-Spatial/Non-Spatial &                         &                         &                      \\ {(nsp/nsp)}} & \specialcell{Spatial/Non-Spatial \\ {(\emph{sp/nsp})}} & \specialcell{Spatial/Spatial \\ {(\emph{sp/sp})}} & \specialcell{Spatial/No Tuning \\ {(\emph{sp/not})}}       \\
		\hline
		\ac{SVM}  & \textbf{0.906}, 134.30               & \textbf{0.858}, 152.16  & \textbf{0.844}, 128.10  & \textbf{0.814}, 0.31 \\
		\ac{RF}   & \textbf{0.945}, 1697.41              & \textbf{0.872}, 1651.95 & \textbf{0.863}, 1594.90 & \textbf{0.872}, 0.28 \\
		\ac{BRT}  & \textbf{0.949}, 2923.66              & \textbf{0.873}, 2905.61 & \textbf{0.859}, 2895.17 & \textbf{0.771}, 0.20 \\
		\ac{WKNN} & \textbf{0.895}, 86.67                & \textbf{0.839}, 113.21  & \textbf{0.839}, 81.66   & \textbf{0.841}, 0.22 \\
		\bottomrule
	\end{tabular}
	\endgroup
	\label{tab:cv_results}
\end{table}
```

**Comment by cmhughes** [comment]
Hello! Thanks for this :)

I'd recommend saving the following into the file `pat-s.yaml`
```
lookForAlignDelims:
   tabular: 
      alignRowsWithoutMaxDelims: 0
      alignDoubleBackSlash: 0
```
and then run your file with
```
latexindent.pl -l=pat-s.yaml myfile.tex
```
which gives
```


%% cv results
\begin{table}[b!]
\centering
\caption[]{Repetition mean \ac{AUROC} values (bold) and runtime (minutes) for each model and \ac{CV} setting for 200 random search iterations.}
\begingroup\footnotesize
\begin{tabular}{lllll}
	\\
	& \specialcell{Non-Spatial/Non-Spatial \\ {(nsp/nsp)}} & \specialcell{Spatial/Non-Spatial \\ {(\emph{sp/nsp})}} & \specialcell{Spatial/Spatial \\ {(\emph{sp/sp})}} & \specialcell{Spatial/No Tuning \\ {(\emph{sp/not})}}       \\
	\hline
	\ac{SVM}  & \textbf{0.906}, 134.30  & \textbf{0.858}, 152.16  & \textbf{0.844}, 128.10  & \textbf{0.814}, 0.31 \\
	\ac{RF}   & \textbf{0.945}, 1697.41 & \textbf{0.872}, 1651.95 & \textbf{0.863}, 1594.90 & \textbf{0.872}, 0.28 \\
	\ac{BRT}  & \textbf{0.949}, 2923.66 & \textbf{0.873}, 2905.61 & \textbf{0.859}, 2895.17 & \textbf{0.771}, 0.20 \\
	\ac{WKNN} & \textbf{0.895}, 86.67   & \textbf{0.839}, 113.21  & \textbf{0.839}, 81.66   & \textbf{0.841}, 0.22 \\
	\bottomrule
\end{tabular}
\endgroup
\label{tab:cv_results}
\end{table}
```
Does this look as you'd like?

**Comment by pat-s** [comment]
Hi Chris, 

thanks for the quick reply, that looks good!

However, I am struggling to insert the `-l` switch in the `arara` 4.0 [rule](https://github.com/cereda/arara/blob/master/rules/indent.yaml).
How do I have to hand over the YAML file in the to `settings` parameter? 
I tried various options, also combining it with the `where` parameter but I was not successful.
Maybe @cereda can help us here?

**Comment by cmhughes** [comment]
Over to you, Paulo! :)

To confirm, the -l switch can take an optional parameter, so for example,
both of the following are allowed:

latexindent -l myfile.tex
latexindent -l=mysettings.yaml myfile.tex

**Comment by cereda** [comment]
Oh my, I only noticed this thread today, and I am currently in the shaky 
bus, far from my laptop! Apologies!

I will take a closer look at it later on today, deeply sorry for the delay!

Cheerio!

**Comment by pat-s** [comment]
No worries Paulo, I will most likely survive a few days without the `latexindent` rule :smile: 
Much appreciated!

**Comment by cereda** [comment]
Still in the shaky bus. 😀

The `indent` rule has a suspicious entry regarding logging, so it is one for future check.

Try adding `settings: local` and `where: yourfile.yaml` to the directive. It should work, I guess. Or not. 😀

**Comment by pat-s** [comment]
That works! However, the custom yaml file is not honored using `arara`.

Using `latexindent.pl` standalone, everything works as desired using `latexindent -l -w`.

I do not have time right now to dig deeper why this happens, but here is my config:

```
%%%% using 'arara' 4.0
% arara: xelatex: {synctex: yes, interaction: nonstopmode}
% arara: bibtex
% arara: xelatex: {synctex: yes, interaction: nonstopmode}
% arara: xelatex: {synctex: yes, interaction: nonstopmode}

% arara indent: {overwrite: yes, settings: local, where: localSettings.yaml}

% arara: clean: { extensions: [ aux, bbl, bcf, cod, blg, lof, lot, out, toc, log, xml, bak0 ] }
```

So this seems to be  a case for inspector Paulo :-) Happy to part it to `arara` as its not an `latexindent` issue anymore :smile:

**Comment by cereda** [comment]
Drat! Can't we still blame Chris? 🤣 

Quick question: is there a quick way of hinting if the local setting is being used by the script? If so, it can make my life easer.

**Comment by pat-s** [comment]
Inspector at work :duck: 

As a workaround I currently combine `arara` and `latexindent` like this:

```bash
arara elsarticle-template.tex && ~/software/latexindent.pl-master/latexindent.pl -w -l /mnt/mccoy/home/patrick/PhD/papers/2017_ESM/02_writing/files/localSettings.yaml /mnt/mccoy/home/patrick/PhD/papers/2017_ESM/02_writing/files/elsarticle-template.tex
```

**Comment by cereda** [comment]
@cmhughes: Chris, out of curiosity, is it possible to include in the `.log` file an entry about the local file? For example, if I issue `-l=foo.yaml`, I could get:

```
File 'foo.yaml' loaded from the -l argument.
```

Or something along those lines.

@pat-s: Patrick, could you help me reduce the issue to a very small example? My tests haven't raised anything suspicious. First, I tried using a reference to a nonexistent file:

```tex
% arara: indent: { settings: local, where: foo.yaml }
```

When running `arara --dry-run test.tex`, I get:

```
[latexindent, -l=foo.yaml, test.tex]
```

If I run `latexindent -l=foo.yaml test.tex` directly, I basically get the same log file modulo date. As expected, in both cases, I get a warning about a nonexistent file. If I create an empty `foo.yaml`, the logs remain the same as well, but both do not mention the loading (hence my question to Chris).

I cannot think of what's going on, and perhaps a better example is need. Could you help me? If so, I think we could move this discussion to the `arara` project.

Thank you!

**Comment by pat-s** [comment]
Hope the reprex will be helpful :tada: :smile:

**Comment by cmhughes** [comment]
lol! I've posted log files in https://github.com/cereda/arara/issues/99

**Comment by cereda** [comment]
![Quack](https://user-images.githubusercontent.com/302062/34848766-1e51e39c-f707-11e7-8de7-d3ba6d34a86d.png)

# I haz fixes!

**Comment by cmhughes** [comment]
Ace! Your love of ducks is most inspiring :)
