### ISSUE TITLE
defaultSettings.yaml searched on wrong path

### ISSUE THREAD

**Issue by koppor** [cmhughes/latexindent.pl#97]
I use latexindent.pl 3.4 on texlive 2017 on Windows 10. When latexindent is called, it outputs following error message:

```
File 'd:/texlive/2017/bin/win32/defaultSettings.yaml' does not exist at D:\temp\user\par-4f6c69766572\cache-6b2249f7bb5d39e637de46e97eb0dc0bea92e452\inc\lib/LatexIndent/GetYamlSettings.pm line 51.
```

The error output is true, as the file is located at `D:\texlive\2017\texmf-dist\scripts\latexindent\defaultSettings.yaml`

Is this an issue of texlive? - When using latexindent on miktex (windows), everything works fine.

**Comment by cmhughes** [comment]
Thanks for reporting this!

I can confirm this is a bug, and commit to getting it fixed very soon, hopefully over the weekend of 20th Jan 2018. Assuming I can fix it, it'll be merged in as a hotfix, and uploaded to ctan, and then an update of your texlive should fix it.

In the meantime, if you feel like delving into the code, you can change the offending line in `GetYamlSettings.pm` to 
```
$defaultSettings = YAML::Tiny->read( "$FindBin::RealBin/defaultSettings.yaml" ) if(-e "$FindBin::RealBin/defaultSettings.yaml");
```

**Comment by cmhughes** [comment]
Resolved as of https://github.com/cmhughes/latexindent.pl/commit/2440534c3ebe53483798bf932c9663e0173fc649 and uploaded to ctan as V3.4.1. 

Give the ctan maintainers 24 hours from now, and then the mirrors usually need another 24 hours or so. If you run a texlive update from (about) Sunday 21st January, you should pick up V3.4.1.

Thanks again!

**Comment by koppor** [comment]
Thank you for the quick action taken. My hotfix was to just copy over the file to the other location. 😇
