### ISSUE TITLE
\@ifpackageloaded should be treated as an "if"

### ISSUE THREAD

**Issue by koppor** [cmhughes/latexindent.pl#98]
Input

```
\@ifpackageloaded{tex4ht}{\def\iftex4ht{\iftrue}}
                         {\def\iftex4ht{\iffalse}}
```

Output

```
\@ifpackageloaded{tex4ht}{\def\iftex4ht{\iftrue}}
{\def\iftex4ht{\iffalse}}
```

Expected Output (with defaultindent two spaces)

```
\@ifpackageloaded{tex4ht}{\def\iftex4ht{\iftrue}}
  {\def\iftex4ht{\iffalse}}
```

**Comment by cmhughes** [comment]
Thanks for this! :)

You need to tweak `noAdditionalIndentGlobal` (see Listings 65 and 66 of V3.3); for example, if you have the following

## localSettings.yaml
```
defaultIndent: '  '
noAdditionalIndentGlobal:
    commands: 0
```
and run 
```
latexindent.pl -l myfile.tex
```
then you receive the output you desired above.

**Comment by koppor** [comment]
Yeah, this fixes the `@\ifpackageloaded` thing, but corrupts other things:

```
\epstopdfDeclareGraphicsRule{.svg}{pdf}{.pdf}{%
  inkscape -z -D --file=#1 --export-pdf=\OutputFile
}
```

gets a double indent

```
\epstopdfDeclareGraphicsRule{.svg}{pdf}{.pdf}{%
    inkscape -z -D --file=#1 --export-pdf=\OutputFile
  }
```

So, closing braces are not aligned. Yeah, this could be the desired effect of that configuration, but that's not what I wanted to achieve 😇 

Seems, I just have to relayout my `@ifpackageloaded` statement to a multiline one, then the indent works correctly.

**Comment by cmhughes** [comment]
This behaviour is expected, and intentional :)

See the discussion around Listings 116 and 117 of the documentation of V3.4.1: 

*We define the ‘body’ of a command as any lines following the command name that include
its optional or mandatory arguments.*

**Comment by koppor** [comment]
OK 🎉 - I go with reformatting 😇
